### ISSUE TITLE
[Installation] @beartype circularly imports dependencies at install-time

### ISSUE THREAD

**Issue by leycec** [beartype/beartype#108]
@posita uncovered an ongoing tragedy [in his most recent *force majeure*](https://github.com/beartype/beartype/pull/103). Our top-level `setup.py` transitively imports `beartype.typing`, which then circularly imports the optional third-party `typing_extensions` runtime dependency under certain inscrutable conditions we'd rather not think about.

**This is badness incarnate.** But lose no hope, all! A solution slinks from the shadows like an uncompromising badass. Let's:

* Refactor the root `beartype.__init__` submodule to only conditionally import from the remainder of the codebase *if and only if* that submodule is *not* being imported by the top-level `setup.py` script. In theory, detecting that condition should be "trivial," "safe," and "portable." How? "Simple."

Because I just air-quoted everything, you should now be concerned. In `setup.py`, "just":

```python
# Dynamically create a new fake module. Look. Just do it.
import types
fake_module = types.ModuleType('beartype.__is_installing__', 'This is horrible.')

# Dynamically register the fake module. Don't look like that.
import sys
sys.modules['beartype.__is_installing__'] = fake_module
```

In `beartype.__init__`, just:

```python
import sys
if 'beartype.__is_installing__' not in sys.modules:
    import from beartype._decor.main import beartype
    from beartype._decor.conf import (
        BeartypeConf,
        BeartypeStrategy,
    )
```

@TeamSpen210: *please help.* We're begging here. You are the wizard @beartype deserves. Is this awful? Is there a genuinely trivial, safe, and portable way to go about this *or* are we stuck with the above sanity-rending miasma?

**Comment by TeamSpen210** [comment]
Hmm, well you don't need to do that. First, you'd want to eliminate the beartype dependencies `beartype.meta` has - they're both only used in `_make_libs_testtime_optional()`, which I think is wrong in the first place. Dependencies shouldn't really change depending on which wheel you read them from, instead you should be able to make them a constant and use [environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) to specify when it can be used. Then you can use `exec()` to directly load the file in `setup.py`, avoiding the rest of beartype entirely. 

However, I'm not entirely sure why most of the constants in that module are present there. Are you importing them anywhere else? I think it'd probably be better in general to move the specifications to `pyproject.toml` or `setup.cfg` - since these are declarative config files, tools are able to just read them and get information instead of needing to run code to figure out stuff. The packaging ecosystem I think is trying to move away from `setup.py` since it's able to do anything, and is therefore unanalysable. It does mean a bit of duplication perhaps, but probably not too much. For specific things like the version, what you can do is fetch it from existing data:
* `importlib.metadata` (stdlib 3.8+) or `importlib_metadata` (backport for Py3.7+) allows fetching it from the package metadata.
* I'm personally using [`versioningit`](https://github.com/jwodder/versioningit), which fetches versions from Git tags at wheel build time. If the current commit is tagged, it's set to that, otherwise it's set to something like `4.2.1.post12+git#76b005e`, so you know which commit is used. For user installs, it can write the version to a generated module, so you don't need it as a dependency then, only at wheel build.
* There's a bunch of other packages available for the same sort of thing, not sure if others might fit your release workflow better.

**Comment by leycec** [comment]
> ...you should be able to make them a constant and use [environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) to specify when it can be used.

**This is legit.** I'd entirely forgotten about environment markers, because this spongy brain matter is running on fumes.

> It does mean a bit of duplication perhaps...

> ...a bunch of other packages...

**Heathenism!** I *absolutely* grok the community consensus here.

I just happen to stridently disagree, because I live in a decaying cabin and sleep on an uncomfortable bed of organic squash grown from our garden. :seedling: 

Violating DRY and adding build-time dependencies just to avoid violating DRY is a no-go, which is why I'm in opposition to the consensus approach. But don't get me wrong: *I passionately despise* `setuptools`. You'd be mad not to, right? I just have yet to find a solution that satisfies sanity.

Until then... environment markers and crude `setup.py` kludges it is. Let's a-go!

![woo](https://c.tenor.com/BHTvXyxzQEcAAAAC/wrestler-woo.gif)

**Comment by leycec** [comment]
The sweat on my trembling upper lip is real. Thankfully, so is 8da3ab4. B-b-but... *does it pass CI!?!?* <sup>*grips mouse tightly*</sup>

**EDIT:** Nope. `</sigh>`
