### ISSUE TITLE
[Upstream Bug] VSCode + Pylance + Pyright linter errors on @beartype

### ISSUE THREAD

**Issue by rbroderi** [beartype/beartype#126]
Type of "beartype" is partially unknown
  Type of "beartype" is "Overload[(obj: BeartypeableT@beartype) -> BeartypeableT@beartype, (*, conf: BeartypeConf) -> ((BeartypeableT@BeartypeConfedDecorator) -> BeartypeableT@BeartypeConfedDecorator), (obj: BeartypeableT@beartype, *, conf: BeartypeConf = BeartypeConf()) -> (BeartypeableT@BeartypeReturn | ((BeartypeableT@BeartypeConfedDecorator) -> BeartypeableT@BeartypeConfedDecorator))]"Pylance[reportUnknownVariableType](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)

**Comment by leycec** [comment]
Me:

![yup, it's me](https://c.tenor.com/8Ys5O0Y00m8AAAAM/angry-mad.gif)

Pyright:

![defly pyright](https://img-9gag-fun.9cache.com/photo/aN0rnYK_700bwp.webp)

Pyright continues its endless litany of fake news. See issue #127 on what Pyright is and why it's to blame here, yet again.

Thankfully, [mypy](http://mypy-lang.org) emits no such complaints. Since [mypy](http://mypy-lang.org) is Python's industry-standard static type checker and therefore almost certainly right about everything, Pyright is *almost certainly* wrong here.

Kinda sounds like Pyright fails to fully support (PEP 484-compliant overloads](https://peps.python.org/pep-0484/#function-method-overloading), which would be no surprise. Overloads are non-trivial. Pyright's emphasis is on speed rather than correctness, so... :shrug: 

That said, I can't really close this with a "lolbro pyright broke" like I deviously did at issue #127. Even though Pyright is *almost certainly* wrong here, we can't have VSCode **+** Pylance throwing up all over itself whenever it trips into @beartype. I'll locally install Pyright and see if I can't do a deep dive on Pyright at some point.

That said, **Pyright is not really a priority** – especially when Pyright is *almost certainly* wrong. mypy? Now that's a priority, because *everyone* uses mypy. Pyright? That's pretty much only used by VSCode **+** Pylance.

Honestly, I wish someone who is not me would author an awesome mypy-based VSCode Python plugin. Then, everybody could just quietly abandon Pylance and Pyright for that. Ain't nobody got unpaid volunteer time to sort out janky non-standard type-checkers. :face_exhaling:

**Comment by leycec** [comment]
**[Glorious FAQ entry that solves everything is up](https://github.com/beartype/beartype#id27).**

Since `pyright` refuses to fix its violations of typing standards required by @beartype, our only recourse is to advise all VSCoders (...*this means you*) to [embrace the VSCode Mypy extension](https://marketplace.visualstudio.com/items?itemName=matangover.mypy). Let's pretend I actually tested those instructions. :sweat_smile: 

Big thanks to @rbroderi for this and the companion issue #126!

**Comment by leycec** [comment]
**Gah!** See [issue #127 for fast and furious details](https://github.com/beartype/beartype/issues/127#issuecomment-1157346407).

**Comment by leycec** [comment]
**Bwaha!** @beartype now officially supports `pyright`. Because you care, we care. See [concluding commentary at issue #127](https://github.com/beartype/beartype/issues/127#issuecomment-1164071613) for further fugly details.
