### ISSUE TITLE
__defaults__ and __kwdefaults__ for @beartype'ed functions

### ISSUE THREAD

**Issue by stevemarin** [beartype/beartype#129]
Hello, and thank you very much for Beartype!  I'm trying to do the following to access default functions for @beartype'd functions:

```
from typing import Annotated
from beartype import beartype
from beartype.vale import Is

PositiveInt = Annotated[int, lambda x: x > 0]

@beartype
def func(*, a: PositiveInt = 3, b: str = "bob"):
    return (a, b)

print(func.__kwdefaults__)
```

Unfortunately with the decorator, I'm lost as to how to access the defaults, since I get this:

```
{'__beartype_func': <function func at 0x00000171A8CFDA20>, '__beartype_raise_exception': <function raise_pep_call_exception at 0x00000171A30385E0>}
```

The issue seems to arise when type hints are provided...  For example, this function signature works fine:

```
@beartype
def func(*, a = 3, b = "bob"):
    return (a, b)

print(func.__kwdefaults__) # returns {'a': 3, 'b': 'bob'}
```

Do you have any thoughts?  Thanks again!

**Comment by TeamSpen210** [comment]
With no type hints, beartype recognises there's nothing for it to check, so it just returns the original function unchanged. With hints, it generates a new function which does the checking, then calls the original. You should be able to access the original function with the `__wrapped__` attribute, so do `func.__wrapped__.__kwdefaults__`.

**Comment by stevemarin** [comment]
I realized my problem immediately after hitting submit when I viewed `func.__kwdefaults__["__beartype_func"].__kwdefaults__` without printing it.  Thank you very, very much!

**Comment by leycec** [comment]
@TeamSpen210: :open_mouth: How do you know everything? Not even the all-knowing Wikipedia knows. Thanks so much for the 0-second save yet again, bear bro.

**Relatedly:** this is something that will go away in a future @beartype release. Why? Because @beartype will perfectly reproduce the signature of the decorated function, including both `__defaults__` and `__kwdefaults__` dunder attributes. Until then, I profusely apologize for the `func.__wrapped__.__{kw,}defaults__` workaround.
