### ISSUE TITLE
question: `die_unless_type` guard in `die_unless_type_issubclassable` and position sensitivity.

### ISSUE THREAD

**Issue by tlambert03** [beartype/beartype#143]
In #136 I was beginning to add a `die_unless_type_issubclassable(self._origin)` safety measure, since we use `issubclass()` liberally in there, and I ran into a question:

Many of the `collections.abc` types work fine as the second parameter to `issubclass`

```python
from typing import Sequence
assert issubclass(list, Sequence)  # no prob
```

but of course, it doesn't work the other way around: 
```python
In [2]: assert issubclass(Sequence, list)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 assert issubclass(Sequence, list)

TypeError: issubclass() arg 1 must be a class
```

presumably, this is why you have the `die_unless_type` guard in the `die_unless_type_issubclassable` function.
```python
die_unless_type_issubclassable(typing.Sequence)
```
```pytb
BeartypeDecorHintPep3119Exception: typing.Sequence not class.
```

So, is there a function in beartype that lets me check if an object can safely be used specifically as the first, second, or both parameters in `issubclass`?

**Comment by tlambert03** [comment]
actually... maybe never mind?  I realized that the case I specifically ran into was when `typing.Sequence` was used the origin of `typing.Annotated[]` ... so, it's a bit of an edge case that's easily dealt with there.  But, I still have the general question :)

**Comment by leycec** [comment]
**Excellent questionnaire.** On this most glorious of post-patriotic summer days, I bring a basketful of answers. :basket: 

All that you seek and more currently resides in [our secretive, subversive, and sly `beartype._util.cls.pep.utilpep3119` submodule](https://github.com/beartype/beartype/blob/main/beartype/_util/cls/pep/utilpep3119.py). As the name suggests, that submodule implements support for the [`__instancecheck__()` and `__subclasscheck__()` metaclass dunder methods standardized by PEP 3119](https://peps.python.org/pep-3119/#overloading-isinstance-and-issubclass).

B-b-but first...

## Stop, Disambiguate and Listen

*@leycec's back with the brand new invention!* <sup>...awkward moment</sup>

Let's disambiguate a few critical things. Above, you suggest that "Many of the `collections.abc` types work fine as the second parameter to `issubclass`." This is absolutely true. However, you then import from `typing` instead:

```python
from typing import Sequence
```

**Uhohs.** `collections.abc` types are, indeed, types. `typing` type hint factories are *not* types; they just (kinda uselessly) masquerade as types when you pass them to the `isinstance()` or `issubclass()` builtins. `collections.abc` types and `typing` type hint factories are dissimilar things that hate each other despite sharing similar names:

```python
>>> from collections.abc import Sequence as SequenceABC
>>> isinstance(SequenceABC, type)
True  # <-- Good, good. We have a type, gentlemen.
>>> from typing import Sequence
>>> isinstance(Sequence, type)
False  # <-- ...oh. Oh, Gods. We in bed with cray-cray.
```

This is one of many reasons why *most* of the `typing` type hint factories have been deprecated in favour of their `collections.abc` counterparts. The latter make more sense and are generally more widely applicable and useful; the former are creaky and scary and it's time to take them out behind the wood pile.

## @leycec's Metaphors Are What's Scary, Yo

That may well be, but we fearlessly continue. You go on to wisely ask: "So, is there a function in `beartype` that lets me check if an object can safely be used specifically as the first, second, or both parameters in `issubclass`?"

**Ha, ha!** Yes. In fact, such wondrous things exist to serve us:

#1. To check if an object can safely be used specifically as the **first** parameter to `issubclass`, simply test whether that object is a type using the standard Python idiom for detecting types: `isinstance({object}, type)`. That works, because all classes in Python are actually instances of the `type` superclass. Neat-o! See above for voluminous examples that edify even as they instruct.
#2. To check if an object can safely be used specifically as the **second** parameter to `issubclass`, call our homegrown `beartype._util.cls.pep.utilpep3119.is_type_issubclassable()` tester ala:

```python
>>> from beartype._util.cls.pep.utilpep3119 import is_type_issubclassable
>>> from collections.abc import Sequence as SequenceABC
>>> is_type_issubclassable(SequenceABC)
True  # <-- Good, good. We have an issubclassable type, bois.
>>> from typing import Sequence
>>> is_type_issubclassable(Sequence)
False  # <-- It's time we had a talk, "typing" module.
```

Does that address your delightful curiosity? If not, I shall monologue at even greater and more tiresome length until GitHub itself silences me with a `--quiet` flag.

**Comment by leycec** [comment]
...maybe resolved? I am nodding firmly to myself while day-dreaming about being a top-gun maverick fighter pilot with immaculate hawk-like 20/20 vision. It's for the best that never happened. I admit that to myself now.

Let's close this before I embarrass the @beartype organization any further. :cloud:  :airplane:
