### ISSUE TITLE
PEP 585 "callable" not supported?

### ISSUE THREAD

**Issue by MaxSchoenau** [beartype/beartype#144]
Hi everyone,

because beartype told me so in a BeartypeDecorHintPep585DeprecationWarning, I changed my type hint from typing.Callable to the generic "callable". However, this now returns the following error: 

BeartypeDecorHintNonpepException: @beartyped Model.__init__() parameter "_Y" type hint <built-in function callable> either PEP-noncompliant or currently unsupported by @beartype.

Is the generic type hint unsupported at the moment, or did I do something wrong?

Edit: This problem got solved by using the beartype.typing module, however I would rather prefer being able to use the PEP 585 syntax.

**Comment by leycec** [comment]
Hi, Max! Everybody say "Hi, Max!", please. :teacher: 

**Okay.** So, let's see if we can't get you sorted here...

> I changed my type hint from `typing.Callable` to the generic `callable`.

**Ah-ha.** There's your problem. Python is confusing. We can all admit that. I do to my wife every evening. Sadly, she just rolls her eyes and tells me to get back to work.

What's happening here is that the `callable()` builtin is actually a *function* rather than a *type* in Python. `callable()` returns `True` if and only if the passed object is **callable** (i.e., can be called like a function or method, which obviously includes functions and methods but also classes defining the `__call__()` dunder method):

```python
$ python3
>>> type(callable)
<class 'builtin_function_or_method'>
>>> callable(callable)
True
>>> callable("I swear this string is callable. You gotta believe me!")
False
```

Clearly, `callable()` is *not* a valid type hint. Right? That's what @beartype is awkwardly complaining about there.

Instead, you want [the `collections.abc.Callable` abstract base class (ABC)](https://docs.python.org/3/library/collections.abc.html#collections.abc.Callable). If you don't care about backward compatibility with Python 3.7 or 3.8, <sup>*...you probably don't*</sup> @beartype will happily accept `collections.abc.Callable[...]` type hints under Python ≥ 3.9:

```python
$ python3.9
>>> from beartype import beartype
>>> from collections.abc import Callable
>>> def init(_Y: Callable[[], bool]) -> bool:
...        return _Y()
>>> init(bool)
False
```

Or you can simply pass `collections.abc.Callable` unsubscripted if your `Model.init()` method can permissively accept *any* possible callable. In that case, `collections.abc.Callable` is semantic shorthand for the more explicit `collections.abc.Callable[..., typing.Any]` type hint. Additionally, you can do this under *any* Python version – including Python 3.7 and 3.8:

```python
$ python3.8
>>> from beartype import beartype
>>> from collections.abc import Callable
>>> def init(_Y: Callable) -> bool:
...        return _Y()
>>> init(bool)
False
```

Does that answer your question?

## One Last Thing I Gotta Say

Oh – and please note that @beartype doesn't yet support deep type-checking of `Callable[...]` type hints. We *do* shallowly type-check that the passed or returned object is actually callable... but that's it for the moment. With any luck (*and ample funding, please Money Gods ample funding*), we'll support deep type-checking of `Callable[...]` type hints by the end of the year.

Thanks for your profound interest in @beartype. May the QA be with you always.

**Comment by MaxSchoenau** [comment]
Ah, I misread the PEP 585 wrongly and thought that collections.abc.Callable is deprecated as well as typing.Callable when it was just the latter. Thank you very much for your detailed help and explanation, and thank you even more for beartype.

**Comment by leycec** [comment]
Oh, you're most welcome. And thanks so much for the kind words! @beartype is here for the community; so, just let us know if you hit any further snags. :smiley_cat:
