### ISSUE TITLE
[Bug] @beartype causes failures with `unittest.TestCase.assertWarns`

### ISSUE THREAD

**Issue by jdogburck** [beartype/beartype#156]
Just adding `import beartype`, not using, beartype causes an error, when using assertWarns tests in python 3.7.7 on Windows 10.   Remove the `import beartype` and the error doesn't occur.

This doesn't occur with python 3.8.10 or 3.10.5.

Given the following code:

```
import beartype
import unittest
import warnings

def func() -> None:
    warnings.warn("Nothing to see here...")

class TestFunc(unittest.TestCase):

    def test_func(self) -> None:
        self.assertWarns(Warning, func)

if __name__ == '__main__':
    unittest.main()
```

And a fresh environment created with:

```
python -m venv .venv
.venv\scripts\activate.bat
pip install beartype
```

Running it with `python test.py` gives the following:

```
C:\Users\burckjm1\test>python test.py
.E
======================================================================
ERROR: test_func (__main__.TestFunc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 11, in test_func
    self.assertWarns(Warning, func)
  File "c:\Users\...\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 790, 
in assertWarns
    return context.handle('assertWarns', args, kwargs)
  File "c:\Users\...\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 177, 
in handle
    with self:
  File "c:\Users\...\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 230, 
in __enter__
    for v in sys.modules.values():
RuntimeError: dictionary changed size during iteration

----------------------------------------------------------------------
Ran 2 tests in 0.002s

FAILED (errors=1)
```

**Comment by leycec** [comment]
:scream: 

**Wow.** That's wild, weird, and wacky. Also, horrifying, horrible, and hideous. I must confess that neither I nor anyone else have ever seen that – despite leveraging @beartype across a panoply of open-source and propriety test-obsessed projects.

Yet, something bad is happening. So this is what it feels like to be ignorant.

Let's put on the detective cap and investigate the shadowy depths below crawling with slithering serpentine shapes hissing menacingly in my general direction.

![oh gods](https://c.tenor.com/vxH_D5G6UngAAAAM/stuck-indiana-jones.gif)

**Comment by leycec** [comment]
**Ah-ha!** This is actually an [upstream CPython issue resolved over two years ago](https://bugs.python.org/issue29620). Sadly, because CPython is to blame, we can't reasonably resolve this on our end. Thankfully, because CPython is to blame, the solution is just to upgrade Python 3.7 on your end. Does that sound reasonable?

Python 3.7.7 is sufficiently obsolete that it's a security risk. So, you *probably* want to upgrade to the newest stable release of Python 3.7 anyway. I believe that's **[Python 3.7.13](https://www.python.org/downloads/release/python-3713),** released just several months ago.

Thanks so much for the heads-up and all the exciting interest, @jdogburck. I almost had a heatstroke-induced heart attack there. :sweat_smile:

**Comment by jdogburck** [comment]
thank you for expeditiously exposing the error even if you couldn't evict it.   unfortunately - we do need to support python 3.7 although I'm sure we can recommend 3.7.8 forward if not 3.7.13.
