### ISSUE TITLE
Is `beartype.door` still O(1)?

### ISSUE THREAD

**Issue by langfield** [beartype/beartype#163]
This [commit](3cd8cb4b2ced8d5d3e40708c0bcda8b0c79eeea7) is extremely exciting. I really like the typechecking ideas in [`awfutils`](https://github.com/awf/awfutils), and this is something I've been hoping to see in @beartype for a long time. However, I worry about the overhead involved in inserting tons of `assert()` calls within the bodies of potentially every function in a codebase. I sometimes write code where almost half the statements in a function are annotated with an inline hint. In a 7-figure line count codebase, won't we run into significant performance overhead, even if the typechecking itself is O(1) in the data?

Can anyone think of any easy way to benchmark this?

**Comment by leycec** [comment]
**Hah, hah, hah!** "Hot Profiling" is my middle name, which is probably why I got bullied at school and then had my ultimate revenge by writing fast code. `Universe:` 0. `@leycec:` 1.

Firstly, rejoice, typing brethren! @beartype is *not* going to subject your existing `@beartype`-decorated callables to sudden static type-checking without your knowledge or consent. Preserving the performance of your world-shattering app is even more important to us than it is to you and that one perennially disgruntled boss with a unibrow.

Secondly, rejoice even harder, typing brethren! `beartype 0.12.0` (so, our next *next* stable release) is going to introduce the new `beartype.claw` API. This API provides import hooks <sup>...get it, *claw*? :laughing: :face_with_head_bandage:</sup> that automagically do various ~~abusive~~ useful things to your **entire friggin' codebase,** like:

* Implicitly decorate *all* classes and callables everywhere by `@beartype`, so that you no longer need to do that.
* Implicitly type-check *all* [PEP 526-annotated assignments](https://peps.python.org/pep-0526/) (e.g., `muh_var : list[str] = ['kek', 'lol']`) via the statement-level `beartype.door.die_if_unbearable()` runtime type-checker. In other words:

```python
# Import hooks in the "beartype.claw" submodule will dynamically augment this dumb code...
def muh_rockin_func() -> None:
    muh_rockin_local: list[int] = [0xFEEDFACE, 0xCAFEBABE]

# ...into this phenomenal code!
from beartype import beartype
from beartype.door import die_if_unbearable

@beartype
def muh_rockin_func() -> None:
    muh_rockin_local: list[int] = [0xFEEDFACE, 0xCAFEBABE]
    die_if_unbearable(muh_rockin_local, list[int])
```

Clearly, you're already paying the cost of `@beartype` decoration. So, that's not a pressing concern. Your pressing concern are the `die_if_unbearable()` calls that @beartype will be megalomaniacally injecting everywhere while twirling its bear-stache, right?

## For the Low Price of Nothing, @beartype Solves Everything

Our upcoming `beartype 0.11.0` release significantly optimizes the `is_bearable()` callable, which now enjoys the same `O(1)` "constant time with negligible constants" performance that `@beartype`-decorated callables enjoy. The `die_if_unbearable()` callable has yet to be obsessively optimized – but it's still probably wickedly fast.

Are you familiar with the [built-in `%time` magic command in the IPython REPL and Jupyter Notebook](https://ipython.readthedocs.io/en/stable/interactive/magics.html)? Basically, that's the easiest way *by far* to trivially profile Python statements. Let's do just that:

```python
>>> from beartype.door import is_bearable
>>> from beartype.typing import List, Tuple
>>> import numpy as np
>>> data = [(np.array(i), np.array(i+1)) for i in range(1000000)]
>>> %time is_bearable(data, List[Tuple[np.ndarray, np.ndarray]])
   CPU times: user 996 µs, sys: 0 ns, total: 996 µs
   Wall time: 1 ms
True
>>> %time is_bearable(data, List[Tuple[np.ndarray, np.ndarray]])
   CPU times: user 31 µs, sys: 2 µs, total: 33 µs
   Wall time: 36.7 µs
True
```

You should now be thinking: "Either your system's under sporadic load or something icky just happened there." Yup! Something icky just happened there:

1. The first time you call `is_bearable()` with a given type hint, `is_bearable()` dynamically synthesizes a new statement-level runtime type-checker behind your back efficiently type-checking arbitrary objects against that exact type hint. Unsurprisingly, this synthesis takes time. In the above example, exactly 965 µs or approximately **1 ms** of wall-clock time.
2. Every time thereafter that you call `is_bearable()` with the same type hint, `is_bearable()` reuses the same statement-level runtime type-checker that the first call synthesized behind your back. Unsurprisingly, this reuse takes no time whatsoever. This is what enables us to confidently mutter: "Negligible constants, bro. Negligible constants."

`is_bearable()` thus exhibits **amortized** worst-case "constant time with negligible constants" performance across all calls to `is_bearable()` passed the same type hint. Although `is_bearable()` costs transiently spike when passed a new type hint, those costs should *basically* be drowned out over the lifetime of your app.

## You Conveniently Ignored die_if_unbearable()

**Got me.** I'm pretty sure (but technically uncertain) that `die_if_unbearable()` exhibits similar efficiency gains. If it doesn't, we'll optimize it even harder *or* just inject code that first calls `is_bearable()` and only then calls `die_if_unbearable()` as needed: e.g.,

```python
from beartype import beartype
from beartype.door import die_if_unbearable, is_bearable

@beartype
def muh_rockin_func() -> None:
    muh_rockin_local: list[int] = [0xFEEDFACE, 0xCAFEBABE]
    if not is_bearable(muh_rockin_local, list[int]): die_if_unbearable(muh_rockin_local, list[int])
```

But... *yeah.* That's all kinda implementation details. Stuff should just work and just work so blindingly fast that nobody even thinks to question the unfathomable profundity of the type-checking bear.

Oh, and benchmarking this will ultimately be trivial. Rejoice for yet a third time! Specifically, `beartype 0.12.0` will publish the `beartype.claw.beartype_package()` import hook that you'll inject at the head of your `{muh_root_package}.__init__` submodule like so:

```python
# In "{muh_root_package}.__init__":
from beartype.claw import beartype_package
beartype_package()  # <-- that's it. you just @beartyped the world. congrats.
```

So, profiling this magic basically reduces to:

* **Profile your app in your favourite way** (e.g., [tuna](https://github.com/nschloe/tuna), [`pytest-profiling`](https://pypi.org/project/pytest-profiling/)).
* **Comment out the above call** to `beartype_package()`.
* **Profile your app again.**
* ...
* **Angrily harvest beavers from the wilderness and then throw said beavers at @leycec.**

**Comment by langfield** [comment]
I fear we are talking about different things. Worry not, I have no misgivings
about your ability to make/keep the individual `is_bearable()`-like callables
O(1). You are clearly a wizard at this.

Maybe an example will make things more clear. Suppose we have a function like
the one below.

```python
AngryType = Tuple[int, Tuple[int, Tuple[int, Tuple[int, Tuple[int, Tuple[int, Tuple[int]]]]]]]
@slothbeartype
def frequent(a: int) -> int:
    b: AngryType = transform(a)
    c: AngryType = transform1(b)
    d: AngryType = transform2(c)
    e: AngryType = transform3(d)
    f: AngryType = transform4(e)
    g: AngryType = transform5(f)
    h: AngryType = transform6(g)
    i: AngryType = transform7(h)
    j: AngryType = transform8(i)
    k: AngryType = transform9(j)
    l: AngryType = transform10(k)
    m: AngryType = transform11(l)
    return m
```

So a few things need explaining here. The ``@slothbeartype`` just indicates
that, somehow (I don't know if there will eventually be a decorator argument
for this or something, but we could just as easily use the import hooks you
mentioned), we have enabled the statement-level typechecking via
``beartype.door``. As an aside, it would be nice to be able to do this locally,
i.e. just for selected functions.

The ``AngryType`` definition is just a stand-in for a hint that takes @beartype
a comparatively long time to check (although of course, it will always be
O(1)).

So at import-time, the code, which has 526 annotations as you can see, is
transformed into a similar block with a bunch of ``die_if_unbearable()`` calls,
which can be thought of as basically wrappers around a bunch of asserts.

Each of these runs in O(1) amortized time, but that's each call. Even if the
cost of generating the checker for our hint is eventually balanced out, the
cost of all the calls, together (one for each annotated line), is definitely
not O(1) in the number of lines * the number of calls, right? Or am I seriously
misunderstanding something?

Imagine `frequent()` is a function buried deep in the dependency tree of a
complex application. It's called hundreds of times a second in some GUI app.
It's reasonable to say our checking without `beartype.door` is O(1) globally,
since parameter lists are bounded by the sanity of the programmer (very few
people are out here averaging `>10` parameters per function). But now that
we're potentially doing computation on each line, I don't know if this is
reasonable. Large codebase with high density of 526 hints => nontrivial
slowdown due to @beartype. But of course, I would be happy to be told how I
have misunderstood this.

**Comment by leycec** [comment]
**Ah-ha!** Yes, the confusion is all mine. Let us now explicate while waving hands.

## @slothbeartype: "We Banish Thee to /dev/null!"

The shambolic abominition known only as `@slothbeartype` will (...*probably*) only remain a proverbial legend depicted in cave art as a fat stick animal that gently rolls over its unlucky prey under the cover of darkness. @beartype will (...*probably*) never provide a decorator like that. PEP 526 support will (...*probably*) never happen at decorator time. The existing `@beartype` decorator is already too slow, frankly; there are justifiable reasons for that, <sup>*waves hands while muttering incoherently*</sup> but let's not compound matters here.

PEP 526 support will only happen at import hook time through public functions exported by the `beartype.claw` subpackage (e.g., `beartype_package()`), which third-party `{muh_package}.__init__` submodules then explicitly call. This is reasonable, because import hooks already necessarily perform abstract syntax tree (AST) transformations by definition. Performing yet another AST transformation at import hook time to support PEP 526 costs nothing.

Praise be to the red-tipped claw. :feet: 

Sadly, this means that...

> As an aside, it would be nice to be able to do this locally, i.e. just for selected functions.

**Yeah.** I... kinda don't know how to do that. Import hooks **+** AST transformations are dark voodoo weighed down by inscrutable APIs not necessarily amenable to deep configuration.

You're right, though. Import hooks like `beartype_package()` should eventually support some sort of whitelist or blacklist functionality. I wonder if a `pytest`-style marking API might be the most reasonably flexible approach? Like, by default, our import hooks unconditionally subject *everything* to PEP 526-compliant runtime type-checking – but specific classes and callables can conditionally opt out of that with some sort of @beartype-specific blacklist decorator: e.g.,

```python
from beartype.claw import beartype_no_pep526

# Prevent @beartype import hooks from subjecting
# this function to PEP 526 runtime type-checking.
@beartype_no_pep526
def frequent(a: int) -> int:
    # @beartype will now ignore this assignment. \o/
    b: AngryType = transform(a)
    return b
```

Right? Pretty sure we can support that swag. During recursive AST visitation, we just detect a callable AST node decorated by the `@beartype.claw.beartype_no_pep526` decorator and then bottom out (i.e., gracefully unwind) the current recursive call chain at that node.

Let's pretend I know what I'm talking about.

> The AngryType definition is just a stand-in for a hint that takes https://github.com/beartype a comparatively long time to check (although of course, it will always be O(1)).

"What you say!?!?" <sup>← to be read in badly dubbed Chinese King Fu master voice</sup>

That's sort of a paradoxical contradiction you got there. If a type hint takes a comparatively long time to check, it's (...*probably*) not `O(1)`. Examples include instances of classes whose metaclasses override the `__instancecheck__()` dunder method to do heinous things that scald the eyes with poisonous vapours, like perform database queries against remote servers or even just iterate over arbitrarily large containers in local memory. That's clearly PEBKAC. @beartype conveniently turns a blind eye to those sorts of shenanigans.

Even the most wickedly complex type hint – say, a union of multiple containers types themselves nesting unions of multiple container types several levels deep – should still be type-checkable in sub-microsecond time. So, less than one-millionth of a second.

Python is shockingly fast if you confine yourself to the proper subset of Python I am now coining Bearython. @beartype generates code exclusively in Bearython. Because almost everything in Python is slow beyond reason, the only thing Bearython permits is `if` conditionals and `isinstance()` calls. You'd be surprised how far that gets @beartype.

> Even if the cost of generating the checker for our hint is eventually balanced out, the cost of all the calls, together (one for each annotated line), is definitely not O(1) in the number of lines * the number of calls, right?

**Right.** The time complexity of PEP 526 compliance over the lifetime of a Python process could be considered `O(k)` time for `k` the total number of annotated assignments repeatedly type-checked by @beartype. Each `k` incurs a real-world wall-clock cost of at most 1μs, assuming *no* crimes against humanity like `__isinstancecheck__()` . For all `k < 1,000,000`, the total real-world wall-clock costs should still be less than a second over the entire lifetime of the current process and thus imperceptible to glorious fleshy meat suits such as ourselves.

Note that I am now furiously waving my hands.

**Comment by langfield** [comment]
> **Right.** The time complexity of PEP 526 compliance over the lifetime of a Python process could be considered `O(k)` time for `k` the total number of annotated assignments repeatedly type-checked by @beartype. Each `k` incurs a real-world wall-clock cost of at most 1μs, assuming _no_ crimes against humanity like `__isinstancecheck__()` . For all `k < 1,000,000`, the total real-world wall-clock costs should still be less than a second over the entire lifetime of the current process and thus imperceptible to glorious fleshy meat suits such as ourselves.

Well, you've got me there! Sounds like it's a non-issue, despite being `O(k)` in the number of annotations. As for the import hooks. Well, all I have to say is that when you're taking an extreme measure (and I think doing all of this _is_ an extreme measure), it seems polite to make the toggles opt-in instead of opt-out. I suppose the whole thing is of course opt-in. One of the things I like about the existing decorator is that it is very explicit. Import hooks scare me because I think I might forget that I'm using them, and leave them on when for some reason or another they shouldn't be.

Anyhow, I think the concern has been addressed. Feel free to close!

**Comment by leycec** [comment]
> Import hooks scare me because I think I might forget that I'm using them, and leave them on when for some reason or another they shouldn't be.

**Right?** Import hooks fundamentally violate Python's "Explicit is better than implicit!" maxim, which is perhaps not so good. My cynical suspicion, however, is that most users simply don't care about purist ideology the way we do. As typing zealots, we're mostly fine with all of the manual legwork that @beartype currently mandates. This is a useful tradeoff for people like us, because we retain full and total control over runtime type-checking over all time and space. In return, all @beartype demands is our scarce minutes, precious lifeblood, and eternal souls.

But most users aren't like us. Most users don't have the resources or inclination to manually manage boilerplate churn like that. Decorating *every* class and callable across a million-line codebase with `@beartype.beartype` is a hard blocker – and I feel that real-world pain. It's understandable.

Import hooks fill that adoption gap by eliminating the current prohibitive cost of @beartype's buy-in. Gah! Tech jargon, thy name is this thread.

Thanks so much for all the ongoing excitement, @langfield. If you'd like to see whitelisting or blacklisting features like the above `@beartype_no_pep526`, it'd be great if you could open up a new issue. Remind us all of my hollow promises to do something. :smile:
