### ISSUE TITLE
False Positive of Beartype

### ISSUE THREAD

**Issue by MaxSchoenau** [beartype/beartype#165]
Hello together,

I want to share a bizarre bug with you that I don't understand.

Unfortunately, I do not have the time at the moment to give a useful "minimal failing product"; however, I wanted to show you the error message that I got. Maybe some of you know what could have happened here.

The error message is:
`*** beartype.roar.BeartypeCallHintParamViolation: @beartyped conductance_peaks() parameter params="ExtremumParameters(res=1000, m_relative=90, rel_distance=20, rel_width=1)" violates type hint <class 'tas.tas.ExtremumParameters'>, as "ExtremumParameters(res=1000, m_relative=90, rel_distance=20, rel_width=1)" not instance of <protocol "tas.tas.ExtremumParameters">.`

So it complains about an input that it definitely should not complain about, and I can't find any problem when inspecting the "problematic" input with my debugger. Funny enough, this message does not always appear, making it even more annoying...
It disappears after resetting the console. 

If some of you know what happened here, I would be very glad to hear the solution :)

If one does need much more information for this bug, then I will try to reduce my code until I can show it here when I have the time for it :)

**Comment by leycec** [comment]
**Gah!** A fearsome issue rears like an enraged dragon threatening to smite the hapless @beartype. Sadly, there isn't *quite* enough here for us to go on. Happily, @beartype only raises false positives when type-checking containers (e.g., `list[list[str]]`) – and even that's fairly rare and innocuous.

The `tas.tas.ExtremumParameters` class doesn't strike me as a container. Given the brief `repr()` string of `ExtremumParameters(res=1000, m_relative=90, rel_distance=20, rel_width=1)` that you've helpfully included, that class looks more like a standard dataclass. @beartype *probably* isn't wrong here; there *probably* is something non-deterministically wrong inside either `tas` or your codebase.

Naturally, a minimal length example (MLE) would do wonders for debugging here. :sweat_smile: 

## Diving into the Deep End with @beartype

But I suspect that updating to the most recent live GitHub-hosted version of @beartype would do even more wonders. Why? Because recent improvements in the @beartype codebase have significantly improved the readability of type-checking violation exception messages. If nothing else, updating will get you fully ANSII-colourized output. Are you feeling brave? If so, how brave? We promise that we exhaustively test. Indeed, tests are currently passing and cover 97% or so of the @beartype codebase.

If you manage @beartype with `pip`, this one-liner will update @beartype to our most recent live GitHub-hosted commit:

```bash
python3 -m pip install git+https://github.com/beartype/beartype.git@db2b98e27d9a6c99dfdeafc3ffb5d89c8fc9544f
```

Let us know if that improves debuggability for you. And thanks again, Max!

**Comment by leycec** [comment]
@MaxSchoenau: with grave apologies, I'd selfishly like to close this. I know! I know. We weren't really able to assist you in debugging this and something is still almost certainly wrong on your end. But...

We're on the cusp of pushing out `beartype 0.11.0`. This issue kinda makes us look bad. If you *do* find the time to produce a minimal-length example (MLE) that replicates this issue for us, that would be fantastic. Please reopen this issue at that time *or* open up another issue entirely.

Until then, please accept my profuse regret at being unable to help you resolve this. And thanks so much for your enthusiastic interest in @beartype. You're awesome. Smiley cat approves. :smile_cat:

**Comment by MaxSchoenau** [comment]
Hi, no problem. I don't mind you closing it. I don't want this to be labeled as a bug on your side, with me having given you so little information. Thank you very much for your help! I will update (and maybe reopen) this issue as soon as I can give you a better example of my problem.

**Comment by leycec** [comment]
**Superb!** I actually have a lot of fun crushing bugs. They make such delightful squealing noises as I pound them repeatedly with the sole of my last boot. :boot: :bug: 

I know how difficult it can be to isolate non-deterministic issues like this, too. May the `pdb` debugger be with you on your perilous journey.
