### ISSUE TITLE
Research code coverage integration

### ISSUE THREAD

**Issue by Heliotrop3** [beartype/beartype#20]
Taken from beartype\\.github\worflows\pythonpackage.yml

>FIXME: Uncomment after properly researching code coverage integration. On doing so, add "coverage[toml]" to the set of Python >packages installed with "pip" below.
>```    
>env:
>      USING_COVERAGE: '3.6,3.8'
>```

### Links
[Original link](https://hynek.me/articles/python-github-actions) of inspiration for beartype's current setup.
[(Github Docs) Building and testing Python](https://docs.github.com/en/actions/guides/building-and-testing-python)
[How to Configure Github Actions the Easy Way](https://towardsdatascience.com/setting-up-python-environment-using-github-actions-9a81936be5c9)
[Github Actions for perfect Python CI](https://sourcery.ai/blog/github-actions/)

**Comment by leycec** [comment]
**I am nodding appreciatively.** I swear, I always wanted to get those sweet coverage metrics going! I just never found the auspicious spare moment *not* filled with squalling Bengal and Maine Coon cats with which to do it. I'm sure this is easier than I'm dreading, because *everybody* wants coverage metrics. Don't they? I do.

Relatedly, [there's **coveralls.io**](https://pypi.org/project/coveralls). Maybe that's what we really want. Whatever's easiest is what we really want. Since I have no firm ideas here, let's let this percolate until someone else either delivers a firm idea or publicly berates me for shamelessly doing nothing... *yet again.* `</sigh>`

**Comment by leycec** [comment]
**Addendum:** we want **[codecov.io](https://about.codecov.io),** which has mostly supplanted [overalls.io](https://pypi.org/project/coveralls) throughout the open-source community thanks to:

* Hosting a more reliable CI service with minimal (ideally, no) downtime. That's kinda critical. Since coverage analytics are deeply integrated into CI pipelines, a failure in coverage service usually spells a failure in CI pipelines and thus pushes and PRs. Since those things are bad, codecov.io is good.
* Publishing pretty analytics as concentric circles. Show me the engineer who isn't for those things and I'll show you a platinum-coated dancing chicken in winged migration over the 79th moon of Jupiter. (It's [Sinope](https://en.wikipedia.org/wiki/Sinope_\(moon\)), by the way. You're welcome.)

Of course, codecov.io only handles the frontend publication of coverage statistics. We still need a Python-specific backend to generate those statistics in the first place. For that, we almost probably want to:

1. Install [the pytest-specific `pytest-cov` plugin](https://pypi.org/project/pytest-cov).
2. Run that plugin during CI pipelines by passing the `--cov` option to `pytest` in our `tox.ini` configuration: e.g.,

        {envpython} -m pytest --cov=beartype --maxfail=3 {posargs} {toxinidir}

Note that explicitly passing the name of this package (i.e., `beartype`) as the value of that option appears to be mandatory, which saddens us even as we accept harsh reality.

As a significant black mark in the eye of codecov.io, **it didn't actually work tonight.** Like, either the Content Delivery Network (CDN) hosting their JavaScript and CSS assets fundamentally fell off a land bridge in the Asiatic continent *or* my Firefox is on fire. I'm not ruling out the latter, but the former seems the likelier. *Curse your spiteful CDN, codecov.io!*

**Comment by felix-hilden** [comment]
Hey! Dropping in once more to say that at least for me `coverage` has been working well with `pytest` out of the box. It seems that `pytest-cov` has some benefits, but I'm not sure how you'd like to weigh the added dependency! But I'm sure it's a common dependency, and with dev dependencies I guess it doesn't matter that much.

Another thought: I have done the whole thing of requiring a certain coverage for the overall repository and all PRs. In hindsight it probably should not have been as strict of a requirement for me, but for this kind of library it might actually be appropriate. And it's pretty easy to set up.

**Comment by leycec** [comment]
**OMG!** We faceplanted straight into pytest-dev/pytest-cov#448 while resolving this, which is the ongoing CI horror show that loves to slather everyone in sticky febrile juices like [Shub-Niggurath](https://en.wikipedia.org/wiki/Shub-Niggurath) if Shub-Niggurath decided to drop the The Black Goat of the Woods with a Thousand Young gig and just become a GitHub QA specialist instead.

What I'm trying to say is that measuring coverage was utterly horrible and made me yet again regret reincarnating into this world. On the bright side, it's done. On the dark side, hacking around pytest-dev/pytest-cov#448 bled the last vestiges of my sanity. Arise, Shub-Niggurath and bless us with your dark concrescence!

![This issue in a nutshell.](https://upload.wikimedia.org/wikipedia/commons/8/8f/Shub-Niggurath.jpg)
