### ISSUE TITLE
[Bug] List item type would not be check sometimes by function decorator @beartype

### ISSUE THREAD

**Issue by yioda** [beartype/beartype#202]
I would expect that all calls with string type item would fail, but sometime it would be OK.

``` python
>>> from beartype import beartype
>>> @beartype
... def test(nums: list[int]) -> None:
...     print(f'nums:{nums}')
...
>>> test([1, 2])
nums:[1, 2]
>>> test([1, 'b'])
nums:[1, 'b']
>>> test([1, 'b'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<@beartype(__main__.test) at 0x7fed749b0d30>", line 32, in test
beartype.roar.BeartypeCallHintParamViolation: @beartyped __main__.test() parameter nums=[1, 'b'] violates type hint list[int], as list index 1 item str 'b' not instance of int.
>>> test([1, 'b'])
nums:[1, 'b']
```

version:
``` shell
$ pip show beartype
Name: beartype
Version: 0.11.0
Summary: Unbearably fast runtime type checking in pure Python.
Home-page: https://github.com/beartype/beartype
Author: Cecil Curry, et al.
Author-email: leycec@gmail.com
License: MIT
Location: /home/xxxxxx/.pyenv/versions/3.10.1/lib/python3.10/site-packages
Requires:
Required-by:
```

**Comment by leycec** [comment]
**Heh.** Surprisingly, @beartype is working exactly as intended here. You are now thinking to yourself: "@beartype, you are dumb and I will never use you."

Let us explicate. @beartype guarantees constant-time (i.e., `O(1)`) runtime behaviour. In fact, @beartype *basically* guarantees that each call to a @beartype-decorated callable (like the `test()` function in your example) takes **no more than 10µs** (10 microseconds = 10<sup>-6</sup> seconds). That's *basically* instantaneous. Moreover, that's the entire reason for @beartype's existence: it's so fast than you never want to disable it.

But there's a price for speed. How *does* @beartype type-check an arbitrarily large list in constant-time? It doesn't, because that's impossible. Instead, @beartype type-checks only **random items** of parameters passed to and returns returned from @beartype-decorated callables.

Usually, this is fine. Most lists, for example, are homogeneously constructed with a list comprehension or generator effectively guaranteeing uniform types for all items of that list (e.g., `test(range(-5, 50, 3))`).

Sometimes, this is *not* fine. For those times, a future version of @beartype will add support for the more traditional linear-time (i.e., `O(n)`) type-checking that you are expecting. Until then, @beartype supports ["full-fat" `O(n)` type-checking via @beartype validators](https://github.com/beartype/beartype#full-fat-o-n-matching):

```python
# Import the requisite machinery.
from beartype import beartype
from beartype.vale import Is
from typing import Annotated   # <--------------- if Python ≥ 3.9.0
#from typing_extensions import Annotated   # <--- if Python < 3.9.0

# Type hint matching all integers in a list of integers in O(n) time. Please
# never do this. You now want to, don't you? Why? You know the price! Why?!?
IntList = Annotated[list[int], Is[lambda lst: all(
    isinstance(item, int) for item in lst)]]

# Type-check all integers in a list of integers in O(n) time. How could you?
@beartype
def sum_intlist(my_list: IntList) -> int:
    '''
    The slowest possible integer summation over the passed list of integers.

    There goes your whole data science pipeline. Yikes! So much cringe.
    '''

    return sum(my_list)  # oh, gods what have you done
```

See also this [open issue currently tracking `O(n)` support](https://github.com/beartype/beartype/issues/60). And thanks so much for your interest in @beartype! May 2023 be a year of profound prosperity and joy for you and yours. :tada:

**Comment by yioda** [comment]
Thanks @leycec for explaining! I'm looking forward to `O(n)` support!

**Comment by leycec** [comment]
Oh, you're most welcome. 2023 promises to be the Year of the Beartype – complete with `O(n)` support *and* a likely hybrid mode called `O(smarty pants)` that dynamically switches between `O(n)`, `O(log n)`, and `O(1)` type-checking depending on the size of the container to be type-checked.

Thanks again for being so accommodating and patient, @yioda. Much :smiling_face_with_three_hearts: !
