### ISSUE TITLE
[Feature Request] Generic `TypeVar` type-checking

### ISSUE THREAD

**Issue by iperov** [beartype/beartype#204]
```
from beartype import beartype
from typing import Generic, TypeVar

T = TypeVar('T')
class Bar(Generic[T]):
    
    @beartype
    def func(self, i : T):
        ...

a = Bar[int]()
a.func('f')
```
no exception

**Comment by leycec** [comment]
**Indeed.** You are correct, Sir. @beartype currently only enforces:

* Bounds and constraints on type variables passed at instantiation time (e.g., `T = TypeVar('T', bound=int)`).
* Concrete generics (e.g., `class Bar(List[int])`).

@beartype does *not* enforce abstract generics subscripted by concrete types across method calls of those generics, as in your example. Why? Because nobody (especially including me) knows how to do that at runtime. I'm *pretty* sure that no runtime type-checkers support this edge case. That said, it would be super-great if @beartype did support this edge case. Right? So, let's add this to the steaming pile of "Great stuff we should eventually do."

Until @beartype eventually supports this, I'm afraid the best you can do is constrain type variables with bounds and constraints at instantiation time: e.g.,

```python
from beartype import beartype
from typing import Generic, TypeVar

T = TypeVar('T', bound=int)
class Bar(Generic[T]):
    
    @beartype
    def func(self, i : T):
        ...

a = Bar[int]()
a.func('f')
```

The above raises the expected exception:

```
beartype.roar.BeartypeCallHintParamViolation: @beartyped __main__.Bar.func()
parameter i='f' violates type hint ~T, as str 'f' not instance of int.
```

Thanks so much for the excellent feature request, @iperov. May the power of @beartype be with you throughout 2023 and beyond. :flex:

**Comment by leycec** [comment]
**Fascinating...** and **horrifying!** The `tl;dr` is that Python fails to preserve this typing information at runtime – officially, anyway. That is to say, Python simply discards the `[int]` subscripting `Bar` and thus silently reduces `Bar[int]` to `Bar` at runtime: e.g.,

```python
# Python reduces this...
a = Bar[int]()

# ...to just this! *BARF*
a = Bar()
```

Since Python unhelpfully destroys everything @beartype (and other runtime type-checkers) need to recover `[int]` from `a`, @beartype's paws are probably tied.

## Hacks! Hacks Everywhere!

That said, unofficial hacks exist. To quote a [relevant StackOverflow answer on this topic](https://stackoverflow.com/a/60984681/2809027):

> **There is no supported API for this.** Under limited circumstances, if you're willing to mess around with undocumented implementation details, you can sometimes do it, but **it's not reliable at all.**
>
> First, mypy doesn't require you to provide type arguments when assigning to a generically-typed variable. You can do things like `x: Test[int] = Test()` and neither Python nor mypy will complain. mypy infers the type arguments, but `Test` is used at runtime instead of `Test[int]`. Since explicit type arguments are awkward to write and carry a performance penalty, lots of code only uses type arguments in the annotations, not at runtime.
>
> There's no way to recover type arguments at runtime that were never provided at runtime.
>
> When type arguments are provided at runtime, the implementation does currently try to preserve this information, but only in **a completely undocumented internal attribute that is subject to change without notice**, and **even this attribute might not be present**. Specifically, when you call
>
> `Test[int]()`
>
>, the class of the new object is `Test` rather than `Test[int]`, but the typing implementation attempts to set
>
> `obj.__orig_class__ = Test[int]`
>
> on the new object. If it cannot set `__orig_class__` (for example, if `Test` uses `__slots__`), then it catches the AttributeError and gives up.

Given the above, @beartype *can* actually attempt to do what you want – but only under limited circumstances. Namely:

* The generic *must* be instantiated with a concrete type as you are thankfully doing.
* The generic *must* not use `__slots__`, also as you are thankfully doing.

Our concern then becomes: this is non-trivial for us to implement, test, and document. Is this worth our while? If we do this, will anyone else actually going to use this by abiding by the above constraints – which are undocumented, fragile, and subject to change by CPython devs at any time?

Alternately, the above can be rephrased as: would someone who is *not* me be willing to submit a Python Enhancement Proposal (PEP) formalizing support for the `__orig_class__` dunder attribute? If that happens, @beartype is *much* more likely to support this edge case.

Intellectual food for QA thought as the Canadian winter grinds on. :snowflake:

**Comment by iperov** [comment]
> Because nobody especially me knows how to do that efficiently at runtime

https://github.com/Stewori/pytypes works fine with such generic and even nested generics. I don't know how efficiently, but works.

**Comment by leycec** [comment]
**Gah!** You shame me into doing something, @iperov. Technically, `pytypes` is dead. Pragmatically, that makes things even *worse.* @beartype is currently behaving worse than a dead project, guys.

**Very well.** I shall grumble loudly... but eventually do this. That said, this *probably* isn't my highest priority. I am lazy. We've gotta keep that in mind. More importantly, [deep type-checking core container types like sets and dictionaries](https://github.com/beartype/beartype/issues/204) (as well as [linear type-checking those same types in `O(n)` time when configured to do so by `BeartypeStrategy.On`](https://github.com/beartype/beartype/issues/204)) sadly takes priority.

But thanks for gently hounding me about this. I'd been meaning to look into whether or not this was actually feasible... and it is! Sorta. Barely. Close enough. `</wink>`

Let's see what gifts of pure joy 2023 brings. Please ping me if I fail to do this. :ping_pong:

**Comment by Gobot1234** [comment]
> Alternately, the above can be rephrased as: would someone who is not me be willing to submit a Python Enhancement Proposal (PEP) formalizing support for the __orig_class__ dunder attribute? If that happens, @beartype is much more likely to support this edge case.

Hi your friend neighbourhood passerby, `__orig_class__` should be considered stable once https://github.com/python/cpython/pull/101827 lands :). I am also interested in improving the introspection abilities further going forward but that won't be for a while, I'll try and let you know if that goes anywhere.

**Comment by leycec** [comment]
Thanks so much for that drive-by heads up, friendly neighbourhood passerby @Gobot1234. It reassures the heart on a warm Friday evening to see CPython officially embracing and stabilizing the `__orig_class__` API. That's wondrous! I caper with glee. :man_dancing: 

Let us temper our expectations, though. I am still lazy. This is still hard – even with official support for introspection of generic `TypeVar`s. Meanwhile, @beartype still lacks core type-checking for low-hanging fruit standardized decades ago by PEP 484. Generic `TypeVar`s are high-hanging fruit. @beartype should pick all of the low-hanging fruit first. It only makes sense. Right?

2027 is what I'm saying. 2027 is the year @beartype goes hard on generic `TypeVar`s.

**Comment by leycec** [comment]
@iperov: **Gah!** So sorry that we haven't been able to attend to this yet. We're currently [wading through the suspiciously brown smelly muck of import hooks](https://github.com/beartype/beartype/issues/43). My dark suspicion is that we *probably* won't start deeply type-checking `TypeVar` until later this year or even next year.

Until then, would you mind if we kept this open? This was (and still is) a great feature request. Mash those emoji if you believe in miracles, people. :joy_cat:

**Comment by iperov** [comment]
thanks but I no longer need this.

Type annotation and developer discipline is all you need.

**Comment by leycec** [comment]
Oh, I fully agree. Don't worry! Same page. Absolutely. I'll probably never use this myself and doubt many other @beartype users will either. Still, this *was* standardized by PEP 484 a literal lifetime ago. It'd be great if @beartype could eventually support this... **just 'cause.** We're here to support everything – even things that are kinda sketchy and questionable.

Would you object if I reopen this yet again? If so, no worries. I'll happily open up a new feature request detailing this rather than subjecting you to further comments from ~~Hell~~ the frozen ice wastes of Canada.  :cold_sweat: :cold_face: :snowflake:

**Comment by iperov** [comment]
Open new please

**Comment by leycec** [comment]
**Gotcha.** Your will be done. Thanks again for this excellent issue. :bow:
