### ISSUE TITLE
Tests fail: INTERNALERROR

### ISSUE THREAD

**Issue by yurivict** [beartype/beartype#207]
```
========================================================================================== test session starts ==========================================================================================
platform freebsd13 -- Python 3.9.16, pytest-7.2.0, pluggy-1.0.0 -- /usr/local/bin/python3.9
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/usr/ports/devel/py-beartype/work-py39/beartype-0.12.0/.hypothesis/examples')
Using --randomly-seed=2859320603
rootdir: /usr/ports/devel/py-beartype/work-py39/beartype-0.12.0, configfile: pytest.ini, testpaths: beartype_test
plugins: forked-1.4.0, hypothesis-6.58.0, cov-2.9.0, xdist-2.5.0, randomly-3.12.0, timeout-2.1.0, rerunfailures-10.1, flaky-3.7.0, env-0.6.2, freezegun-0.4.2, mock-1.10.4, subtests-0.9.0, nbval-0.10.0
collected 263 items                                                                                                                                                                                     
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 334, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 667, in perform_collect
INTERNALERROR>     hook.pytest_collection_modifyitems(
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pytest_freezegun.py", line 55, in pytest_collection_modifyitems
INTERNALERROR>     if get_closest_marker(item, MARKER_NAME):
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pytest_freezegun.py", line 17, in get_closest_marker
INTERNALERROR>     if LooseVersion(pytest.__version__) < LooseVersion('3.6.0'):
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/version.py", line 55, in __init__
INTERNALERROR>     warnings.warn(
INTERNALERROR> DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

========================================================================================= no tests ran in 3.11s =========================================================================================
*** Error code 3
```

Version: 0.12.0
python-3.9
FreeBSD 13.1

**Comment by leycec** [comment]
**Yikes.** `pytest` gore, ahoy! I... honestly have no idea what's going on there. [Tests pass on all supported platforms and Python versions both locally *and* remotely under GitHub Actions-hosted continuous integration (CI) pipelines](https://github.com/beartype/beartype/actions/runs/3937431746).

Tragically, neither I nor Microsoft can replicate this. The lack of any mention of @beartype in the above output is doubly concerning. It's likely that you've installed some combination of third-party `pytest` plugins that are hostile to existence under FreeBSD. In this case, I *strongly* suspect the [unmaintained `pytest-freezegun` plugin](https://pypi.org/project/pytest-freezegun) is your culprit:

```
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pytest_freezegun.py", line 55, in pytest_collection_modifyitems
INTERNALERROR>     if get_closest_marker(item, MARKER_NAME):
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pytest_freezegun.py", line 17, in get_closest_marker
INTERNALERROR>     if LooseVersion(pytest.__version__) < LooseVersion('3.6.0'):
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/version.py", line 55, in __init__
INTERNALERROR>     warnings.warn(
INTERNALERROR> DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
```

`pytest-freezegun` is leveraging the deprecated `LooseVersion` class from `distutils`. For safety, @beartype's `pytest` suite is configured to coerce deprecations (and, in fact, *any* non-fatal warnings) into fatal exceptions. This is what you're seeing.

From the little that I can tell, *any* attempt to run `pytest` against *any* Python project on your system should fail with similar non-human-readable output. The moral of this sad story is...

## Death Becomes Your `pytest` Installation

`pytest-freezegun` is dead. Avoid dead projects, because they're *dead*. You wouldn't prop the rotting corpse of Grammy Moses up on the second-hand wicker couch you inherited from her estate and then wonder why she's failing to offer you a five-year-old ginger-coated black licorice pellet like she used to, right? This is like that.

`pytest` plugins are notoriously fragile; the more you install, the more likely you are to suffer unexpected breakage when testing unrelated Python projects that don't even *use* those plugins. I recently hit this myself with the well-maintained `pytest-asyncio` plugin; @beartype doesn't use that plugin, but everybody else does, which means I can't uninstall it, which I *really* want to do. I then inevitably waste my time circumventing useless errors and warnings from that plugin when running unrelated @beartype tests. **Gah!**

For this reason, @beartype requires *no* `pytest` plugins. Ideally, @beartype tests should only be run under a virtual environment with the bare minimum of `pytest` plugins you know you absolutely require for other Python projects.

## 2023: The Year Everyone Uninstalls `pytest` Plugins

Lemme know if that locally resolves your `pytest` failures! If it doesn't, please reopen this issue and I'll happily resolve whatever breaks next. Until then, thanks for all the based FreeBSD-based enthusiasm about @beartype! :fist_raised: :bear: :fist_raised:

**Comment by yurivict** [comment]
> From the little that I can tell, any attempt to run pytest against any Python project on your system should fail with similar non-human-readable output. The moral of this sad story is...

In fact Pytest works fine on FreeBSD virtually all other projects, except beartype.

**Comment by leycec** [comment]
Bro, it's not @beartype! Okay. It's *probably* not @beartype. I will shave off my last remaining hair follicle if @beartype is to blame for this. Everything in that output suggests the unmaintained `pytest-freezegun` plugin is at fault – which makes sense. It's unmaintained. @beartype isn't even mentioned, really.

Would you mind temporarily uninstalling `pytest-freezegun` and then giving @beartype tests another go? Please. I'm on me arthritic knees begging you sorta thing. Just humour me, because it is late and we're both tired. :face_exhaling:

**Comment by yurivict** [comment]
You are probably right.
