### ISSUE TITLE
test FAILED beartype_test/a90_func/lib/sphinx/test_beartype_in_sphinx.py::test_beartype_in_sphinx

### ISSUE THREAD

**Issue by danigm** [beartype/beartype#209]
This test is failing with sphinx 6.1.3.

This is part of the traceback:
```
>       assert is_success(sphinx_build_exit_code), (
             f'"sphinx-build" exit code {sphinx_build_exit_code} != 0.')
E       AssertionError: "sphinx-build" exit code 2 != 0.
E       assert False
E        +  where False = <function is_success at 0x3ffa7453550>(2)
SPHINX_ARGUMENTS = ['/home/abuild/rpmbuild/BUILD/beartype-0.11.0/beartype_test/a90_func/data/lib/sphinx',
  '/tmp/pytest-of-abuild/pytest-0/test_beartype_in_sphinx0']
 SPHINX_OPTIONS = ['-E', '-b', 'html', '-W']

...

tmp_path   = PosixPath('/tmp/pytest-of-abuild/pytest-0/test_beartype_in_sphinx0')

beartype_test/a90_func/lib/sphinx/test_beartype_in_sphinx.py:100: AssertionError
----------------------------- Captured stdout call -----------------------------
Running Sphinx v6.1.3
----------------------------- Captured stderr call -----------------------------

Exception occurred:
  File "/usr/lib/python3.8/site-packages/sphinx/deprecation.py", line 46, in __getattr__
    warnings.warn(f"The alias '{self._modname}.{name}' is deprecated, "
sphinx.deprecation.RemovedInSphinx80Warning: The alias 'sphinx.util.SkipProgressMessage' is deprecated, use 'sphinx.util.display.SkipProgressMessage' instead. Check CHANGES for Sphinx API modifications.
The full traceback has been saved in /tmp/sphinx-err-4ir0jzf8.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
=========================== short test summary info ============================
SKIPPED [1] beartype_test/a00_unit/a60_api/typing/test_typingpep544.py:439: Python 3.8.16 < 3.9.0.
SKIPPED [1] beartype_test/a90_func/pep/test_pep561_static.py:149: Command "pyright" not found.
FAILED beartype_test/a90_func/lib/sphinx/test_beartype_in_sphinx.py::test_beartype_in_sphinx
============ 1 failed, 251 passed, 2 skipped, 3 deselected in 3.82s ============

```

**Comment by leycec** [comment]
**Gah!** Thanks for the swift catch, @danig. And might I say that Málaga looks especially stunning to a Canadian at this time of year. What a wonderful place to live! I can *almost* feel the warm sea breeze basking on my pale skin that hasn't seen the Sun in fifteen years. :sun_behind_rain_cloud: 

**So....** this is all Sphinx's fault. I'd recently disabled this test under our GitHub Actions-based continuous integration (CI) pipeline, where this test fails with the exact same exception. I still can't replicate this locally on my ancient Gentoo Linux devbox, but... who cares! I now despise this test with every frostbitten fibre of my being and just want it to go away. Since Sphinx is busted and making @beartype look bad, we'll just unconditionally skip this test *everywhere* until I find a spare minute to investigate this a bit deeper.

Thanks again for the heads up! May you cherish every precious moment in the Sun.

**Comment by leycec** [comment]
**Hah, hah!** Instead of warmth, sunshine, or worthwhile beaches, Canadians have enhanced work productivity due to *not* having any of those things. In other words, I resolved this. I mean, what *else* was I going to do? Go outside? That's akin to death! Seriously. Going outside kills in Canada. When even the Maine Coon cats covered in long-hair fur that gets everywhere refuse to go outside, you know you're basically living on the moon.

![basically the moon](https://media.tenor.com/Ki_i5rX7Q3AAAAAS/cat-snow.gif)

**Comment by danigm** [comment]
Thanks! That was a quick and nice fix.
