### ISSUE TITLE
Generalizing Github actions workflow to MacOS and Windows

### ISSUE THREAD

**Issue by Heliotrop3** [beartype/beartype#21]
Taken from beartype\\.github\worflows\pythonpackage.yml

>
> FIXME: As required, generalize to macOS and Windows by:
> - Uncommenting the following line here:
>   ```#runs-on: ${{ matrix.platform }}```
> - Uncommenting the "strategy/matrix/platform" line below.
> - Replacing the "envlist" setting in "tox.ini" with something resembling:
>    ```#envlist = py3{5,6,7,8}-{linux,macos,windows},pypy3-{linux,macos,windows}```

Related: See #20 for links related to configuring CI on Github.
See #22 for discussion around beartype's CI/CD as a whole

**Comment by leycec** [comment]
Come to think, this is actually a fairly high priority – well, the Windows part anyway. macOS testing would be great as well, of course – *except that we can't afford it.* Microsoft only allots public repos **2,000 GitHub Actions minutes per month** for an average of **66.66 minutes per day.** Weep, monotheists! The number of the Beast strikes again! `</ahem>`

Although our test suite is lightning fast, it's also run under four CPython and two PyPy versions. That should *still* be lightning fast, except that Azure (i.e., Microsoft's cloud platform that unsurprisingly also hosts GitHub Actions) is painfully slow. [Each CI run](https://github.com/beartype/beartype/actions) currently costs us **5 minutes.** Adding Windows testing at least (but probably more than) doubles that to **10 minutes** or more. We'd like to be able to perform multiple CI runs per day (e.g., to handle pull requests), so we're rapidly bumping up against real-world business constraints. *Curse the perfidious men in suits.*

**Comment by leycec** [comment]
**Ugh.** This is done! That's good. But Windows is slow! That's bad, because testing against Windows now consumes precious CI minutes possibly better spent elsewhere. That's currently fine, because we're currently under our CI minutes budget.

But if we ever exceed that budget, we'll sadly have to drop Windows CI support. Until then, test all the things against all the platforms, @beartype! Thanks yet again for all the bravado, Tyler. This issue resolution's for you. Please, have this complimentary gluten-free organic moon cake. :moon_cake:

**Comment by harens** [comment]
Hello again, It's Haren from https://github.com/beartype/beartype/issues/12 👋. I hope everyone is well. I thought I'd drop in and see what's going on in the wonderful @beartype organisation.

> Microsoft only allots public repos 2,000 GitHub Actions minutes per month for an average of 66.66 minutes per day.

I presume this is from https://github.com/pricing. However, may I draw your attention to the small print 🔎:

> 2,000 Actions minutes/month
Free for public repositories

In case you didn't know, GitHub CI is free for public repos! From https://github.com/features/actions:

![image](https://user-images.githubusercontent.com/12570877/107849658-a43f6d00-6df4-11eb-9a0f-7f35bc153f1c.png)

From the [docs](https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions#about-billing-for-github-actions):

> GitHub Actions usage is free for both public repositories and self-hosted runners. For private repositories, each GitHub account receives a certain amount of free minutes and storage, depending on the product used with the account.

Or from their [blog](https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/#simple-pay-as-you-go-pricing):

> We want every open source project to be productive and use best practices, so Actions is free for the 40 million developers on GitHub to use with public repositories. For private repositories, Actions offers simple, pay-as-you-go pricing.

This is why a lot of people (including myself) moved from Travis CI to GitHub Actions after [Travis changed their pricing model](https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works).

Hopefully this should save you a lot of hassle.

All the best,
Haren

**Comment by leycec** [comment]
`</facepalm>`

...this is why my face continually looks like it has egg on it. Because, it does. Thanks a mud-flecked snow load for the detailed writeup on something I should have already know but didn't apparently several seconds of cursory Googling is insufficient to actually know something, @Harens.

It was equally fascinating and depressing to learn about Travis' suicidal business model – especially in light of their front runners as the first-to-market CI solution. We all have fond memories of early-days Travis, but... **wow.** They sure botched that landing in the final kilometre, didn't they? *Idera, may you reap the shareholder tears you have sown.*

Due to this blessed news that I consecrate with my broken ski poles, commit 058ef6a686caaac:

* Expands our build matrix for CI testing to macOS. **Yay!** We don't *need* to test on macOS per se, because we currently have no platform-specific code. Nonetheless, we do this in remembrance of @harens.
* Increases our timeout for CI jobs from five to ten minutes. **Yay!** Tests are allowed to live slightly longer now.
