### ISSUE TITLE
PEP 561 compliance

### ISSUE THREAD

**Issue by harens** [beartype/beartype#25]
Hi @leycec and the @beartype organisation 👋 

I'm currently rewriting large parts of a [project of mine](https://github.com/harens/seaport), and I'm planning on using beartype 🐻 with it! (because beartype is _awesome_ 😎)

Part of the rewrite involves creating a python module that users will be able to import. Currently, my project is [PEP 561 compatible](https://www.python.org/dev/peps/pep-0561). However, beartype causes some issues with this making it no longer the case.

For instance, if I were to run `mypy --strict` on my code, I now get lots of the following errors:

```
Untyped decorator makes function "..." untyped
Skipping analyzing 'beartype.cave': found module but no type hints or library stubs
Skipping analyzing 'beartype': found module but no type hints or library stubs
```

This then has the knock on effect that the functions in my project appear untyped when imported, making it no longer PEP 561 compliant.

Assuming beartype is properly annotated, which I'm  200% sure it is, it should hopefully be as simple as adding a `py.typed` file in the [project directory](https://github.com/beartype/beartype/tree/main/beartype). See the [mypy docs](https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-type-hints-for-third-party-library) for more info. This could then be another PEP ticked off in the [compliance](https://github.com/beartype/beartype#compliance) list.

Since you have a lot (and I really do mean a lot) more experience with these different PEPs and type checking than I do, please let me know if I'm missing anything. Thank you for your help and for maintaining this great project.

**Comment by leycec** [comment]
> Hi @leycec and the @beartype organisation :wave:

**Oh! Oh!** It's Haren, everyone's favourite macOS package maintainer, GitHub infrastructure expert, and just all-around inspiring code hero – back from early retirement with a hard-hitting deep dive into PEP compliance that will make us all better, stronger, and more employable Pythonistas. *It's gud.* :pleading_face: 

> I'm currently rewriting large parts of a project of mine, and I'm planning on using beartype :bear: with it! (because beartype is awesome :sunglasses:)

Oh, you. Sweet pillow talk and strenuous promises of a new reverse dependency on `beartype` guarantee zero-day issue turnaround here at @beartype, Ltd. (Choose `beartype`: because bears would do it, too.)

> However, beartype causes some issues with this making it no longer the case.

![Noooooo!](https://i.kym-cdn.com/entries/icons/original/000/000/854/vader_NOOOO.jpg)

> For instance, if I were to run `mypy --strict` on my code, I now get lots of the following errors:

That's... *not good.* We want and need to be mypy-compatible, so this is now my new low-hanging fruit. Let us pluck that fruit and stroke it gently.

> This then has the knock on effect that the functions in my project appear untyped when imported, making it no longer PEP 561 compliant.

**Wow.** That's pretty awful. There's just no upside here, is there?

> Assuming beartype is properly annotated, which I'm 200% sure it is...

*shifty eyes nervously dart to the escape pod*

About that... it might not be.

I mean, I 63% *think* it *mostly* is – but rigorously annotating `beartype` itself was never a personal milestone, mostly because I couldn't use `beartype` to type-check itself, <sup>*damn you, chicken and egg*</sup> which meant I had no real-world incentive to rigorously annotate `beartype` itself, except now I belatedly learn at the eleventh hour on the precipice of shipping a new stable release that I *do* have a real-world incentive to rigorously annotate `beartype`, because if I don't, everyone using `beartype` will start yelling at me, because mypy will start yelling at them.

This is the circle of type-checking pain, where everyone pays equally for the sins of one bad dev. I ask, is this justice?

> ...it should hopefully be as simple as adding a `py.typed` file in the project directory.

...we can do that. I like simple. But nothing is simple except *Dragon Quest 1* (NES), where the only meaningful goal is massacring an endless litany of pixelated slime until even child-you gets bored, goes outside for the first time in several days, and has a brisk run around the lawn until passing out.

![Gods help us all.](https://www.destructoid.com//ul/519229-Slimes.jpg)

As a punitive self-admonition, I note to myself that I should also:

* Run `beartype` through mypy to catch all lingering annotation mishaps.
* **Add a unit or functional test ensuring this never happens again.** I currently have no idea how to do that, but suspect mypy (or perhaps another static type checker) provides some sort of public API for validating annotation mishaps. If all else fails, we can literally just shell out to `mypy --strict` from within a functional test and fail if `mypy` reports anything *other* than unadulterated perfection.

We now have a new `beartype 0.5.2` milestone, folks. :moyai:

**Comment by leycec** [comment]
**Uh oh.** @leycec made a boobie:

```
$ mypy ~/py/beartype
...
Found 398 errors in 75 files (checked 160 source files)
```

That wasn't even `mypy --strict`. We can only imagine what *that* would say.

There's goes February.

**Comment by leycec** [comment]
We're down to **155 mypy errors** across the main `beartype` codebase, which is better than the prior 398 but admittedly still non-ideal. I cast *Eternal Torment* on the defenceless static type checker! :skull:

**Comment by harens** [comment]
Thank you @leycec for your major progress on this. I must say that I felt saddened to see all the work you've done (not to mention the delay in the release of 0.5.2). I thought it would be a simple fix, which is why I raised the issue. Nevertheless, I've decided that I want to help as well in whatever way I can!

Now what I'm about to say, I say very cautiously, and note that what I say may not be true. Ok, here it goes...I don't think we need to get rid of all the mypy errors within Beartype to be PEP 561 compliant. Shock! 😱. I think we can break down this compliance issue into two parts:

* Stop mypy from complaining __from the user's perspective for their project__.
* Allow PEP 561 packages to remain compliant (and hopefully make Beartype compliant along the way).

Although squashing errors within Beartype helps to prevent mypy from grumbling at you, the glorious @beartype dev, it shouldn't necessarily make a difference to the user (especially if we're correcting errors for Beartype modules that users won't import).

I think the priority should be adding basic annotations to the decorators and the various beartype-specific types. Once we've done that, I think that should be enough for now.

---

Having said all of that, it is nice to reduce the amount of errors mypy spews out. I was able to reduce it to ~112, so I'll send a WIP PR for this. I also fixed a minor issue with the `py.typed` file that I'll discuss there *(I forgot that there's a bit more than just creating the file, that one's on me 🖐️)*.

---

So...I was testing my changes locally with my seaport project, and from a user's perspective, here's what I found.

When running `mypy` on my project with the new changes, I now only get the following error:

```
error: Variable "beartype.cave.NoneTypeOr" is not valid as a type
note: See https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases
```

I make use of both `NoneTypeOr` and `NoneType` in my program, so I presume this error will also occur for other beartype-specific types except `NoneType`. Overall however, I think that this is great progress from before! 🥳 All from adding that `py.typed` file.

When running `mypy --strict`, I get the same error as above but I also get the following:

```
error: Module 'beartype' does not explicitly export attribute 'beartype'; implicit reexport disabled
error: Untyped decorator makes function "..." untyped
```

I won't pretend I properly understand the first error, but adding [`--implicit-reexport`](https://mypy.readthedocs.io/en/stable/config_file.html#confval-implicit_reexport) fixes it. I think it's to do with how `__all__` is set up, but I'll let that be your call since the docstrings imply to me that we don't touch it.

As for the second error, I'm going to presume that those type annotations just need to be added for the decorators. I'll do some more local testing and playing around before sending a PR, and I'll let you know what I find.

Due to time zone differences, I'm hoping that a PR should be up by the time you read this helping to reduce possible conflicts. Thanks again for all your work on this @leycec. I really appreciate it.

All the best,
Haren

**Comment by leycec** [comment]
When you're so close you can taste the sweet nectar dripping down your ruddy cheeks:

```
$ mypy ~/py/beartype
...
Found 8 errors in 5 files (checked 82 source files)
```

You will be mine, ripe peach. *Oh, yes.* :peach:

**Comment by harens** [comment]
Wowsers! 😮 I'm stunned. I didn't think that this would be possible, let alone only two days after I opened the issue. Thank you for your hard work on this @leycec. You are scarily efficient 👻.

Just a few notes from me. My experience with `MANIFEST.in` files is flat out zero, but I think `include` needs to be added to the front of this line. Otherwise the file isn't included.

https://github.com/beartype/beartype/blob/ceee48b9717a6cd2dfe7846276fb0c90e71a8751/MANIFEST.in#L22

Another thing, I tried what you suggested for `__all__ = ['beartype']`, and it seems (at least for me) to remove the `implicit reexport disabled` error. I think you're right about this being a mypy 0.800 error, since I remember reading somewhere that it affects this version and I'm using said version.

However, for whatever reason, I'm still getting the `Untyped decorator` and `not valid as a type` errors. 

For the first error, I think we just need to properly annotate the main decorator (which is currently unannotated):

https://github.com/beartype/beartype/blob/ceee48b9717a6cd2dfe7846276fb0c90e71a8751/beartype/_decor/main.py#L274

I'm not sure about the second error. I think https://github.com/python/mypy/issues/2477 has something to do with it but I don't know.

**Comment by leycec** [comment]
> You are scarily efficient :ghost:.

I frighten myself in front of the mirror every morning! Heavy nine o'clock beard shadow: it's just *not* a healthy winter look. :bearded_person: 

> My experience with `MANIFEST.in` files is flat out zero...

**Take all my jealousy.** Like the predatory man-cougars inhabiting the closest adjacent roadhouse, my advice remains the same: it is best not to get involved. In my case, I like to minimize my contact with Python's unclean packaging system. `MANIFEST.in` enables that by centralizing all non-module filename filth into a single unified ~~brothel~~ cesspit.

I humbly apologize for shifting your hard-won contributions from `setup.py` (where they rightfully belong) to `MANIFEST.in` (where they can only cause renewed suffering). If it's any consolation, I had to take five baths afterwards to wipe away the gnawing sense of maintainer regret and cloying stench of packaging anti-patterns.

> I think `include` needs to be added to the front of this line.

Christ on a chocolate crucifix, I think you're right. I even wrote a unit test supposedly exercising this. Y U fail me now, last-minute shoddy tests? `</sigh>`

> Another thing, I tried what you suggested for `__all__ = ['beartype']`, and it seems (at least for me) to remove the `implicit reexport disabled` error.

**3.1415 cheers!** It shall be done, macOS Master.

> For the first error, I think we just need to properly annotate the main decorator (which is currently unannotated):

**3.1415 groans!** I *would* annotate everything except the whole point of everything. This is how the static type-checking ends: not with an issue resolution, but a collective groan.

I shall fix everything that is broken and then everyone will know true happiness, just like in the ending of [*Roadside Picnic*](http://soviethistory.msu.edu/wp-content/uploads/2015/10/picnic.pdf) – **only the greatest scifi novella of all time that I have just cruelly spoiled.**

**Comment by leycec** [comment]
...can't help but feel like [Johnny Cash brokenly shouting "Eight more minutes to go!" at Folsom Prison](https://www.youtube.com/watch?v=jxvR7ZUjaJk) here. Cue type-hinted prison riot.

**Comment by harens** [comment]
> ...can't help but feel like Johnny Cash brokenly shouting "Eight more minutes to go!" at Folsom Prison here

We're almost there @leycec, we're very close now. 🏁

The `__all__` thing seems to have worked, and the py.typed file is included. 🎉 I wouldn't worry too much about those last 8 mypy errors since it won't make a difference to the user.

The only issue left is that `not valid as a type` error. As a temporary workaround for my project, I've dropped `NoneTypeOr` in favour of `Optional`, but obviously this workaround doesn't apply to some of the other beartype types (and it would be nice to fix it properly).

As a small reproducible example:

```python
from beartype import beartype
from beartype.cave import NoneTypeOr

@beartype
def example(name: NoneTypeOr[str]) -> str:
    return "Sam" if name is None else name
```

```sh
> mypy --version
mypy 0.800
> mypy demo.py
demo.py:5: error: Variable "beartype.cave.NoneTypeOr" is not valid as a type
demo.py:5: note: See https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases
Found 1 error in 1 file (checked 1 source file)
> mypy --strict demo.py
demo.py:5: error: Variable "beartype.cave.NoneTypeOr" is not valid as a type
demo.py:5: note: See https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases
Found 1 error in 1 file (checked 1 source file)
```

I don't know if you have any ideas on this, but I'm a bit stuck. However, once this is fixed, then we're done (both for mypy *and* mypy --strict).

**Comment by leycec** [comment]
Ah, the classic `error: Variable "beartype.cave.NoneTypeOr" is not valid as a type` mypy complaint. As with most mypy complaints, this happens because mypy is attempting static analysis on a dynamic language. Since attempting static analysis on a dynamic language fundamentally fails in the general, average, *and* worst cases (which is to say, basically always), mypy fails. Good times.

Specifically, mypy successfully sees that `beartype.cave.NoneTypeOr` is a dictionary (*that's good*) but then fails to realize that the values of that dictionary are PEP-compliant type hints (*that's bad*). The simplest fix is for me to squelch mypy by annotating line 1233 of `beartype.cave` like so:

```
NoneTypeOr: _Any = _NoneTypeOrType()
```

Shut up, mypy! You will accept all our dynamism and *you will like it.*

**Comment by leycec** [comment]
**Bwahalla!** Beartype is now successfully PEP 561-compliant. We know this, because:

* Mypy no longer locally complains on my miraculous devbox. The miracle is that my devbox still runs despite a thick layer of dust and grime coating every possible computer component.
* [We now dynamically run mypy as a functional test embedded in our pytest suite on every push *and* PR](https://github.com/beartype/beartype/blob/bbc2cbb829606402063080c5c8a7a63fb740bba1/beartype_test/a90_func/pep/test_pep561_static.py#L24), which means no one gets to break mypy compatibility without GitHub itself tagging their public usernames with unforgettable epithets like `build breaker` and `release molester`.

I wish those were badges. Someday, GitHub. *Make this happen.*

I'll push out a stable release as soon as I stop playing video games about dysfunctional Japanese criminal underworld bosses, because preserving your PEP 561-compliance matters to me. Thanks again for all the tremendous volunteerism, Haren! You assure quality merely by breathing. :wind_face:

**Comment by Gonzom** [comment]
@leycec, this seriously was one of the best pieces of code-related texts I had the pleasure of reading :) Can't wait for the Netflix adaptation!

**Comment by posita** [comment]
> ... and then everyone will know true happiness, just like in the ending of [_Roadside Picnic_](http://soviethistory.msu.edu/wp-content/uploads/2015/10/picnic.pdf) – **only the greatest scifi novella of all time that I have just cruelly spoiled.**

Spoiler alert: The ending is definitely _**not**_ spoiled, and I am grateful for the reference! I am left wondering if I should feel a little embarrassed by:

1. Not already being aware of this fantastic story; and/or
2. Taking over a year-and-a--half to finally sit down and read it once I was.

The translation is fantastic. (I had to look up what a "[Cryptomaoist Edition"](https://www.cca.org/cm/) was. Spoiler alert: the actual definition is much more mundane than the portmanteau would suggest.)

**Comment by leycec** [comment]
`</chortles_in_cryptomaoist_glee>`

I know, right? *Roadside Picnic* is scifi's best-kept secret. The main protagonist is, in a certain vivid sense, the Zone itself. The juxtaposition of humanity with the inhuman only further highlights the inhumanity of humanity – as it does in George Romero's earliest work (and all good body horror, really).

We shall all search in vain for similar works of existentialist societo-environmental critique wrapped in the thinnest veneer of magical realism doused liberally with the literary kerosene of a Soviet culture itself poised on the precipice of collapse. The only masterpieces that reach the same heights for me are:

* Georgiy Daneliya's *Kin-dza-dza!* – the greatest Cryptomaoist <sup>*chortles*</sup> satire of industrial civilization, technological progress, and Soviet-era brutalism. Also, the greatest Monty Python film that Monty Python never made but really wish they had in hindsight. I have never laughed as hard as I have laughed while repeatedly watching *Kin-dza-dza!* for fourty-eight hours straight. My wife did not appreciate this brief period of my life, oddly. Like *Roadside Picnic,* **read nothing, watch nothing, and learn nothing before watching _Kin-dza-dza!_** Some things are best enjoyed straight.
* Hayao Miyazaki's *Nausicaa* – the manga, of course. It intermingles an incredibly bleak, despairing, and hostile worldview with a profound belief in the intransigence of the individual human spirit. A post-post-post-apocalyptic humanity has – through millennia of malign negligence, wanton greed, and scientific misconduct – pushed itself to the furthest shore of habitable existence. Will we voluntarily pull back from the man-made brink? *Cue thunder, brimstone, and magical flying devices.*
