### ISSUE TITLE
[Feature Request] Satisfy static type-checkers by exporting `beartype.roar._roarwarn._BeartypeConfReduceDecoratorExceptionToWarningDefault`

### ISSUE THREAD

**Issue by KyleKing** [beartype/beartype#260]
Would you be open to exporting `_BeartypeConfReduceDecoratorExceptionToWarningDefault` as part of the `beartype` public API?

https://github.com/beartype/beartype/blob/7d9dc4efd2b14867d80f292cc328f204c1d4c888/beartype/_conf/confcls.py#L18-L19

`mypy` and `pyright` didn't like me using [`**kwargs` to optionally set `warning_cls_on_decorator_exception` to None](https://github.com/KyleKing/calcipy_template/blob/7db5f3ed1bafea4c3151b523467aa06004431fd3/package_template/%7B%7B%20package_name_py%20%7D%7D/__init__.py.jinja#L41-L43), so I'm using the private import in the interim:

https://github.com/KyleKing/calcipy_template/blob/23fa65c0400cac50c1cc1b3770526af669ce0159/package_template/%7B%7B%20package_name_py%20%7D%7D/__init__.py.jinja#L39-L48

**Comment by leycec** [comment]
**Gah!** y u so face-numbingly dumb, `mypy` and `pyright`? `</sigh>`

The answer, of course, is: "Certainly!" I'd be happy to publicly export that to reduce the face-numbing pain you and your codebase have felt for over a week. That said:

* I'll probably *never* publicly document `BeartypeConfReduceDecoratorExceptionToWarningDefault` – because nobody should *ever* explicitly pass that anywhere. The only reason that fake "warning type" exists is to enable `beartype.claw` to differentiate between someone passing the `warning_cls_on_decorator_exception` parameter and someone *not* passing that parameter.
* Relatedly, thanks so much for supplying [that working code snippet](https://github.com/KyleKing/calcipy_template/blob/23fa65c0400cac50c1cc1b3770526af669ce0159/package_template/%7B%7B%20package_name_py%20%7D%7D/__init__.py.jinja#L39-L48). Given that, you *probably* want to avoid violating privacy encapsulation by passing the public `beartype.roar.BeartypeClawDecorWarning` warning type rather than the fake `beartype.roar._roarwarn._BeartypeConfReduceDecoratorExceptionToWarningDefault`: e.g.,

```python
    # You almost certainly want to do this rather than what you're currently doing.
    # I almost certainly want to be sleeping rather than what I am currently doing.
    # How could two devs have gone so wrong? I blame my shady docos for everything.
    if beartype_mode != _BeartypeModes.OFF:
        from beartype.roar import BeartypeClawDecorWarning
        beartype_warning_default = BeartypeClawDecorWarning

        beartype_this_package(conf=BeartypeConf(
            warning_cls_on_decorator_exception=(
                None if beartype_mode == _BeartypeModes.ERROR else beartype_warning_default
            ),
            is_color=getenv('BEARTYPE_NO_COLOR') is not None),
        )
```

Does that suffice to satisfy `mypy` and `pyright` *or* would you still like me to publicize `BeartypeConfReduceDecoratorExceptionToWarningDefault`? I'd be happy to if I have to – but it's probably best that I *not* do that unless I really need to. You decide, King Kyle. :+1: :prince: :crown:

**Comment by KyleKing** [comment]
Perfect, that works for me!
