### ISSUE TITLE
[Feature Request] Universally Opt Out of Logged Warnings

### ISSUE THREAD

**Issue by KyleKing** [beartype/beartype#274]
Expanding on #201, I think there might be a use case for `BEARTYPE_HIDE_WARNINGS` where when set, the behavior is the same as if someone had configured:

```python
from beartype.roar import BeartypeDecorHintPep585DeprecationWarning
from warnings import filterwarnings
filterwarnings("ignore", category=BeartypeDecorHintPep585DeprecationWarning)
```

from option 3 of: https://beartype.readthedocs.io/en/latest/api_roar/#are-we-on-the-worst-timeline

The context is that a coworker saw the PEP585 warning and then requested runtime type checking to be removed entirely, which I countered with making it opt-in with next-gen tasty  bearclaw:

![Bearclaw Time](https://www.parkavenuebakery.net/wp-content/uploads/2018/08/PAproducts-112_xgaplus.jpg)

**Comment by leycec** [comment]
I see your decadent morsel that ruptures my gums just *looking* at that sprawling paean to the folly of ~~Man~~ the pastry industry and raise you this true reenactment of your workplace:

> **@beartype:** Your code is busted and your codebase will die in less than two years. Thankfully, you can fix this by just globally replacing `\bfrom typing import\b` with either `from typing_extensions import` or `from beartype.typing import`. I know, right? Neat-o.
> **Coworker:** I hate @beartype. Make @beartype die.
> **@KyleKing:** @beartype kinda has a point there. Maybe we should jus–
> **Coworker:** I HATE @beartype. MAKE @beartype DIE.
> **@KyleKing:** One of us would benefit from group programming therapy. I don't think it's me.
> **Coworker:** Was that sarcasm, Kyle? Because that sounded like sarcasm, Kyle.
> **@KyleKing:** ...I'll make @beartype opt-in.
> **Coworker:** I will always opt out of that.
> **@beartype:** I'm not feeling so good about this workplace. What about *my* feelings?

What @beartype is trying to say is that your coworker is busted, your code is busted, and your codebase will die in less than two years. That's the bad news. But you can fix this by just globally replacing `\bfrom typing import\b` with either `from typing_extensions import` or `from beartype.typing import`. That's the good news.

The correct decision is to just do that global replacement. Stop importing `typing`, because `typing` is forward-incompatible. Start importing something that *is* forward-compatible. `typing_extensions` is the obvious choice, but `beartype.typing` is equally valid.

The correct decision is *not* to:

* **Globally disable runtime type-checking.** That is the worst possible thing your coworker could do.
* **Globally silence deprecation warnings.** That is the second-worst possible thing your coworker could do.

Both of those things only temporarily mask the underlying issue, which is bad. Thankfully, the underlying issue is trivially resolved with a single global search-and-replacement, which is good.

## Broken Humans Make Broken Code

@KyleKing, I respect and applaud you. You know this. You do phenomenal work across the open-source community – and probably across the academic and startup community, too. But... *your coworker is a broken human.* We can't repair broken humans like your coworker, but we can quietly ignore them and hope they mend their broken approach to software engineering.

Ordinarily, I'd be delighted to add yet-more-environment-variables to our growing laundry list of insanity. But this isn't an ordinary use case. Seriously. Should *anyone* in *any* programming language be ignoring deprecation warnings about *anything*? No. No, they shouldn't. Everyone should feel a bone-chilling, brain-boding fear whenever a deprecation warning erupts. Nobody should shrug and pretend that everything is okay and "Won't someone just *shut that deprecation warning up,* already!?!?"

**Gah.** You're so demonstrably awesome, @KyleKing. I seriously hate closing a feature request that you've proposed, because you've repeatedly demonstrated that you're awesome. But this feature request... I dunno, bro. @beartype can't fix busted humans. The real issue here seems to be your busted coworker. That's a social issue, a managerial issue, and a PEBKAC issue.

I'm no good at those sorts of things, which helps explain why I live in a cabin in the Canadian wilderness surrounded by ravenous man-eating carnivores that most people think are X-men. I am here to tell you that wolverines, lynxes, and fishers do, in fact, exist. I wish they didn't. Especially fishers. Those things terrify me. They lurk in trees. They're huge. They look like bear-cat hybrid things with blood-flecked claws the size of tree trunks. Have you even seen a fisher up close? That's usually the last look anyone gets. I shudder, bro. I shudder.

Let's quietly close this for the good of Canada. I don't even know what that means. Nonetheless, I sigh. :face_exhaling:
