### ISSUE TITLE
[DOOR Bug] `typing.Literal[...] <= typing.Union[typing.Literal[...], ...] is False`

### ISSUE THREAD

**Issue by PhilipVinc** [beartype/beartype#276]
(Reduced from plum's [beratype/plum#99](https://github.com/beartype/plum/issues/99))

Comparing `TypeHint` for Literal types and union of literal types does not work. In this case one of the two statements should clearly be true.

```python
import beartype
from beartype import door
import typing

beartype.door.TypeHint(typing.Literal[True])<=beartype.door.TypeHint(typing.Union[typing.Literal[True], typing.Literal[False]])
# False

beartype.door.TypeHint(typing.Literal[True])>=beartype.door.TypeHint(typing.Union[typing.Literal[True], typing.Literal[False]])
# False
```

**Comment by PhilipVinc** [comment]
might be related to #271

**Comment by leycec** [comment]
**Gah!** Thanks so much for the heads up, @PhilipVinc. You're absolutely right; the first statement should evaluate to `True` but currently doesn't, because @leycec let the `beartype.door` subpackage languish for months and now here we are – on the rocky shoals of a busted API with no paddle, no ship, and a rapidly vanishing supply of Jamaican rum:

```python
>>> beartype.door.TypeHint(typing.Literal[True])<=beartype.door.TypeHint(typing.Union[typing.Literal[True], typing.Literal[False]])
False  # <-- this should totally be "True"! ugh. just ugh.
```

I'm currently hip-deep in stabilizing forward references and PEP 563 support for @beartype's upcoming `0.16.0` release. But I've demarcated @beartype's next *next* `0.17.0` release entirely for horrifying DOOR issues like this. Let's see what the bright future holds in store for humanity, Python, and the dancing QA bear that is @beartype.

> I wish Python was more like Julia.

![heresy](https://media.tenor.com/a39vdINFIJsAAAAC/heresy-priest.gif)

![moar heresy](https://media.tenor.com/oXigx7wss6kAAAAd/heresy-detected-warhammer40k.gif)

**Comment by leycec** [comment]
**Resolved by f604f05.** Of course, this also resolves beartype/plum#99. Of course, I am now even more bald thanks to GitHub-related stress injuries incurred during this resolution. I cannot be held responsible if I now begin malding...

Oh, noes. It's happening. I'm malding! *I'M MAAAAAALDING!* :bald_man: `</awkward_cough>`

**Comment by PhilipVinc** [comment]
Amazing! That indeed solves the problems. 
(I'm trying to go through your changes to understand a bit what was going on, and I have to confess it's quite messy. But in the end, who am I? Just a physicist...)

May I ask that you tag a new release? It would allow me to get rid of those ugly `Val` in plum.

**Comment by PhilipVinc** [comment]
> ![heresy](https://camo.githubusercontent.com/f2f8a3cc11162d6a629998521570db73586d80702a648232f91d9b5a8c61e1d6/68747470733a2f2f6d656469612e74656e6f722e636f6d2f6133397664494e46494a7341414141432f6865726573792d7072696573742e676966) [ ![heresy](https://camo.githubusercontent.com/f2f8a3cc11162d6a629998521570db73586d80702a648232f91d9b5a8c61e1d6/68747470733a2f2f6d656469612e74656e6f722e636f6d2f6133397664494e46494a7341414141432f6865726573792d7072696573742e676966) ](https://camo.githubusercontent.com/f2f8a3cc11162d6a629998521570db73586d80702a648232f91d9b5a8c61e1d6/68747470733a2f2f6d656469612e74656e6f722e636f6d2f6133397664494e46494a7341414141432f6865726573792d7072696573742e676966) [ ](https://camo.githubusercontent.com/f2f8a3cc11162d6a629998521570db73586d80702a648232f91d9b5a8c61e1d6/68747470733a2f2f6d656469612e74656e6f722e636f6d2f6133397664494e46494a7341414141432f6865726573792d7072696573742e676966)

Hehe... It's my punishment. I saw paradise but had to come back to purgatory (or hell. I'm unsure) because nobody was there...

**Comment by leycec** [comment]
> I'm trying to go through your changes to understand a bit what was going on...

*...omg.* You are @beartype's first user to ever attempt that. You actually asked: "How? How did you do that?" Nobody has asked that question before. In fact, most users never even extend gratitude after a successful resolution or leave meaningful feedback after a less-than-successful resolution.

This officially earns you the dubious yet glorious title of **One of Beartype's Greatest Users of All Time,** Dr. Vicentini. I'm genuinely honoured. You exhibited insatiable curiosity. You went where few dare to tread.

Are you still curious? Let's pretend you are. I'd like to return the favour by explaining how I resolved this. So, Python. Python internally implements the `<=` operator between two objects via the `__le__()` dunder method defined on the classes of those objects. In this case, this means the [`beartype.door._cls.doorsuper.TypeHint.__le__()` method](https://github.com/beartype/beartype/blob/f604f05faeaf3c093a58539612a8453f87d4c2c6/beartype/door/_cls/doorsuper.py#L231), which internally defers to the [public `TypeHint.is_subhint()` method](https://github.com/beartype/beartype/blob/f604f05faeaf3c093a58539612a8453f87d4c2c6/beartype/door/_cls/doorsuper.py#L611), which internally defers to the private `TypeHint._is_subhint()` method.

`TypeHint._is_subhint()` returns `True` only if the current type hint is a subhint of at least one **branch** (i.e., child type hint) of the passed type hint. Each child type hint of a union is a branch. Ergo, `Union[Literal[True], Literal[False]]` has two branches: `Literal[True]` and `Literal[False]`. So far so good. But here's where things get hairy like a sasquatch.

The `beartype.door` API wraps each type hint with an instance of a subclass of `TypeHint` uniquely handling that kind of type hint. In this case, `beartype.door` wraps each `typing.Literal[...]` type hint with an instance of the [`beartype.door._cls.pep.doorpep586.LiteralTypeHint` subclass](https://github.com/beartype/beartype/blob/f604f05faeaf3c093a58539612a8453f87d4c2c6/beartype/door/_cls/pep/doorpep586.py#L47). That subclass overrides the superclass `_is_subhint()` method with [its own `LiteralTypeHint._is_subhint()` implementation](https://github.com/beartype/beartype/blob/f604f05faeaf3c093a58539612a8453f87d4c2c6/beartype/door/_cls/pep/doorpep586.py#L47). You are now thinking, "I see no problem here, you bald rascal."

The problem here is that the subclass `LiteralTypeHint._is_subhint()` method (which does *not* handle unions) failed to call the superclass `TypeHint._is_subhint()` method (which *does* handle unions) The resolution was thus trivial: just have `LiteralTypeHint._is_subhint()` additionally call the `super()._is_subhint()` as a last-ditch fallback when all else fails. You are now thinking...

> ...and I have to confess it's quite messy.

*...heh.* Yeah. About that. The episode of *Father Ted* in which [Father Ted resolves a minor dent in a prize car is an appropriate reference](https://www.youtube.com/watch?v=Z4fBbhyzE9A) here.

Alternately, consider a life-sized puppet (like in [traditional Japanese *bunraku*](https://www.youtube.com/watch?v=0hoK3RFvxwM) or [its modern reincarnation "Thunderbolt Fantasy"](https://www.youtube.com/watch?v=1muOeJ4fBps)) with a shock twist: *that puppet is filled with a flaming bag of faecal matter.* That puppet is the `beartype.door` API.

![](https://media.tenor.com/mMvIFth0cbQAAAAd/thunderbolt-fantasy-freak-out.gif)
<sup>"This... This cannot be!" — @leycec after debugging `beartype.door`</sup>

![](https://media.tenor.com/cvE5Gh2_7KQAAAAC/thunderbolt-fantasy-tbf.gif)
<sup>Puppet ninjas. At last. Is this the true meaning of `beartype.door`!?</sup>

Imagine what trying to fix an issue in a life-sized puppet filled with a flaming bag of faecal matter would be like.

You notice a minor defect. You repair the minor defect. Much to your despair, the repair causes the puppet to dribble flaming faecal matter out of its mouth and all over its silk tunic. While muttering incoherently to yourself, you quietly staunch the flames, dab up the faecal matter, and patch the tunic as best you feebly can. In so doing, you tragically rip the tunic – exposing yet more flaming faecal matter, which then spews a putrid miasma of viscous flames everywhere (including all over you). Now drenched in flaming faecal matter, you flail about madly as the flames threaten to ignite your now purulent and irreparable facial hair. In so doing, you accidentally fling yourself from the precipitous plateau you were working on five hundred feet below into a boulder-strewn whitewater gorge. Miraculously, you narrowly avoid the jagged rocks during your harrowing descent into the violently raging river – leaving only the femurs in both legs crushed by this real-world demonstration of Newtonian mechanics.

You gingerly wash up onto the opposite shore. Broken, battered, but undefeated. You live. You vow to never fix an issue in a life-sized puppet filled with a flaming bag of faecal matter again.

This is what it means to maintain @beartype.

> May I ask that you tag a new release?

For the physicist who expressed curiosity, **anything!** I'll pump this out Friday evening with our next `beartype 0.16.0` stable release.

> I saw paradise but had to come back to purgatory (or hell. I'm unsure) because nobody was there...

That... that was the single most intelligent one-liner existentialist metaphor anyone has ever said to me.

[Power-law dynamics](https://en.wikipedia.org/wiki/Power_law), curse you. You have denied @PhilipVinc his crowded paradise. In so doing, you have made a mortal enemy of @leycec.

<sup>@wesselb: This may be of relevance to you. I summon thee!</sup>

**Comment by wesselb** [comment]
This was a great read :). Thanks again @leycec for getting to the bottom of this and writing this up. Maintaining `beartype.door` must be a real pain, but you're truly doing a better-than-awesome job.
