### ISSUE TITLE
[Bug] `@beartype` + `@classmethod` + `@property` = dumpster fire

### ISSUE THREAD

**Issue by empyrealapp** [beartype/beartype#278]
I believe I found a bug in beartype.  When you create a classmethod property, you get an error: `AssertionError: <property object at 0x108952a70> uncallable.`.  I believe this is due to stacked decorators on a property which is normally not callable from the class.

```
@beartype
class A:
    @classmethod
    @property
    def foo(cls):
        return 10

```

**Comment by leycec** [comment]
> I believe I found a bug in beartype.

:fearful: → :scream:

> I believe this is due to stacked decorators on a property which is normally not callable from the class.

**It's true!** It's all true! Welp, there goes the upcoming @beartype 0.16.0 release. Let's chuck everything in the dumpster and start over from scratch, everybody.

Thanks so much for the heads up on this sweltering Thursday, @empyrealapp. It's actually fascinating that you're the first @beartype user to ever create a class property. You'd think that would be more common. I must admit: I don't think even I've done that. And I've done everything! Usually when I didn't need to and probably shouldn't have. But... *still.*

We'll get this patched up for you in a jiffy. High five from the QA cat.

![qa cat omg](https://media.tenor.com/_2WaHoKCVJ4AAAAC/cat-high.gif)

**Comment by leycec** [comment]
**Welp...** I have good news and I have bad news, @empyrealapp. Let's start with the bad. That way, everyone gets a happy ending.

What you want to do is [**officially deprecated under Python ≥ 3.11 and guaranteed to fail under some future release:**](https://docs.python.org/3.11/library/functions.html?highlight=classmethod#classmethod)

> Changed in version 3.11: Class methods can no longer wrap other [descriptors](https://docs.python.org/3.11/glossary.html#term-descriptor) such as [`property()`](https://docs.python.org/3.11/library/functions.html?highlight=classmethod#property).

## Make the Pain Go Away, Daddy @leycec

Allow me to now numb your pain. What you want to do is still readily achievable in the same way that it always was (i.e., before Python 3.8 permitted `@classmethod` to be chained into `@property`). This is a two-step process that you will love to hate – but there no longer exists another way. Going forward, this is the *only* way:

1. Define a new metaclass for your class.
1. Define your class property on that metaclass rather than on your class.

Refactoring the above example then yields this forward-compatible solution for Python ≥ 3.11:

```python
from beartype import beartype

@beartype
class AMeta(type):
    '''
    Metaclass of the :class`.A` class, defining class properties for that class.
    '''

    @property
    def foo(cls):
        return 10


@beartype
class A(object, metaclass=AMeta):
    pass
```

## You Suck, Daddy @leycec!!!!!!

Embrace the metaclass. Search your feelings. Metaclasses are good. You know it to be true.

That said, Python 3.8, 3.9, and 3.10 *do* still exist. Since these versions still permit `@classmethod` to be chained into `@property`, @beartype should permit that too – even if it's kinda wrong and will result in your code rupturing money and blood in a few years. It's your code, after all; we're all consenting adults here. If you want to blow yourself up, @beartype should help you do that.

@beartype: *helping you blow yourself up since 2014.*

**Comment by posita** [comment]
> @beartype should permit that too – even if it's kinda wrong and will result in your code rupturing money and blood in a few years.

I'm assuming this means that such an implementation would require @beartype itself not to rupture money and blood in a few years, though, right? I'm curious. What's the play? [`inspect.getattr_static`](https://docs.python.org/3/library/inspect.html#inspect.getattr_static) every `@classmethod` to see if it wraps a `@property`, and then ignore those?

Guerrilla patch the `@classmethod` to somehow sandwich a @beartype in there somewhere?

![bear sandwich](https://media.tenor.com/yq5vv20HwyoAAAAM/brown-bear.gif)

Or something even _**more**_ dia-bear-ical?!

![need to know](https://media.tenor.com/rUh3-JZW_hgAAAAM/igotstoknow-barney.gif)

_For the benefit of our home audience, @leycec is smarter than I am, so he's probably got some kind of [Wile E. Coyote, Super Genius](https://youtu.be/STeVTzWelns) thing planned. (Professional driver, closed course, do not attempt.)_

**Comment by leycec** [comment]
**OMG.** Super-Genius @posita on the scene with drive-by memin', schemin', and dreamin'! Fat high fives as CPython devs leer in the background.

![future cop](https://media.tenor.com/BLd5B4WFDfYAAAAd/high-five-demolition-man.gif)

> I'm assuming this means that such an implementation would require @beartype itself not to rupture money and blood in a few years...

B-b-but won't @beartype *always* be rupturing money and blood? My wallet and wrists feel drained. Isn't this just how it's supposed to be?

\> *rolls a [Malkavian](https://vtmb.fandom.com/wiki/Malkavian) in World of Darkness*

\> *cackles madly as @beartype continues rupturing money and blood without cessation*

\> *whimpers sadly under the stunning meta-realization that rolling a [Malkavian](https://vtmb.fandom.com/wiki/Malkavian) only intensifies the rupturing of money and blood without cessation*

\> *quietly gets up and leaves the table, along with all of the Mountain Dew and Cheetos*

Seriously. There's no play. Class properties are busted. Not even @beartype can monkey-patch busted.

*...okay.* @beartype could *totally* monkey-patch busted. We monkey-patch busted all the time! But we can only break so many iconic Python idioms before the whole thing slowly burns down, falls over, then sinks into the swamp. How did you even *think* of those inhuman plays? Like...

> [`inspect.getattr_static`](https://docs.python.org/3/library/inspect.html#inspect.getattr_static) every `@classmethod` to see if it wraps a `@property`, and then ignore those?

Does your perfidious infatuation with pain know no bounds!?!? Also: how, why, and when do you know about `inspect.getattr_static()`? Actually, belay that answer. I'm shook already. :hot_face: 

> Guerrilla patch the `@classmethod` to somehow sandwich a @beartype in there somewhere?

*...okay.* Okay, already! You can't keep a dark brooding secret from @posita. He knows what you did last ~~summer~~ commit. I admit it! I admit everything. It's all true. Everything, @posita. That's actually exactly what we did. You couldn't possibly have known, yet you knew. We sandwiched it. We sandwiched the whole thing. Can @beartype haz cheezeburger? Yes.

Specifically, @beartype now iteratively:

1. Slyly insinuates itself after each `@classmethod` descriptor and then...
1. Slyly insinuates itself after each `@property` descriptor.

It's so diabolically awful and short-sighted, it couldn't possibly work. Therefore, it works.

![wut](https://media.tenor.com/VHn31zQYHwUAAAAd/%E5%B4%A9%E6%BA%83-collapse.gif)
<sup>I'm unclear what's happening here. Yet, this expresses my feelings.</sup>

**Comment by leycec** [comment]
**Resolved by 77db6100950.**

@empyrealapp: you [*really* don't want to do what you're doing](https://github.com/beartype/beartype/issues/278#issuecomment-1712405058), but @beartype now happily lets you dig your own explosive cadaver.

@posita: you didn' see nuffin'.

**Comment by posita** [comment]
> Also: how, why, and when do you know about `inspect.getattr_static()`? Actually, belay that answer. I'm shook already. 🥵

Fun fact<sup>for some definition of fun, and because I can't follow simple instructions</sup>: I actually discovered it after reading your https://github.com/beartype/beartype/issues/278#issuecomment-1712405058. I thought to myself, "Self, how would you go about detecting whether some attribute of a type object was a `@property`-wrapped function without causing side effects by actually accessing that property and without the benefit of `__dict__`<sup>because `__slots__` or something</sup>?" And then, bam. There it was. Although I fully concede my intellectual exercise was completely insufficient to address the cases you've enumerated in 77db6100950b4c0c5f51ea733544ab5160af0f7f ...

> @posita: you didn' see nuffin'.

... which I totally didn't look at.

![nope, didn't see nuffin'](https://media.tenor.com/IzCCMOgXt4sAAAAM/hide-peek.gif)

**Comment by leycec** [comment]
> do not use `inspect.getattr_static` if you are nursing, pregnant, or considering conception

![heh](https://media.tenor.com/aC4y7H87fE4AAAAd/worf-star-trek.gif)
<sup>**Left:** *your codebase.* **Right:** `inspect.getattr_static`.</sup>
