### ISSUE TITLE
README suggestion

### ISSUE THREAD

**Issue by albanie** [beartype/beartype#3]
This all looks splendid. And I can see that you are laying down code at high-speed, so this may already be on the agenda but just as a suggestion: it may make sense to have part of the README explain how the O(1) type checking is performed for arbitrarily long containers.

**Comment by leycec** [comment]
Absolutely. I'd raise an eyebrow at that myself. The short-term game plan is something resembling:

1. **Finalize unit test coverage for the `beartype.cave` submodule** by... *this Friday?* Maybe. Let's be optimistic and joyful.
1. **Add an additional `README.rst` subsection on annotating unions of types with tuples** by... *next Monday?* Maybe. I hate Gantt charts, so let's go with that.
1. **Release beartype 0.1.0 to PyPI** by... *next Wednesday?*
1. **Release beartype 0.1.0 to conda-forge** by... *next Friday?*
1. **File U.S. expat taxes.** Oh, satanic angels below, how I loathe filing U.S. expat taxes. That'll probably take a full month, 'cause U.S. gubment gonna gubment.
1. **Refactor [BETSE](https://gitlab.com/betse/betse) and [BETSEE](https://gitlab.com/betse/betsee) to require beartype 0.1.0.** That'll probably take two weeks, 'cause million-line codebases ain't gonna refactor themselves. It is sad.
1. **Actually begin resolving beartype issues,** like this one for example!

*Ugh.* As we can see, it's gonna be a full summer. On the bright side, at least I'm Canadian during an unsettling period of political unrest, global pandemic, and squinty-eyed sabre-rattling! Yay! :maple_leaf:

**Comment by leycec** [comment]
**[beartype 0.1.0 is now live (and maybe worky) on PyPi](https://pypi.org/project/beartype/0.1.0),** much to the astonishment of my weary brainpan: :sleepy: 

    pip3 install beartype

**Comment by albanie** [comment]
Awesome!  This is a heroic effort. Just a couple of extra comments (after my attempt to understand the contents/comments of [decor.py](https://github.com/beartype/beartype/blob/master/beartype/_decor/decor.py)).  If I understand correctly: 
1. Currently, it isn't feasible for `beartype` types to either use (or be subclasses of) the types defined in the `typing` module.  It mentions in the comments that `typing` disallows the use of `isinstance`, which presumably makes this difficult.  In your judgement, do you think this will remain the case in the long term?  If it was possible to use the `typing` types (or subclasses), I guess all the various linting progress that have sprung up for static analysis in editors might be happliy interoperable with beartype, which would be a bonus without requiring extra development effort on beartype itself.  It would also help enormously in porting code to use beartype (e.g. just add the `@beartype` decorator, or switch from an existing one, which is `@typechecked` in my case).  But clearly, if it's not possible, it's not possible.
2. For now, as the module states, nested type-checking is not supported.  Do you think it would be reasonable to allow `O(D)` complexity, where `D` is container depth (e.g. validate one item in the container at each level of nesting)? I appreciate this will be a non-trivial implementation effort.

**Comment by leycec** [comment]
> Currently, it isn't feasible for `beartype` types to either use (or be subclasses of) the types defined in the `typing` module.

Yup. It is indeed sad. I originally intended to raise human-readable exceptions when users type-check `@beartype` against `typing` types and recommend beartype-specific alternatives where available: e.g.,

* "Use `beartype.cave.NoneTypeOr` rather than `typing.Optional`!"
* "Use tuples rather than `typing.Union`!"

But... then real life rudely intruded and I forgot and beartype 0.1.0 got released anyway. <sup>"Argh!"</sup>

>  It mentions in the comments that `typing` disallows the use of `isinstance`...

Yup. `typing` is overly hostile to our interests. But that's fine! Being anti-authoritarian, I just *love* violating contractual safeguards like that with inscrutable black magic. Moreover...

> ...which presumably makes this difficult.

I thought so too, so I didn't even bother pursuing this line of inquiry. **I absolutely should have.** @terrdavis [cleverly uncovered a private dunder attribute of `typing.Generic` subtypes](https://gist.github.com/leycec/3d48cc60e7d5fe8860b077acb067dc54#gistcomment-2868908) and then [actually refactored a much earlier version of `@beartype` to circumvent `typing` hostility by leveraging that attribute in his Gist of my Gist](https://gist.github.com/terrdavis/1b23b7ff8023f55f627199b09cfa6b24):

> **terrdavis:** It tests for the new error `"TypeError: Subscripted generics cannot be used with class and instance checks"` by always attempting to use the `__origin__` attribute of `Generic` types for instance checks.

I still need to fully grep through @terrdavis's changeset – and I won't really have the time to do that for a few weeks. In theory, that might be our trivial silver bullet. If that works, we can at least superficially pretend to partially support PEP 484-style `typing` subtypes by beartype 0.2.0.

That would be a significant win. Let's hope our dreams come true.

I am fully in agreement with everything else you penned above for point 1. Since `beartype` fundamentally diverges from the *entire* Python type-checking ecosystem (albeit for good reasons), that's a significant barrier to entry for existing projects that we could all do without. Let's see if we can do without that by beartype 0.2.0.

>  Do you think it would be reasonable to allow `O(D)` complexity, where `D` is container depth (e.g. validate one item in the container at each level of nesting)?

That's a fascinating thought. Tragically, `typing` enables end users to annotate infinitely recursive types via forward references. The [canonical binary tree example](https://stackoverflow.com/a/38341145/2809027) is:

```
from typing import List
class Tree:
    ...
    def leaves(self) -> List['Tree']: ...
```

Predictably, *all* fully PEP 484-compliant type checkers (e.g., [mypy](https://github.com/python/mypy/issues/3685)) as well as [the core `typing` library itself](https://github.com/python/typing/issues/667) exhibit infinite recursion issues throughout their codebase lifetimes as a result. I'd like `beartype` to be the exception.

Nested type-checking requires explicit guards against all the various sorts of infinite recursion that `typing` enables, which means we then basically need to implement a rudimentary form of graph theory-based heuristics and analytics to detect and shortcircuit those shenanigans before they blow up in everyone's faces.

Ignoring recursive types and the intestinal pain they cause, it's abundantly clear that **everyone wants at least some sort of finitely bounded nested type-checking.** So, this will definitely happen. `beartype` is here to eventually satisfy everyone's needs – and type-checking at least a subset of container items is a valid and useful need that I myself have in both [BETSE](https://gitlab.com/betse/betse) and [BETSEE](https://gitlab.com/betse/betsee).

This means it will happen. It's more a matter of "When?" and "How?" than "If?" at this point. The devil's in the details and my present lack of free time. Let me get back to everyone in late June with something more meaty and appetizing, eh? :meat_on_bone: :cut_of_meat: :poultry_leg:

**Comment by albanie** [comment]
Sounds great.  For now, I'll use `beartype` for functions with non-nested type annotations and fall back to typeguard for the remainder.  Hopefully, this will help to stress test the module somewhat and allows me to keep the wonderfully succinct beartype exceptions.   Just to emphasise the difference:

```
from beartype import beartype
from typeguard import typechecked


@typechecked
def example_typechecked(a: int):
    pass


@beartype
def example_beartyped(a: int):
    pass

# typeguard example
example_typechecked("1")
```

This raises the following exception:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/coding/src/zsvision/tmp.py in <module>
     14 
     15 
---> 16 example_typechecked("1")
     17 # example_beartyped(1)

~/local/anaconda3/envs/pt37/lib/python3.7/site-packages/typeguard/__init__.py in wrapper(*args, **kwargs)
    807     def wrapper(*args, **kwargs):
    808         memo = _CallMemo(python_func, _localns, args=args, kwargs=kwargs)
--> 809         check_argument_types(memo)
    810         retval = func(*args, **kwargs)
    811         check_return_type(retval, memo)

~/local/anaconda3/envs/pt37/lib/python3.7/site-packages/typeguard/__init__.py in check_argument_types(memo)
    668                 check_type(description, value, expected_type, memo)
    669             except TypeError as exc:  # suppress unnecessarily long tracebacks
--> 670                 raise exc from None
    671 
    672     return True

~/local/anaconda3/envs/pt37/lib/python3.7/site-packages/typeguard/__init__.py in check_argument_types(memo)
    666             description = 'argument "{}"'.format(argname)
    667             try:
--> 668                 check_type(description, value, expected_type, memo)
    669             except TypeError as exc:  # suppress unnecessarily long tracebacks
    670                 raise exc from None

~/local/anaconda3/envs/pt37/lib/python3.7/site-packages/typeguard/__init__.py in check_type(argname, value, expected_type, memo)
    596                 raise TypeError(
    597                     'type of {} must be {}; got {} instead'.
--> 598                     format(argname, qualified_name(expected_type), qualified_name(value)))
    599     elif isinstance(expected_type, TypeVar):
    600         # Only happens on < 3.6

TypeError: type of argument "a" must be int; got str instead
```

Calling instead with
```
example_beartyped("1")
```
raises:
```
---------------------------------------------------------------------------
BeartypeCallTypeParamException            Traceback (most recent call last)
~/coding/src/zsvision/tmp.py in <module>
     14 
     15 # typeguard example
---> 16 example_beartyped("1")

~/local/anaconda3/envs/pt37/lib/python3.7/site-packages/beartype/_decor/decor.py in __example_beartyped_beartyped__(__beartype_func, *args, **kwargs)

BeartypeCallTypeParamException: @beartyped example_beartyped() parameter a='1' not a <class 'int'>.
```
🐻

**Comment by leycec** [comment]
I'm *baaaa-ack* – and just in time for the apocalyptic meltdown of the United States. I would have settled for a saner, stabler ally on Canada's southern border, but... you can't have everything, I suppose.

Immanent doom, declaration of martial law, and suspension of democratic norms notwithstanding, here's what's done from above:

> **Finalize unit test coverage for the `beartype.cave` submodule.**

*done*

> **Add an additional `README.rst` subsection on annotating unions of types with tuples.**

*done*

> **Release beartype 0.1.0 to PyPI.**

*done*

> **Release beartype 0.1.0 to conda-forge.**

In-process, but probably done tonight. Let's wish upon an open-source star. :star2: 

> **File U.S. expat taxes.**

*done* <sup>much to my mutual loathing and disgust</sup>

> **Make beartype compatible with [PEP 563](https://www.python.org/dev/peps/pep-0563) (AKA, TheMostFunctionallyRetardedPEPEver).**

[PEP 563](https://www.python.org/dev/peps/pep-0563) compatibility is up next, because without that *all* annotation-based decorators – including both `beartype` and `typeguard` – fail hard under the upcoming Python 4.0.0 as well as `from __future__ import annotations` under Python >= 3.7.0. Both of those scenarios are bad.

Unsurprisingly, `typeguard` also [fails to support PEP 563](https://github.com/agronholm/typeguard/issues/123) at the moment. Did I mention that [PEP 563](https://www.python.org/dev/peps/pep-0563) is functionally retarded? Because it *really, really* is.

**Comment by leycec** [comment]
> For now, I'll use `beartype` for functions with non-nested type annotations and fall back to `typeguard` for the remainder.

*Yay!* Thanks so much for the early-adopter support. As the world burns in its authoritarian populist prison, we at least can be confident of our runtime-checked Python types. That's something, anyway.

> Hopefully, this will help to stress test the module somewhat...

*Yay!* Stress out this package for the good of us all. If you hit any snags, please file an issue and I'll promptly resolve everything with my beating stick.

> ...and allows me to keep the wonderfully succinct `beartype` exceptions.

**Love it.** I unfathomably :heartbeat: that the principal (perhaps, only) benefit of beartype 0.1.0 over `typeguard` is (wait for it)... *shallow exception tracebacks.* I mean, that wasn't exactly what I was going for – but I'll take it. GitHub star beggars can't be choosers.

The deep `typeguard` traceback you've exhibited *does* raise valid questions and eyebrows, though: like, what exactly were they thinking when they nested exceptions within two seemingly unnecessary exception-handling blocks with unintentionally hilarious justifications like:

```
except TypeError as exc:  # suppress unnecessarily long tracebacks
```

<sup>It would seem that did not have the intended effect.</sup>

I see you're working under Anaconda as well. I take it this means a proper Anaconda package for `beartype` hosted at the `conda-forge` channel would be of value then, yes? If yes, press :ok: to win.

Thanks again for the voluminous support, @albanie! You remain unbearably gr8, m8.

**Comment by leycec** [comment]
The [conda-forge `beartype` feedstock](https://github.com/conda-forge/beartype-feedstock) and [corresponding Anaconda package](https://anaconda.org/conda-forge/beartype) are now live for Anaconda users. Let's do this! Up next: the **[dread PEP 563](https://www.python.org/dev/peps/pep-0563).** :octocat:

**Comment by leycec** [comment]
**0a40b754f1ba now implements PEP 563.** Up next: let's release beartype 0.1.1 while things actually work!

**Comment by leycec** [comment]
**[beartype 0.1.1 is now live on PyPI](https://pypi.org/project/beartype)!** Assuming [conda-forge](https://conda-forge.org) automation plays along, the [beartype package for Anaconda](https://anaconda.org/conda-forge/beartype) should also be automatically bumped in a day or two. This release brings:

* **[PEP 563](https://www.python.org/dev/peps/pep-0563) support**, which means forward compatibility with the upcoming Python 4.0.0 as well as Python 3.7.0—3.9.x under `from __future__ import annotations`.
* Optimization for **unannotated callables** (i.e., callables annotated with *no* type hints), which `@beartype` now preserves as is rather than encapsulating with a useless noop wrapper. <sup>*...woops*</sup>
* An **[exhaustive feature list](https://github.com/beartype/beartype#id9)**, charting progress on type-related PEPs and core feature requests across `beartype` versions.

My beautiful wife's birthday is in a few days, which means I better take a brief respite from open-source volunteerism and attend to the "real" world of gritty needs, deeds, and creeds. When I miraculously return in a week or two, work on the hotly anticipated beartype 0.2.0 shall valiantly begin. :crossed_swords: 

Thanks again for the continued interest, @albanie! I may only have two users — but they're the best users a project could ever ask for.

Up next: **shallow PEP 484-style `typing` support.** Everyone wants it. Well, everyone shall get it!

**Comment by albanie** [comment]
This is awesome. With `typing` support exponential userbase growth is inexorable.

**Comment by leycec** [comment]
[**It begins.**](https://github.com/beartype/beartype/commit/b4efe5ce2c206f48ae9e06cc32134010eeedc46f) Let the blood-dimmed tide of efficient runtime type-checking flow like sweet deliverance.

**Comment by leycec** [comment]
aa23b59511b163 implements `typing.Any` support. **Up next:** `typing.Union` support. United we type! :mechanical_arm:

**Comment by leycec** [comment]
Microsoft: *you have broken the GitHub UI.* Now we're left squinting at 75% of the available screen real estate. Since the similarly awful New Reddit still exists, I'm not holding out for a reversion back to sanity. Thankfully, [Old School Github](https://addons.mozilla.org/en-US/firefox/addon/old-school-github) now exists. Undo all the bad things! `</facepalm>`

In other news, refactoring `@beartype` to even partially support PEP 484 is... *non-trivial.* We'll incrementally get there, but I'm currently rewriting the internals from procedural to object-oriented. This is because I'm a design masochist. Also, I realized it would *basically* be infeasible to support type variables (i.e., `typing.TypeVar`) under the prior procedural implementation. Objects: objects everywhere.

From the external perspective, the public API remains the same. `@beartype` is still the same sane decorator function we all know and cherish. Change brings both pain and renewed vigour. :full_moon_with_face:

**Comment by leycec** [comment]
a4c7d05 finalizes the object-oriented redesign for great glory. Onward to Golgotha and efficient `typing.Union` checking.

**Comment by leycec** [comment]
`beartype 0.2.0` is now live (and *absolutely* worky) on PyPi, much to the astonishment of weary passers-by and strange bedfellows alike:

```
pip3 install beartype
```

**Yer gonna luv it,** or your open-source enthusiasm back!

One thing you'll possibly love is that `beartype` now [fully supports `typing` unions](https://github.com/beartype/beartype#id16) while [superficially supporting most other `typing` attributes](https://github.com/beartype/beartype#id17) except [the stupidly hard stuff like generics and type variables that hopefully no one cares about for the foreseeable future](https://github.com/beartype/beartype#id18). So:

```
# This type-checks "muh_union" to be either an integer or string, as expected.
@beartype
def muh_func(muh_union: Union[int, str]) -> None: pass

# This type-checks "muh_other_union" to be either an integer, string,
# or list *WITHOUT* type-checking the items of that list to be floats.
# We're not quite there, yet. But we'll get there. Oh, how we'll get there.
@beartype
def muh_other_func(muh_other_union: Union[int, str, List[float]]) -> None: pass

# Likewise, this superficially type-checks "muh_list" to be a
# list *WITHOUT* type-checking the items of that list to be
# iterables of mappings from strings to floats. Again, we'll
# get there... sometime.
@beartype
def muh_gripping_func(muh_list: List[Iterable[Mapping[str, float]]]) -> None: pass
```

So, you can throw pretty much anything `typing`-related at `beartype` and it won't desperately cough up decoration-time exceptions anymore. *That's nice.*

Another thing you'll possibly love is that `beartype` now provides an [out-of-the-box profiling suite quantitatively timing itself against competing implementations](https://github.com/beartype/beartype#id4) – which currently just means [typeguard](https://github.com/agronholm/typeguard), because [enforce](https://github.com/RussBaz/enforce) died a few years ago and [pytypes](https://github.com/Stewori/pytypes) followed it last year. Which sucks, because now Python's runtime type-checking ecosystem has lost most of its biodiversity and is basically shambling shambolically on its last gangrenous legs. On the bright side, `beartype` is stupidly fast. Which rocks, because that was the entire point of the last three months of my life. <sup>...*precious summer, come back to me!*</sup>

Another thing you'll possibly love is that **you were right.** Do you dimly recall when we discussed the merits of various `O(1)` type-checking schemes and you proposed randomly type-checking one item from each container on each call? I don't, but you were right. I'd dismissed the idea as overly computationally expensive at the time, but... now? We're so far ahead of the performance curve that we can definitely take the negligible hit of generating pseudo-random numbers on every call. In fact, doing so has substantial benefits. Like what? Like [statistically guaranteeing `beartype` will deeply type-check *all* passed containers in `n log n` calls](https://github.com/beartype/beartype#nobody-believes-you) (assuming no changes to those containers, of course). So that's what we're going to do in `beartype 0.2.1`, where we <sup>...*okay, I*</sup> intend to implement **deep type-checking support** for at least `typing.List` and `typing.Sequence`, because those are the easiest. Gotta pluck that low-hanging fruit, bro. *That's nice, too.*

But wait, **there's more.** The last thing you'll love is that [I finally resolved this issue](https://github.com/beartype/beartype#beartype--the-bare-metal-type-checker-). *Phew!*

You have my eternal gratitude for actually expressing interest in `beartype` and continually submitting excellent ideas, demonstrable issues, and prospective solutions to this repository and elsewhere. Go, you! :hugs:

**Comment by leycec** [comment]
**Oh...** Oh, my [/r/DataIsBeautiful](https://www.reddit.com/r/dataisbeautiful) Gods. @albanie with the ultimate necrobump I shall always cherish. And congrats on landing that *h0t* CAML Lab post at Cambridge, too. Were you always that h0t? Probably. I probably forgot. It's been years. How has it been years already? How do I no longer have any hair whatsoever? These questions and more are unanswerable. :person_bald: 

Your inspiring idea to randomize @beartype type-checks across containers in `O(1)` time was **beyond correct,** @albanie. I remain indebted – yet poor, so the debt remains unpayable. No wonder you're the Cambridge guy. Praise be to wherever Cambridge is! This prophecy blossomed into a linear slope with increasing slope entirely thanks to you.

![](https://media1.tenor.com/m/MQ4Apepu6ssAAAAC/thanks-thank-you.gif)
