### ISSUE TITLE
Union with nptyping not handled properly

### ISSUE THREAD

**Issue by peske** [beartype/beartype#303]
First, thanks for your great work!

The problem I'm facing is illustrated in the following code:

```python
from typing import Optional

import numpy as np
from beartype import beartype
from nptyping import Float64, NDArray, Shape

@beartype
def fun1(arg1: NDArray[Shape["*"], Float64]) -> None:
    pass

@beartype
def fun2(arg1: NDArray[Shape["*"], Float64] | None) -> None:
    pass

@beartype
def fun3(arg1: Optional[NDArray[Shape["*"], Float64]]) -> None:
    pass

def test_fun() -> None:
    fun1(np.array([i / 2 for i in range(1, 101)], dtype=np.float64))  # <- works ok
    fun2(np.array([i / 2 for i in range(1, 101)], dtype=np.float64))  # <- fails
    fun3(np.array([i / 2 for i in range(1, 101)], dtype=np.float64))  # <- works ok
```

All three functions `fun1`, `fun2`, and `fun3` accept the same argument, except that in `fun2` and `fun3` it is optional (can be `None`). The same input argument for `fun1` and `fun3` is considered OK, while for `fun2` it fails with:

```
parameter arg="array([ 0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,
E           6. ,  6....])" violates type hint nptyping.ndarray.NDArray | None, as <protocol "numpy.ndarray"> "array([ 0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,
E           6. ,  6....])" not <class "builtins.NoneType"> or <class "nptyping.ndarray.NDArray">
```

Am I doing something wrong? Any workaround?

Thanks!

**UPDATE**: Meanwhile I've discovered that it works with `Optional` and added `fun3`, so this is a workaround. However, it would be nice to fix this bug because `| None` notation is more commonly used and suggested than `Optional` (Ruff UP007).

**Comment by leycec** [comment]
> First, thanks for your great work!

Thank *you* so much for the kind words, @peske. Serbia looks like such a fascinating and beautiful country, too. I'd love to visit someday. Who wouldn't? So much green space and florid history all over the place there! :open_mouth: 

> The problem I'm facing is illustrated in the following code:

Thanks so much for that detailed example. You are about to change your mind about both me and @beartype, because... **I can't replicate your problem.** I tried *really* hard on a late Friday night – but Python 3.10 through 3.12 all quietly accept and run your code without complaints, warnings, or exceptions.

## Let's Do Some Canada-splaining

> Canada-splaining: It's like man-splaining, *only worse*.

I have a few ideas about what might be happening here. Are you perhaps attempting to run this example:

* Under Python < 3.10? Like, under Python 3.8 *or* Python 3.9? If so, that would be your problem. Sadly, Python only supports the PEP 604-compliant `|` pipe operator that your `fun2()` function annotates its type hints with under Python ≥ 3.10. I weep. :weary: 
* With an older version of @beartype? Please ensure you've installed the most recent stable release of @beartype as of this writing: **@beartype 0.16.4.** It is good.
* With an older version of `nptyping`? Likewise, please ensure you've installed the most recent stable release of `nptyping` as of this writing: **`nptyping` 2.5.0.** It is possibly good.

Lastly, your irrational hatred of me is about to intensify. I am about to suggest another unpleasant thing that will ruin your beautiful but bitterly cold weekend in Serbia: **consider dropping `nptyping`.** Seriously. `nptyping` is [currently unmaintained and likely to die shortly](https://github.com/ramonhagenaars/nptyping). The project's last commit was nearly nine months ago.

Instead, you almost certainly want to refactor your code to leverage @patrick-kidger's [`jaxtyping`](https://github.com/google/jaxtyping). Yes, this will be work. That sucks. Yes, you will eventually thank me after shaking your fists in anger at the dismal grey sun. That's good.

Unlike `nptyping`, `jaxtyping` provides well-maintained type hints covering NumPy, JAX, PyTorch, and TensorFlow. It's pretty intense. It's also @beartype's [official FAQ recommendation for type-checking NumPy arrays](https://beartype.readthedocs.io/en/latest/faq/#numpy-arrays).

## Let's Quietly Go Home

Sadly, I can't replicate this on my end. Likewise, `nptyping` is unmaintained and possibly broken on your end. I hope you don't mind *too* much if I quietly close this issue and pretend everything is okay without doing anything.

Please reopen this if I am a raving lunatic. Thank you. Have an awesome winter in Serbia, bro! :snowboarder:

**Comment by peske** [comment]
Hey @leycec!

Thanks for your kind response!

There are several things to say, so let's start from the original problem: it is caused by my stupidity. I've used **both** `beartype_this_package` at the package level, and `@beartype` at the function level. It looks that this caused the weird behavior and my problems. (Btw. it may be a good idea to implement some kind of warning/error if other people do such a stupid thing?)

About Serbia - thanks for your kind words! Nothing special, but there are a few things to see and experience... Since you've turned out to be so friendly and helpful - I can offer you an apartment in Serbia for several weeks for free, so you're welcome to see first hand... And if you decide to come in September or October, the invitation includes visiting Corfu island, Greece (I also have apartment there). Serbia+Greece is a perfect combo if you enjoy eating :) Not to mention history and beaches of Greece...

To be completely honest, my opinion about Canada is not so good though... News that are coming from there are quite ugly. Censorship, government blocking people's banking accounts, cancel culture... Sounds more like North Korea or Belarus... Sorry for brutal honesty. But my criticism is not for the people, of course - some are very friendly and helpful ;)

When it comes to nptyping / jaxtyping - thanks for the advise! I wasn't aware about jaxtyping. I'm a newbie in Python... I will definitely give it a chance. Talking about replacing things, I would be happiest to replace the language (Python) itself. Making a dynamically typed language is probably one of the stupidest idea ever. And then trying to fix it with enormous effort with _type hints_ (that are not enforcing???), `mypy`, things like `beartype`, etc. I'm software engineer for almost 25 years, probably wrote millions of line of code, but was lucky to work with decent languages (first C# and C++, later Golang and Rust). This is my first Python project (it's a science project so...), and it's very frustrating. Irony is that scientific community is doomed with some of the ugliest languages in the world (Python and MATLAB).

My Canadian friend, enjoy your winter there, and think about options for the next summer/fall... ;) Seriously.

Semi-bitter Serbian

**Comment by peske** [comment]
After additional research, I've concluded that my problem was not caused by using both `beartype_this_package` and `@beartype` as I've said in my previous message, but with some very strange bug in `beartype`. I've opened another issue: https://github.com/beartype/beartype/issues/304
