### ISSUE TITLE
[Feature Request] Official `nptyping` support

### ISSUE THREAD

**Issue by peske** [beartype/beartype#304]
This bug is explained in the following simple project: https://github.com/peske/beartype-demo

Please take a look at README there.

**Comment by leycec** [comment]
**Wow!** You went above and beyond the call of GitHub duty here. You are the first @beartype user to create a full-fledged project just to demonstrate an issue. :open_mouth: 

I applaud this. I also applaud that you are both so nice *and* so stubborn. Stubbornness is a rare virtue. Stubbornness "gets a bad rap," as we say in English. Although stubbornness *can* be associated with detrimental personality traits (like inflexibility), stubbornness is also the only way that anything actually gets done in this world. Without stubborness, there would be *no* @beartype. There probably wouldn't be a Python, either.

I therefore applaud you. Because I applaud you, commit e5a3915c390a resolves both this and related feature request #303 for you and everyone else. Until @beartype 0.17.0 is officially released, consider upgrading to this commit via `pip` as follows:

```bash
python3 -m pip install git+https://github.com/beartype/beartype.git@e5a3915c390a71a049f408de71f8b2d628f7b8ff
```

## Who's Line Is It, Anyway?

Technically, this wasn't an issue in @beartype itself. This is an issue an `nptyping`. Allow me to tiresomely explicate.

Every time you subscript the `nptyping.NDArray` type hint factory by something (like `NDArray[Shape["N, N"], Float64]`), `nptyping.NDArray` dynamically creates and returns a **new class.** That's fine. But these classes all share the same name `"NDArray"`. That's *not* fine. These are distinct classes; they should have distinct names. Witness the badness:

```python
>>> from nptyping import Float64, NDArray, Shape
>>> foo = NDArray[Shape["N, N"], Float64]
>>> bar = NDArray[Shape["*"], Float64]

>>> foo == bar
False    # <-- this is sane
>>> foo.__name__
NDArray  # <-- this is insane
>>> bar.__name__
NDArray  # <-- still insane after all these years

>>> foo | None == bar | None
False           # <-- this is sane
>>> repr(foo | None)
NDArray | None  # <-- big yikes
>>> repr(bar | None)
NDArray | None  # <-- yikes intensifies
```

Commit e5a3915c390a relaxes @beartype to accept that sort of insanity. But even that's not the real problem. The real problem is that...

## `nptyping` Is Deader Than Dead

**`nptyping` is currently unmaintained, suffers over 20 severe issues, and emits 7 severe NumPy deprecation warnings.** In other words, `nptyping` is a ticking time bomb likely to explode your codebase into tiny fragments that are steaming and shredding your fragile keyboard. All @beartype users <sup>*...this means you, you, and you, too!*</sup> are strongly advised to immediately transition from `nptyping` to @patrick-kidger's [`jaxtyping`](https://github.com/google/jaxtyping).

Unlike `nptyping`, [`jaxtyping`](https://github.com/google/jaxtyping) provides well-maintained type hints covering NumPy, JAX, PyTorch, and TensorFlow. It's pretty intense. It's also @beartype's [official FAQ recommendation for type-checking NumPy arrays](https://beartype.readthedocs.io/en/latest/faq/#numpy-arrays).

Deprecations emitted by merely importing `nptyping` include:
    
```
/usr/lib/python3.12/site-packages/nptyping/typing_.py:51: DeprecationWarning: `np.bool8` is a deprecated alias for `np.b>
  Bool8 = np.bool8
/usr/lib/python3.12/site-packages/nptyping/typing_.py:54: DeprecationWarning: `np.object0` is a deprecated alias for ``n>
  Object0 = np.object0
/usr/lib/python3.12/site-packages/nptyping/typing_.py:66: DeprecationWarning: `np.int0` is a deprecated alias for `np.in>
  Int0 = np.int0
/usr/lib/python3.12/site-packages/nptyping/typing_.py:80: DeprecationWarning: `np.uint0` is a deprecated alias for `np.u>
  UInt0 = np.uint0
/usr/lib/python3.12/site-packages/nptyping/typing_.py:107: DeprecationWarning: `np.void0` is a deprecated alias for `np.>
  Void0 = np.void0
/usr/lib/python3.12/site-packages/nptyping/typing_.py:112: DeprecationWarning: `np.bytes0` is a deprecated alias for `np>
  Bytes0 = np.bytes0
/usr/lib/python3.12/site-packages/nptyping/typing_.py:114: DeprecationWarning: `np.str0` is a deprecated alias for `np.s>
  Str0 = np.str0
```

**Yikes.** If you simply *must* continue using `nptyping`, consider resurrecting `nptyping` by:

* Forking `nptyping`. I suggest the name `nopetyping`. :smiling_face_with_tear: 
* Fixing all of the NumPy deprecations.
* Fixing any of the [other open issues](https://github.com/ramonhagenaars/nptyping/issues) that look bad. This should be fun!
* Merging all of the [open pull requests](https://github.com/ramonhagenaars/nptyping/pulls).

Personally, I'd just switch to [`jaxtyping`](https://github.com/google/jaxtyping). But `nptyping` *is* a fascinating package. It's a shame it died. Somebody should bring it back to life. Be the code necromancer you want to see in the world. :mage_man:

**Comment by peske** [comment]
Hey @leycec!

Sorry putting so much work on you! If I knew that it's all about `nptyping` - I wouldn't do that. The bug was so weird (adding argument in one function causing problem in another) that I thought it must be somehow related to `beartype`. I've given up on `nptyping` anyway (thanks to your knowledgeable advise). `jaxtyping` works like charm for me.

I hope that changes you've made will be at least somewhat useful outside `nptyping`. If not - sorry!!! I fully agree with you that `nptyping` is dead.

Thanks!

**Comment by leycec** [comment]
**No worries whatsoever, bro.** This *was* a devilish issue – but @beartype was also sorta to blame here. The @beartype codebase should be resilient (rather than vulnerable) to third-party shenanigans like this. By highlighting this weakness in @beartype, you've levelled up our code and aided us in our honourable mission.

Thanks so much for that fun little logic puzzle, too. That captivated me for a few hours. That's all I ask from life anymore. Gods, grant me captivating puzzles until I am too old to hammer on a keyboard! :jigsaw: :older_adult: :jigsaw:
