### ISSUE TITLE
Is there a way to override `beartype_this_package()` for specific functions/classes?

### ISSUE THREAD

**Issue by sunildkumar** [beartype/beartype#305]
I'm trying to add `beartype` to a package in my codebase. While a large majority of functions should be `beartype`d, there are a few that unfortunately should not be. Is there a way to disable `beartype` for a specific function/class when using `beartype_this_package()` ? It seems like the alternative is to manually decorate each function/class in the package, which is unbearable. 

Thanks for you help!

**Comment by leycec** [comment]
**Absolutely.** @beartype got you covered. Please see [this official FAQ entry that will answer all your questions](https://beartype.readthedocs.io/en/latest/faq/#how-do-i-not-type-check-something), including the inevitable question that even I still ask myself at 2AM on Friday: "Why is 42 always the answer? Just, why?" The **tl;dr** is:

```python
# Import the requisite machinery.
from beartype import beartype, BeartypeConf, BeartypeStrategy

# Dynamically create a new @nobeartype decorator disabling type-checking.
nobeartype = beartype(conf=BeartypeConf(strategy=BeartypeStrategy.O0))

# Avoid type-checking *ANY* methods or attributes of this class.
@nobeartype
class UncheckedDangerClassIsDangerous(object):
    # This method raises *NO* type-checking violation despite returning a
    # non-"None" value.
    def unchecked_danger_method_is_dangerous(self) -> None:
        return 'This string is not "None". Sadly, nobody cares anymore.'
```

This is probably the best approach, because it still allows pure static type-checkers like mypy and `pyright` to type-check those classes and callables. If you truly *do* want to prevent every type-checker from type-checking those classes and callables, prefer the standard `@typing.no_type_check` decorator. Usually, you shouldn't do that. But you can. Complicated topic is complicated.

Thanks so much for asking. More importantly, thanks so much for adding `beartype` to literally everything that exists! And please do reopen this if you still have soul-searching questions. Asian takeout box emoji for the win. :takeout_box:
