### ISSUE TITLE
beartype.claw complains about SQLAlchemy string class

### ISSUE THREAD

**Issue by kasium** [beartype/beartype#308]
Using sqlalchemy's string class leads to a weird warning

Files:
**package.\_\_init\_\_**
```py
"""Some package"""
from __future__ import annotations
from beartype.claw import beartype_package
beartype_package("package")
```

**package.foo**
```py
from sqlalchemy import String
class X:
    type = String
```

Executing `python -c "import package.foo"` now leads to this warning:
```
/root/git/beartype/venv/lib/python3.11/site-packages/beartype/_decor/decorcore.py:256: BeartypeClawDecorWarning: Method sqlalchemy.sql.sqltypes.String.__init__() in file "/root/git/beartype/venv/lib/python3.11/site-packages/sqlalchemy/sql/sqltypes.py" line 184:
Callable name "String.__init__" contains only 1 parent lexical scope(s) but "func_scope_names_ignore" parameter ignores 2 parent lexical scope(s), leaving -1 parent lexical scope(s) to be searched for String.__init__() locals.
  warn(warning_message, warning_category)
```

I mean, like what? I don't get what this warning should tell me and what I should do now. Even if this warning is legit, please improve it :-)

Environment
* beartype: 0.16.4
* pyhton 3.11.0
* sqlalchemy: 2.0.23

**Comment by leycec** [comment]
**...heh.** Thankfully, what you should do now is exactly what you did do: **report this to us, because nothing makes sense.** Right? You did great. Thanks so much for the heads up. Lucky for you and everybody else, I *just* resolved this exact issue two nights ago with commit 9faf1ecfc0fc. This is why we party tonight. :partying_face: 

@beartype doesn't *usually* raise unreadable nonsense like that. This is a sorta obscure edge case that only arises when you define a class variable with an initial value that is another class. The exception message is actually perfect, because **(A)** nobody except me is ever supposed to see stuff like that and **(B)** when other people see stuff like that they panic and submit an issue.

**So.** You have three attractive choices here:

1. **Choice 1:** *Just wait.* Okay. That's *not* that attractive. But it works. I hope to publish @beartype 0.17.0 next week with resolutions for both this and your other #307. Viva la laziness.
2. **Choice 2:** Embrace the hype and update to @beartype's newest `git` commit. Since all tests pass, I guarantee joy. `pip` even supports doing this out-of-the-box. Viva la `pip`:

```bash
pip install git+https://github.com/beartype/beartype.git@ff986d4a012b43b3617a565b3c71c682d2d69bc5
```

3. **Choice 3:** Hack around this on your end *without* updating to @beartype's newest `git` commit. Notably, transform the above example to resemble:

```python
from sqlalchemy import String
class X:
    pass

X.type = String  # <-- This is dumb. This. Is. @beartype.
```

In theory, that should work. @beartype should no longer complain. It's best not to ask why. That way leads to the Dark Side. :new_moon_with_face:

**Comment by kasium** [comment]
Also here, thanks for the fast fix. Regarding the `type` field: I'm aware that this is not great, but SQLAlchemy has some cases where class variables are named `type`

**Comment by leycec** [comment]
You're most welcome. And...

> Regarding the `type` field: I'm aware that this is not great, but SQLAlchemy has some cases where class variables are named `type`

**Fascinating...** and horrifying! I thought that might be the case, but it's been *years* since I SQLAlchemied. It's NoSQL or bust for @leycec and friends.

Have a great weekend in Germany. May your weather be better than Canada's. That's pretty much guaranteed – but you never know. :snowman:
