### ISSUE TITLE
LRUDuffleCacheStrong

### ISSUE THREAD

**Issue by Heliotrop3** [beartype/beartype#31]
Extracted from `_pephint.py`

>FIXME: *WOOPS.* The "LRUCacheStrong" (LRUCache) class is absolutely awesome and we'll absolutely be reusing that for various supplementary purposes across the codebase (e.g., for perfect O(1) tuple type-checking below). However, this class sadly doesn't get us where we need to be for full O(1) dictionary and set type-checking. Why? Two main reasons:
>* *ITERATIVE ACCESS.*
    - Our routinely scheduled cleanup function needs to iteratively or randomly access arbitrary cache items for inspection to decide whether they need to be [garbage collected].
>* *VARIABLE OBJECT SIZES.* 
    - We gradually realized, given the plethora of related "FIXME:" comments below, that we'll eventually want to cache a variety of possible types of objects across different caches -- each cache caching a unique type of object. This makes less and less sense the more one considers, however. For example, why have a LRU cache of default size 256 specific to iterators for a downstream consumer that only passes one iterator to a single @beartype-decorated callable?
>
>The solution to both is simple, but not: we define a new derivative "LRUDuffleCacheStrong" (LRUDuffle) class. The motivation for using the term "duffle" is - like a duffle bag - the duffle cache:
>    * Provides random access.
>    * Elegantly stretches to contains a variable number of arbitrary objects of variable size.
>
>The "LRUDuffle" class satisfies both concerns by caching to a maximum *OBJECT SIZE CAPACITY* rather than merely to an *OBJECT NUMBER CAPACITY.* Whereas the "LRUCache" class treats all cached objects as having a uniform size of 1, the "LRUDuffle" class instead assigns each cached object an estimated abstract size (EAS) as a strictly positive integer intended to reflect its actual transitive in-memory size -- where a cached object of EAS 1 is likely to be the smallest object in that cache.

# Analysis

Notably, there's a lot of information spread throughout `_pephint.py` on this topic. So 🐻 with me while I do my best to summarize.

### Random Access
> - Our routinely scheduled cleanup function needs to iteratively or randomly access arbitrary cache items for inspection to decide whether they need to be [garbage collected]

Note: Commentary on why strong references are cached rather than weak references and randomly accessing arbitrary cached items can be found in `utilcachelru.py` and `_pephint.py`; The diluted background information is caching strong references is unavoidably bad which creates the need to address memory leaks by culling objects whose only strong referent is in our cache (cache-only objects). 
<br>

LRUCache subclasses but doesn't introduce any new methods to the builtin dict. Rather the atomic operations underlying the builtin dict's API - `__getitem__`, `__setitem__`, `__contains__` - are overridden to enforce thread-safe LRU caching behavior. Therefore, the issue should be generalized to convey its intrinsic to the builtin dict rather than a quirk of LRUCache.

Psuedo-randomly selecting a key from `dict.keys()` will involve using the `random` library. One option is using `random.choice` however this requires converting `dict.keys()` into a sequence type. This can be done trivially, idiomatically and relatively efficiently although requires converting the view object into a list : 
```
def get_rand_key(self):
    return random.choice([k for k in dict.keys()])
```

Alternatively, we could spin up a dict mapping some id able to be arbitrarily selected in O(1) to a key in the LRU cache. My initial thoughts centered around indexing entries in a lookup table based on current length of the LRU cache.
```
lru = {}
lookup_tbl = {}

lru["roar"]  = bear
lookup_tbl[1] = "roar"

lru["yum"]  = salmon
lookup_tbl[2] = "yum"

...

lru[key] = val
lookup_tbl[len(lru)+1] = key
```

 Theoretically this enables random selection to occur by generating an integer in the inclusive range of 1 and the cache length then grabbing the corresponding value in the lookup table. Notably, this design sucks :goberserk: . Specifically, it encounters non-trivial problems related to handling index gaps created after deleting an item. 
```
# Index -> lru_key -> lru_val
# 1 -> "roar" -> bear
# 2 -> "yum" -> salmon
# 3 -> "protect" -> cubs
# 4 -> "fight" -> wolves

del lru["roar"]
del lookup_tbl[1]

del lru["yum"]
del lookup_tbl[2]

# 3 -> "protect" -> cubs
# 4 -> "fight" -> wolves

# Generate a number in the range [1,2]  - Never generates a valid number
rand_num = random.randint(1, len(LRU))
```
Correcting those gaps requires iterating over not one but two dictionaries. Likewise to avoid collisions we'd need to recycle the indices upon release. This would probably involve a FIFO queue which present yet another issue. Storing the unused indices doesn't mean we can tell random to exclude them from its range. There's probably a workaround with random.choice(...) and lists but if you recall, we've wound up at a very similar solution as before but with extra steps and more headache.

** NOTE: I need to think more on the double hash method described above.

If indexing can't be avoided - which I'm pretty sure it can't - then I propose taking the following route:
```
def get_rand_key(self):
    rand_num = random.randint(0, len(self))
    for idx, key in enumerate(self.keys()):
        if idx == rand_num:
            return key
```
Best case is O(1), worst case is O(n). We save memory by working with the items view rather than a cloned temp list. If we wanted to take this a step further, we could convert the returned view into a generator by encasing it in parens.

### Cleanup Function
Do we have a cleanup function or is this a black box to be implemented at a later time? Regardless, the purpose of strong references is to persist the object *because* it would otherwise get immediately garbage collected. Thus, whether we iteratively or arbitrarily check cached items, a choice should be made whether this cleanup function should consider length of time cached.

## Variable Object Sizes
> - We gradually realized, given the plethora of related "FIXME:" comments below, that we'll eventually want to cache a variety of possible types of objects across different caches -- each cache caching a unique type of object. This makes less and less sense the more one considers, however. 

@leycec, I'm not clear as to why having dedicated caches for each type is a boon rather than a burden. Specifically, what are the drawback of using one cache for all types? Will each and every type have their own cache? How will non-builtin types such as numpy be handled?

### Provided Example
> - For example, why have a LRU cache of default size 256 specific to iterators for a downstream consumer that only passes one iterator to a single @beartype-decorated callable?

Technically, the LRUCache doesn't have a default size. Yes, it enforces LRU caching behavior and yes it has an upper bound. In application, LRUCache is nothing more than a builtin dict with a few tweaked dunders. One of which - `__setitem__` - is responsible for ensuring the count of items doesn't exceed the upper bound. Thus, LRUCache will only ever be as large as the number of items cached but no larger than the upper bound. Ergo, I'm not seeing the difference between a LRUCache holding one item with an upper bound of 256 versus a LRUCache with an upper bound of 1 other than potential capacity. 

Barring a misunderstanding,  the only difference between the caches is their upper bound criteria. Are we absolutely certain the concept of LRUDuffle - defining an upper bound based on cumulative size of objects - can't/shouldn't be incorporated into LRUCache?

**Comment by leycec** [comment]
**Wow.** I... didn't expect such a thorough and phenomenal workup. I mean, I *should* have expected that. It's @Heliotrop3, the GitHub Wonder. You stun and impress, as always.

> Notably, there's a lot of information spread throughout _pephint.py on this topic. So :bear: with me while I do my best to summarize.

**Ugh!** Sorry about that. The LRUDuffle concept inextricably ties itself into the guts of our core code generation algorithm. I could and should have done a more readable job there, but it was late and I'm painfully lazy. It hurts!

> ...caching strong references is unavoidably bad which creates the need to address memory leaks by culling objects whose only strong referent is in our cache (cache-only objects).

*Nailed it in one.*

> One option is using `random.choice` however this requires converting `dict.keys()` into a sequence type.

This is me choking on my own sputum. Tragically, *most* of the `random` module is inappropriate for our needs **because it's so slow it burns my eyes out of their sockets.** I need my eyes, Tyler.

Of course, coercing `dict.keys()` into a sequence just compounds matters, because that's an `O(n)` operation for `n` the cache size, which is strictly verboten, because otherwise we'd be lying when we say `beartype` is `O(1)`. Let's not lie to the people who like us, Tyler.

> Alternatively, we could spin up a `dict` mapping some id able to be arbitrarily selected in `O(1)` to a key in the LRU cache.

Yes! Yes! `O(1)` is the way.

But... I'm out of time for `beartype` today! No! No! I'll try to give my thoughts on the rest of your incisive exegesis in a day or two. Thanks again for all the intrepid explorations. You rock the open-source Casbah, as always. :guitar: :musical_note:

**Comment by leycec** [comment]
**Back in the :bear: saddle.** I'm currently sick, ideally with something that is not melting my lungs into a thin viscous smear of scar tissue and haemorrhagic inflammation.

If I wake up from a medically induced coma in nine months during which time pacifist vegan aliens from Proxima Centauri B have finally landed at [Parliament Hill in Ottawa](https://twitter.com/ExploreCanada/status/540566623967801345), break this to me gently.

> Therefore, the issue should be generalized to convey its intrinsic to...

This may be the smartest thing anyone has ever said in my vicinity.

> Psuedo-randomly selecting a key from `dict.keys()` will involve using the `random` library.

:vomiting_face: 

> Specifically, it [*this design*] encounters non-trivial problems related to handling index gaps created after deleting an item.

:vomiting_face: :vomiting_face: 

> Correcting those gaps requires iterating over not one but two dictionaries. Likewise to avoid collisions we'd need to recycle the indices upon release. This would probably involve a FIFO queue which present yet another issue. Storing the unused indices doesn't mean we can tell `random` to exclude them from its range. There's probably a workaround with `random.choice(...)` and lists but if you recall, we've wound up at a very similar solution as before but with extra steps and more headache.

:vomiting_face: :vomiting_face: :vomiting_face: :vomiting_face: 

> Best case is O(1), worst case is O(n). We save memory by working with the items view rather than a cloned temp list. If we wanted to take this a step further, we could convert the returned view into a generator by encasing it in parens.

:vomiting_face: :vomiting_face: :vomiting_face: :vomiting_face: :vomiting_face: :vomiting_face: :vomiting_face: :vomiting_face: 

The intrinsic horrors of your commentary have made me remember why subsequent and mostly undocumented revisions to the `LRUDuffleCacheStrong` design **dropped random access.**

The first-draft design supported random access, just 'cause. Then I realized that is a *[Bloodborne](https://www.youtube.com/watch?v=VJyc-sD1DiY)*-esque nightmare we would never awaken from. If we *really* want random access to cached items, which we don't because I am sick and thus choking on my own sputum whilst you are preoccupied elsewhere with maintaining your juggernaut of an intellect, the correct solution is probably to coopt a third-party solution compatible with our MIT license such as:

* [`randomdict.RandomDict`](https://github.com/robtandy/randomdict), unlicensed <sup>*hurk!*</sup>, pure Python, and with hard `O(1)` guarantees. The cost is increased space consumption, so let's *not* do this unless we decide we must, which we won't.

The second-draft design dropped random access in favour of maintaining a private `LRUDuffleCacheStrong._iter` iterator over `self.items()`:

```
#  * "_iter", an iterator over this dictionary. Yes, we *COULD* implement
#    random access (e.g., with a linked list or list), but doing so introduces
#    extreme complications and inefficiencies in both space and time. Instead,
#    persisting a simple iterator over this dictionary suffices.
```

That iterator then gives us `O(1)` access to all cached objects with *no* additional space or time costs **in order of the least to most recently used objects.** If you consider the forest rather than the trees view, that's exactly what we want! Right?

What we ultimately want here is to eject stale strong references to cached objects (i.e., objects whose only remaining references are from our cache). But those are likely to be the least recently used objects! Ergo, iterating cached objects from least to most recently used is likelier to yield stale strong references than the comparable approach that randomly accesses those objects. Right?

...*maybe.* Let's just say that it will, because doing so yields a sane, efficient, and comprehensible solution. We'll take it.

> Do we have a cleanup function or is this a black box to be implemented at a later time?

We... need that.

En route to our clean and hygeinic utopia where nobody notices we are secretly storing strong references to all their dictionaries and sets, consider this utility tester detecting stale strong references to arbitrary dictionary objects:

```
from sys import getrefcount

def is_cached_mapping_nearly_dead(mapping: Mapping) -> bool:
    '''
    ``True`` only if there only exists one external strong reference to
    the passed mapping internally cached by the :mod:`beartype.beartype`
    decorator.
    '''

    # Note that the integer returned by this getter is intentionally *NOT*
    # tested for equality with "1". Why? Because ignorable strong
    # references to this mapping include:
    # * The "mapping" parameter passed to this tester.
    # * The "mapping" parameter passed to the getrefcount() getter.
    # * This mapping cached by the beartype-specific global container
    #   caching these mappings.
    # * The iterator over this mapping cached by the same container.
    return getrefcount(mapping) <= 5   # <--- yikes!
```

That's defined as a function for descriptive purposes. We could and should just inline that wherever needed. Onward to Utopia!

Next, consider this prospective `LRUDuffleCacheStrong` method returning the next most recently used cached `FixedList`, which we drunkenly babble about below: 

```
class LRUDuffleCacheStrong(dict):
    ...
    def get_pair_next_or_none(
        self,
        __dict_len = dict.__len__,
    ) -> Optional[Tuple[Hashable, FixedList]]:
        '''
        Next most recently used key-value pair of this cache if this cache
        is non-empty *or* ``None`` otherwise (i.e., if this cache is empty).

        The first call to this method returns the least recently used
        key-value pair of this cache. Each successive call returns the next
        least recently used key-value pair of this cache until finally
        returning the most recently used key-value pair of this cache, at
        which time the call following that call rewinds time by again
        returning the least recently used key-value pair of this cache.
        '''

        #FIXME: Probably nest this in a "with self._thread_lock:" block.

        # If this cache is empty, return None.
        if not __dict_len(self):
            return None
        # Else, this cache is non-empty.

        # Attempt to...
        try:
            # Return the next recent key-value pair of this cache.
            return self._iter.__next__()
        # If doing so raises *ANY* exception, this iterator has become
        # desynchronized from this cache. In this case...
        #
        # Note this implicitly handles the initial edge case in which this
        # cache has yet to be iterated (i.e., "self._iter == None"). Since
        # this is *ONLY* the case for the first call to this method for the
        # entire lifetime of the active Python process, the negligible
        # overhead of handling this exception is preferable to violating DRY
        # by duplicating this logic with an explicit
        # "if self._iter == None:" block.
        except:
            # Reinitialize this iterator.
            self._iter = self.items()

            # Return the least recent such pair.
            return self._iter.__next__()
```

Let us now debate the merits of `FixedList`, for they are good and just and bring strength to the herd. To reduce space and time consumption, each value mapped to a key in `LRUDuffleCacheStrong` is a `FixedList` of length ≥ 3 persisting metadata on the underlying object being cached.

For each cached dictionary and set, this is a `FixedList` of length 4 such that:

0. Index 0 of this list is an **arbitrary object identifying the kind of cached object.** For simplicity, this can just be a class – namely, either:
  * `dict` for cached dictionaries.
  * `set` for cached sets.
1. Index 1 of this list is the **strong reference to an iterator** over that dictionary or set. This is the primary object being cached.
2. Index 2 of this list is the **estimated abstract size (EAS)** of that dictionary or set. This is an integer ≥ 1 encapsulating how large in the abstract we expect that dictionary or set to be. See `sizeable_bigo_size` in `_pephint` for further ancient wisdom that is almost certainly broken.
3. Index 3 of this list is a **weak reference to that dictionary or set** being iterated over. Since we're already effectively maintaining a strong reference to that dictionary or set through the above iterator, it doesn't *particularly* matter whether this is a weak or strong reference. For sanity, it's still probably best to reduce the number of strong references we persist to user-defined objects. In any case, this enables us to lookup the number of existing strong references to that dictionary or set in the `is_cached_mapping_nearly_dead()` function called during cleanup.

Lastly, we then just need the final piece of the puzzle – a `cleanup_beartype()` function that runs in `O(1)` by ruthlessly exploiting the above callables and data structures: e.g.,

```
from itertools import count

_DUFFLE_CACHE = LRUDuffleCacheStrong()
'''
Thread-safe global duffle cache of arbitrary objects.
'''

_duffle_cache_value_index_counter = count(start=0, step=1)
_DUFFLE_CACHE_VALUE_INDEX_TYPE = next(_duffle_cache_value_index_counter)
'''
0-based index of the type of each cached object described by a
:class:`FixedList` value of :data:`_DUFFLE_CACHE`.
'''

_DUFFLE_CACHE_VALUE_INDEX_REF = next(_duffle_cache_value_index_counter)
'''
0-based index of the strong reference to each cached object described by a
:class:`FixedList` value of :data:`_DUFFLE_CACHE`.
'''

_DUFFLE_CACHE_VALUE_INDEX_EAS = next(_duffle_cache_value_index_counter)
'''
0-based index of the estimated abstract size (EAS) of each cached object
described by a :class:`FixedList` value of :data:`_DUFFLE_CACHE`.
'''

_DUFFLE_CACHE_VALUE_INDEX_OBJ = next(_duffle_cache_value_index_counter)
'''
0-based index of a weak reference to an underlying object (e.g., dictionary,
set) associated with each cached object described by a :class:`FixedList` value
of :data:`_DUFFLE_CACHE`.
'''

def cleanup_beartype() -> None:

    cached_pair_next = _DUFFLE_CACHE.get_pair_next_or_none()

    if cached_pair_next is None:
        return

    cached_key, cached_value = *cached_pair_next

    if (
        cached_value[_DUFFLE_CACHE_VALUE_INDEX_TYPE] is dict and
        is_cached_mapping_nearly_dead(
            cached_value[_DUFFLE_CACHE_VALUE_INDEX_OBJ])
    ):
        _DUFFLE_CACHE.uncache_object(cached_key, cached_value)
```

Admittedly, the `LRUDuffleCacheStrong.uncache_object()` method has yet to be defined. Thankfully, that seems trivial:

```
class LRUDuffleCacheStrong(dict):
    ...
    def uncache_object(self, key: Hashable, value: FixedList) -> None:
        assert len(value) > _DUFFLE_CACHE_VALUE_INDEX_EAS
        self._eas -= value[_DUFFLE_CACHE_VALUE_INDEX_EAS]
        del self[key]
```

We then carefully wire that up to the `gc.callbacks` list of callbacks called on every garbage collection run. What could be more trivial, Tyler? :vomiting_face: 

> Regardless, the purpose of strong references is to persist the object because it would otherwise get immediately garbage collected. Thus, whether we iteratively or arbitrarily check cached items, a choice should be made whether this cleanup function should consider length of time cached.

**Right.** Theoretically, the above approach *should* already implicitly take that into account by virtue of iteration (and thus cleanup) from least- to most-recently cached objects. Let's accept that at face value and pat ourselves on the back in a self-congratulatory manner.

> @leycec, I'm not clear as to why having dedicated caches for each type is a boon rather than a burden. Specifically, what are the drawback of using one cache for all types? Will each and every type have their own cache? How will non-builtin types such as numpy be handled?

**"Urgh!"** My abysmal documentation unintended for human eyes has failed us again. Indeed, as you suspect:

* *We absolutely want just one cache for all types.* This cache is, of course, `_DUFFLE_CACHE` in the above cleanup pseudo-code. One cache to rule them all and in the darkness of our poorly tested code bind them. :ring: 
* Since we absolutely want just one cache for all types, *we probably won't even need* `LRUCacheStrong` anymore. Right? Let's just globally rename `LRUCacheStrong` to `LRUDuffleCacheStrong` and then gradually begin building out `LRUDuffleCacheStrong` into something that sorta resembles the above if [we squint at it like Fry](https://knowyourmeme.com/memes/futurama-fry-not-sure-if).
* Non-builtin types such as NumPy arrays... *should probably never be cached!* After all, non-builtin types should typically be typed by callers as those specific types rather than `collections.abc` generics: e.g.,

```
from beartype import beartype
from numpy import ndarray

@beartype
def accept_all_my_love(array: ndarray) -> ndarray:
    return array
```

`numpy.ndarray` is just a standard class, so that won't trigger any of the code paths ultimately leading to the anarchic depravity that is `_DUFFLE_CACHE`. Those paths should *only* be triggered by callable parameters or returns typed as dictionaries or sets: e.g.,

```
from beartype import beartype
from collections.abc import MutableMapping, Set

@beartype
def accept_all_my_vole(dict: MutableMapping[str, float]) -> Set[float]:
    return set(dict.values())
```

But let's not worry about that last iota for now. Squinty Fry compels us.

![By Lord Britain!](https://i.kym-cdn.com/photos/images/newsfeed/000/131/345/3000.jpg?1307463539)

**Comment by leycec** [comment]
**Ugh!** I feels terribad, @Heliotrop3. I inundated us all with a graffitied wall of slap-happy gibberish and then failed to code anything. Well, I coded *something*: Python 3.10 support, which is great, but has nothing to do with duffles or caches, which is not so great.

I miss you around here, Tyler. But I also acknowledge that real-world bad stuff might have gone down for you and that no one can remunerate you for the hard work you do here, because I am impoverished and voluntarily live in a cabin with cats. I wish you the Turing-complete best on all your future endeavours. You are awesome and I hope things get better! :hugs: 

We'll just leave this issue up as a memento to your public greatness.

**Comment by leycec** [comment]
**Ugh!** I feel simply deplorable for belatedly closing this but a month later, but... ain't nobody got the volunteer spirit here. Let's revisit this when one or both of us get paid voluminous [Money Bags of Holding +1](https://roll20.net/compendium/dnd5e/Bag%20of%20Holding#content).

You will also be remembered as a barbarian code hero riding a bear, @Heliotrop3. May the Goddess bless your IDE with eternal flow control.
