### ISSUE TITLE
[Feature Request] Check `typing.Protocol` Annotation Types

### ISSUE THREAD

**Issue by dcharatan** [beartype/beartype#323]
# The Problem

Currently, beartype checks `typing.Protocol` keys, but not the corresponding types:

```
from dataclasses import dataclass
from typing import Protocol, runtime_checkable

from beartype.door import is_bearable


@dataclass
class Example:
    x: str


@runtime_checkable
class WrongName(Protocol):
    wrong_name: str


@runtime_checkable
class WrongType(Protocol):
    x: int


if __name__ == "__main__":
    example = Example("triceratops")

    print(is_bearable(example, WrongName))  # False, should be False
    print(is_bearable(example, WrongType))  # True, should be False (?)
```

Ideally, the second call to `is_bearable` would return `False`, since `"triceratops"` is not an `int`.

# A Potential Workaround (?)

For now, a hacky way to circumvent this is to use a metaclass with `__instancecheck__`:

```
import inspect
from dataclasses import dataclass
from typing import Any

from beartype.door import is_bearable


@dataclass
class Example:
    x: str


class HackMeta(type):
    def __instancecheck__(self, instance: Any) -> bool:
        for key, value in inspect.get_annotations(self).items():
            # Check if the key is missing.
            if not hasattr(instance, key):
                return False

            # Check if the type is wrong.
            if not isinstance(getattr(instance, key), value):
                return False

        return True


class Hack(metaclass=HackMeta):
    x: int


if __name__ == "__main__":
    print(is_bearable(Example("triceratops"), Hack))  # False, should be False
    print(is_bearable(Example(1), Hack))  # True, should be True
```

This feels wrong though... Are there any plans to make `beartype` check both the keys and values/types for `typing.Protocol` annotations?

**Comment by posita** [comment]
I will defer to @leycec to respond directly, of course, but it may help to know that runtime checking of Protcol attributes is already lacking in core Python. More specifically, calling `isinstance(obj, MyProtocol)` probably isn't nearly as thorough as we'd assume or like it to be. (Which means if this problem is to be solved, it's probably going to be a real bear. :smirk:)

`typing.Protocol` currently derives from something called `_ProtocolMeta`, which Python devs have signaled some desire to retire, but it apparently does not want to go gentle into that good night. You can see [its `__instancecheck__` implementation at `Lib/typing.py#L1885-L1916`](https://github.com/python/cpython/blob/95ebd45613d6bf0a8b76778454f1d413d54209db/Lib/typing.py#L1885-L1916). In short, it basically suffers from the same issue that you raise, namely that it merely checks for the presence of attributes, not their types.

Beartype provides an override `Protocol` that does little else other than cache runtime instance checks for performance reasons, although the implementation is a beast.<sup>1</sup> See: https://github.com/beartype/beartype/blob/3a5b216c78034359d2c634307440adb04ffe5a39/beartype/typing/_typingpep544.py#L117-L388

If you wanted to experiment with your approach, you might consider tinkering with that? It would require you to derive your protocols from `beartype.typing.Protocol`, though.

Possibly related: #184, #237

---
<sup>1</sup> Whoever wrote that pile ought to consider a career in either the food service or housekeeping industries.

As an aside, Python _**kind of**_ does something crudely similar, but limited to ABCMeta classes in [`Lib/_py_abc.py#L92-L106`](https://github.com/python/cpython/blob/95ebd45613d6bf0a8b76778454f1d413d54209db/Lib/_py_abc.py#L92-L106). That may seem like a _non sequitur_, but note that `ABCMeta.__isinstance__` is called from `_ProtocolMeta.__instancecheck__` (masquerading as `_abc_instancecheck`) where the proprietary/internal `_is_protocol` attribute is missing, but it's unclear when this code path applies. (To say Python's typing code is spaghetti-esque is to insult spaghetti, I think.)

**Comment by leycec** [comment]
Oh, @posita. You sweet summer bear. I'd hug you, but I live in a wasteland of ice surrounded by man-eating predators with a taste for high IQ. Instead, I'll just restate everything @posita said while pretending I'm adding something of value to the conversation. My ego is fragile.

## `typing.Protocol`: It Pretty Much Sucks, Bro.

[PEP 544](https://peps.python.org/pep-0544) standardized `typing.Protocol`. PEP 544 doesn't do much. Therefore, `typing.Protocol` doesn't do much either. Sucks, huh? We know. We feel that searing pain in our intestines, too.

Specifically, `typing.Protocol` only checks that **methods of the same names exist.** That's it. Srsly. That's all `typing.Protocol` does. Things that `typing.Protocol` does *not* do include:

* Everything else.
* Everything that you want to do, @dcharatan.
* Anything involving type hints.
* Anything involving method signatures, including:
  * Method parameter names.
  * Method parameter order.
  * Method parameter types (e.g., keyword-only, positional-only, variadic positional, variadic keyword).
  * Calling convention (e.g., `async` versus non-`async`, generator versus non-generator).

Sadly, @beartype is standards-based. Sucks, huh? Usually, being standards-based is *good.* But when the standards suck, so too does @beartype.

Thankfully, you've already gone this far. You're already poised on the precipice of madness. If you'd like to go a bit further, <sup>*do it do it* no peer pressure or anything</sup> proposing this to [CPython's official `typing` special interest group (SIG)](https://discuss.python.org/c/typing/32) is **absolutely the best way to make this happen for everybody.** Everybody includes @beartype.

But don't worry! You don't need to actually *do* anything extreme like author a PEP or *whatevahs.* Just briefly propose the idea and suggest that, as a prehistoric aquatic dinosaur studying at MIT, your work resurrecting Megalodon from its ancient watery grave as humanity's newest reason to never go scuba-diving vitally depends on `typing.Protocol` doing something useful with its life for once.

*Thus spake Bearthustra.* Oh, and...

## You Probably Already Know This, But...

```python
class HackMeta(type):
    def __instancecheck__(self, instance: Any) -> bool:
        for key, value in inspect.get_annotations(self).items():
            # Check if the key is missing.
            if not hasattr(instance, key):
                return False

            # Check if the type is wrong.
            #FIXME: isinstance() fails to support most type hints. So,
            #you probably instead want to do this. All hail West Texas.  # <-- wut
            if not is_bearable(getattr(instance, key), value):  # <-- totally works, in general
            #if not isinstance(getattr(instance, key), value):  # <-- totally doesn't work, in general
                return False

        return True
```

``\o/``

**Comment by leycec** [comment]
**This issue deeply saddens me.** I :heart_eyes_cat: Megalodon and would :heart_eyes_cat: to make this happen for everybody. But this has yet to be standardized. Our paws are tied. Somebody who is not me, please standardize this for everybody.

Until then, with many apologies, I quietly close this. Our issue tracker is exploding. Desperate times call for desperation. :face_with_head_bandage:

**Comment by dcharatan** [comment]
Thank you @leycec and @posita for the detailed responses and the tip on using `is_bearable`!
