### ISSUE TITLE
Exception raised despite consistent `repr` output 

### ISSUE THREAD

**Issue by spagdoon0411** [beartype/beartype#334]
I'm new to Beartype with NumPy typing, but I don't think Beartype should be raising this exception. Here's the Python file. (Specifically, the issue seems to be the return type hint for the `load_into_numpy` function (`NDArray[Shape["*"], Float]`); removing it causes the exception to go away.)

```python3
from librosa import load
import numpy as np
import nptyping as npt
from nptyping import NDArray, Shape, Float
from typing import Any
from beartype import beartype


class SpectUtils:

    @beartype
    # Loads a single audio file into a floating-point Numpy "time series" vector. 
    def load_into_numpy(self, path : str, sample_rate : float) -> NDArray[Shape["*"], Float]:
        audio_arr : NDArray[Shape["*"], npt.Float] 
        returned_sample_rate : float
        audio_arr, returned_sample_rate = load(path=path, sr=sample_rate)

        return audio_arr


s = SpectUtils()
audionp: NDArray[Shape["*"], Float] = s.load_into_numpy(path="./example_file.wav" , sample_rate=2250.0)
print(audionp.shape)
```

Here's the resulting exception: 

```
beartype.roar.BeartypeDecorHintPep604Exception: Type hint NDArray[Shape['*'], Float] inconsistent with respect to repr() strings. Since @beartype requires consistency between type hints and repr() strings, this hint is unsupported by @beartype. Consider reporting this issue to the third-party developer implementing this hint: e.g.,
    >>> repr(NDArray[Shape['*'], Float])
    NDArray[Shape['*'], Float]  # <-- this is fine
    >>> repr(NDArray[Shape['*'], Float] | int)
    nptyping.ndarray.NDArray | int  # <-- *THIS IS REALLY SUPER BAD*

    # Ideally, that output should instead resemble:
    >>> repr(NDArray[Shape['*'], Float] | int)
    NDArray[Shape['*'], Float] | int  # <-- what @beartype wants!
```

I get similar exceptions when I replace that problematic type hint with `NDArray` or `NDArray[Any, Any]`

...but when I check what `repr` prints for `NDArray[Shape["*"], Float]`, I get:

```python3
>>> from nptyping import NDArray, Shape, Float
>>> repr(NDArray[Shape["*"], Float])
"NDArray[Shape['*'], Float]"
```

...which totally seems consistent with the format Beartype asks for. Am I missing something?

Here's the whole Traceback:

```
Traceback (most recent call last):
  File "/Users/spandansuthar/Projects/project487/spectrogram_utils.py", line 9, in <module>
    class SpectUtils:
  File "/Users/spandansuthar/Projects/project487/spectrogram_utils.py", line 12, in SpectUtils
    @beartype
     ^^^^^^^^
  File "/Users/spandansuthar/.julia/conda/3/aarch64/envs/project487/lib/python3.11/site-packages/beartype/_decor/decorcache.py", line 77, in beartype
    return beartype_object(obj, conf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spandansuthar/.julia/conda/3/aarch64/envs/project487/lib/python3.11/site-packages/beartype/_decor/decorcore.py", line 83, in beartype_object
    _beartype_object_fatal(obj, conf=conf, **kwargs)
  File "/Users/spandansuthar/.julia/conda/3/aarch64/envs/project487/lib/python3.11/site-packages/beartype/_decor/decorcore.py", line 132, in _beartype_object_fatal
    beartype_nontype(obj, **kwargs)  # type: ignore[return-value]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spandansuthar/.julia/conda/3/aarch64/envs/project487/lib/python3.11/site-packages/beartype/_decor/_decornontype.py", line 177, in beartype_nontype
    return beartype_func(obj, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spandansuthar/.julia/conda/3/aarch64/envs/project487/lib/python3.11/site-packages/beartype/_decor/_decornontype.py", line 242, in beartype_func
    func_wrapper_code = generate_code(bear_call)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spandansuthar/.julia/conda/3/aarch64/envs/project487/lib/python3.11/site-packages/beartype/_decor/wrap/wrapmain.py", line 190, in generate_code
    code_check_return = _code_check_return(bear_call)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spandansuthar/.julia/conda/3/aarch64/envs/project487/lib/python3.11/site-packages/beartype/_decor/wrap/wrapmain.py", line 690, in _code_check_return
    reraise_exception_placeholder(
  File "/Users/spandansuthar/.julia/conda/3/aarch64/envs/project487/lib/python3.11/site-packages/beartype/_util/error/utilerrorraise.py", line 215, in reraise_exception_placeholder
    raise exception.with_traceback(exception.__traceback__)
  File "/Users/spandansuthar/.julia/conda/3/aarch64/envs/project487/lib/python3.11/site-packages/beartype/_decor/wrap/wrapmain.py", line 590, in _code_check_return
    hint = sanify_hint_root_func(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spandansuthar/.julia/conda/3/aarch64/envs/project487/lib/python3.11/site-packages/beartype/_check/convert/convsanify.py", line 149, in sanify_hint_root_func
    hint = reduce_hint_pep484585_func_return(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spandansuthar/.julia/conda/3/aarch64/envs/project487/lib/python3.11/site-packages/beartype/_util/hint/pep/proposal/pep484585/utilpep484585func.py", line 82, in reduce_hint_pep484585_func_return
    hint_sign = get_hint_pep_sign_or_none(hint)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spandansuthar/.julia/conda/3/aarch64/envs/project487/lib/python3.11/site-packages/beartype/_util/cache/utilcachecall.py", line 259, in _callable_cached
    raise exception
  File "/Users/spandansuthar/.julia/conda/3/aarch64/envs/project487/lib/python3.11/site-packages/beartype/_util/cache/utilcachecall.py", line 251, in _callable_cached
    return_value = args_flat_to_return_value[args_flat] = func(
                                                          ^^^^^
  File "/Users/spandansuthar/.julia/conda/3/aarch64/envs/project487/lib/python3.11/site-packages/beartype/_util/hint/pep/utilpepget.py", line 721, in get_hint_pep_sign_or_none
    die_if_hint_pep604_inconsistent(hint)
  File "/Users/spandansuthar/.julia/conda/3/aarch64/envs/project487/lib/python3.11/site-packages/beartype/_util/hint/pep/proposal/utilpep604.py", line 71, in die_if_hint_pep604_inconsistent
    raise BeartypeDecorHintPep604Exception(
beartype.roar.BeartypeDecorHintPep604Exception: Type hint NDArray[Shape['*'], Float] inconsistent with respect to repr() strings. Since @beartype requires consistency between type hints and repr() strings, this hint is unsupported by @beartype. Consider reporting this issue to the third-party developer implementing this hint: e.g.,
    >>> repr(NDArray[Shape['*'], Float])
    NDArray[Shape['*'], Float]  # <-- this is fine
    >>> repr(NDArray[Shape['*'], Float] | int)
    nptyping.ndarray.NDArray | int  # <-- *THIS IS REALLY SUPER BAD*

    # Ideally, that output should instead resemble:
    >>> repr(NDArray[Shape['*'], Float] | int)
    NDArray[Shape['*'], Float] | int  # <-- what @beartype wants!```

**Comment by leycec** [comment]
*...heh.* Audio DSP number crunching at CPSLO, huh? Sounds about right. I too once performed audio DSP number crunching at CPSLO. CSC 109 Dr. Staley Crew represent! The class so brutal the few lone survivors drew up T-shirts reading: "I survived Dr. Staley." *Minna no Anime.* Dr. Kurfess, the awesome German AI-ML-LLM guy. The memories all come flooding back like tears in the rain – which, of course, it never does in CPSLO. Rain is just a metaphor in Cali. Ah, to be youthful and idealistic and out of time on the latest project again!

**Wait.** What were we chatbotting about again? Oh, right. `nptyping`. I sigh. :face_exhaling: 

Because you're Team CPSLO, you have no time. Life is "learn by doing," which mostly means pain, suffering, and tears in the rain that you only become thankful for later in life. *Much later in life.* Therefore, this is your five-second **tl;dr:**

> `nptyping` is dead. Long live [`jaxtyping`](https://github.com/patrick-kidger/jaxtyping).

The five-minute <sup>which you don't have</sup> explanation of that **tl;dr** is as follows. Verily, and I do now [quote myself from the most recent changelog for @beartype 0.17.0](https://github.com/beartype/beartype/discussions/317). I am nothing if not vain and given to self-congratulatory indulgence:

## @patrick-kidger: If He Didn't Type It, You Shouldn't Use It

Lastly, @beartype 0.17.0 officially:

* Supports @patrick-kidger's [Equinox](https://github.com/patrick-kidger/equinox) now. JAX + ML + @beartype = *pretty sure you just got a raise.*
* Does *not* support [`nptyping`](https://github.com/ramonhagenaars/nptyping), because **(A)** `nptyping` is dead and **(B)** `nptyping` is bad. Dead and bad are both bad. If you attempt to use `nptyping`-based type hints under @beartype ≥ 0.17.0, @beartype will **raise fatal exceptions** informing you that you are bad by association: e.g.,

  ```python
  beartype.roar.BeartypeDecorHintPep604Exception: Type hint
  NDArray[Shape['N, N'], Float] inconsistent with respect to repr()
  strings. Since @beartype requires consistency between type hints and
  repr() strings, this hint is unsupported by @beartype. Consider
  reporting this issue to the third-party developer implementing this
  hint: e.g.,
          >>> repr(NDArray[Shape['N, N'], Float])
          NDArray[Shape['N, N'], Float]  # <-- this is fine
          >>> repr(NDArray[Shape['N, N'], Float] | int)
          nptyping.ndarray.NDArray | int  # <-- *THIS IS REALLY SUPER BAD*

          # Ideally, that output should instead resemble:
          >>> repr(NDArray[Shape['N, N'], Float] | int)
          NDArray[Shape['N, N'], Float] | int  # <-- what @beartype wants!
  ```

What @beartype is saying is that **`nptyping` is currently unmaintained, suffers over 20 severe issues, and emits 7 severe NumPy deprecation warnings.** `nptyping` is a ticking time bomb about to explode your codebase into radiating black bodies. Bear bros don't let bear bros import `nptyping`. *Not even once.*

Thankfully, @patrick-kidger exists. <sup>hard to prove, but likely true</sup> Everybody wants to transition from `nptyping` to @patrick-kidger's [Google-adjacent `jaxtyping` package](https://github.com/google/jaxtyping) already. Unlike `nptyping`, `jaxtyping` provides well-maintained type hints covering NumPy, JAX, PyTorch, and TensorFlow. It's kinda intense. It's also @beartype's [official FAQ recommendation for type-checking NumPy arrays](https://beartype.readthedocs.io/en/latest/faq/#numpy-arrays).

The data science pipeline you save might just be your own. It's probably too late, though.

![](https://media1.tenor.com/m/q7TrSkO7jMQAAAAd/ultraman-1966.gif)
<sup>your codebase when you realize you used `nptyping` everywhere</sup>

## "But the `repr()` Strings Don't Lie!", You Are Now Thinking

No, the `repr()` strings lie. Specifically, `nptyping` lies. What that verbose exception message is trying but failing to tell you is that `nptyping` is inconsistent with respect to `repr()` strings and [PEP 604-style new unions](https://peps.python.org/pep-0604).

Yes, it's true that the `repr()` for individual `nptyping` type hints is fine:

```python
>>> repr(NDArray[Shape['*'], Float])
NDArray[Shape['*'], Float]  # <-- this is fine
```

Yet, it's also true that the `repr()` for PEP 604-style new unions containing `nptyping` type hints is *not* at all fine:

```python
>>> repr(NDArray[Shape['*'], Float] | int)
nptyping.ndarray.NDArray | int  # <-- *THIS IS REALLY SUPER BAD*```
```

**That's the bad part.** In Python, the `repr()` should ideally be a string satisfying the following equality:

```python
eval(repr(obj)) == obj
```

That is, `repr()` should ideally return a Python expression which, when dynamically evaluated via the `eval()` builtin, yields the same object. We see, therefore, that `nptyping` fails this simple heuristic:

```python
>>> eval(repr(NDArray[Shape['*'], Float] | int)) == NDArray[Shape['*'], Float] | int
False
```

To my knowledge, `nptyping` is the *only* typing-oriented Python package broken in this way. It's also unmaintained. Honestly, `nptyping` being unmaintained is the worst part. If it was actively maintained, @beartype would probably go out of its way to try to support this sort of insanity. But... *it's dead.* :skull_and_crossbones: 

## CPSLO: Advice for the Ages

Grandpa @leycec shall now dispense wisdom from a geriatric keyboard in the Canadian wilderness:

* If Dr. Kurfess is still there, tell him a skinny guy with long hair who always wore metal T-shirts and looked like an elf reject from *The Lord of the Rings* sent you. Then tell him you work on satellites. Then beg for a summer job. Before you can say "shadenfreude schweinhund," you'll be on the next Lufthansa flight to Das Technologie-Zentrum Informatik und Informationstechnik (TZI) der Universität Bremen. **Good times.**
* If Clint Staley is still there, tell him the sane thing. His face may sour up into a rictus grimace. Do not be discouraged. This is common. Before you can say "bay area death mark crunch time," that saying will describe your promising new life as a junior devbro at one of Staley's many CPSLO tech startups. In a way, your life will now be over. In another way, your life will just be starting. **Good times.**
* If Madoka W-Belzel is still there, tell her almost the same thing – except that you'd like to attend Waseda Daigaku (i.e., only the top private university in Japan) for a year. Attending *Minna no Anime* helps, assuming you had time, which you do not. This script almost writes itself.

Thanks for playing along, @spagdoon0411. May @beartype, `jaxtyping`, and CSC109 be with you always.

**Comment by spagdoon0411** [comment]
Noted--will switch to jaxtyping. I think I'll especially appreciate the Tensorflow type hints. Thank you!

I do know Dr. Kurfess! Haven't taken any classes with him (yet?), but I'll mention this thread if I see him. 

> and out of time on the latest project again!

I don't appreciate being called out like that.
