### ISSUE TITLE
[Feature Request] `sklearn` "metadata routing" support

### ISSUE THREAD

**Issue by tvdboom** [beartype/beartype#340]
Hi,

I'm implementing some sklearn-like transformers that should follow the [metadata routing](https://scikit-learn.org/stable/metadata_routing.html#metadata-routing) API. It works fine until I decorate the class with `beartype`.

Example (works fine without `beartype`):

```python
import sklearn
from sklearn.base import BaseEstimator
from beartype import beartype

sklearn.set_config(enable_metadata_routing=True)

@beartype
class A(BaseEstimator):

    def fit(self, X, y, sample_weight=None):
        return self

a = A().set_fit_request(sample_weight=True)
```

Error:

```
    a = A().set_fit_request(sample_weight=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RequestMethod.__get__.<locals>.func() takes 0 positional arguments but 1 was given
```

I do realize that [sklearn's code](https://github.com/scikit-learn/scikit-learn/blob/5c4aa5d0d90ba66247d675d4c3fc2fdfba3c39ff/sklearn/utils/_metadata_requests.py#L1301) regarding metada objects is far from clean, but I hope there's a fix for it. Thx:)

**Comment by leycec** [comment]
**Guh!** This feature request is the gut punch I didn't see coming. That's a pretty gnarly exception message, huh? It's unclear exactly what `sklearn` is doing here. It's clear only that `sklearn` frightens me. "Metadata routing"? More like "insanity routing," because that's what happens when I try to read [the official documentation for "metadata routing" or the aforementioned code blob](https://scikit-learn.org/stable/metadata_routing.html#metadata-routing). A special darkness grows here.

"Serenity now!", I cry. Then I weep. :sob:

**Comment by leycec** [comment]
*...heh.* Technically, this is an upstream `sklearn` issue. All Python classes should support decoration. Ergo, the `sklearn.base.BaseEstimator` superclass should support decoration, too. It doesn't. Therefore, that superclass is busted.

Pragmatically, convincing `sklearn` to make their classes robust against decoration is a tall order – probably, an impossibly tall order. So, it is up to @beartype to somehow work around busted `sklearn` semantics. Actually...

## HOLD MY BEER

The `sklearn.base.BaseEstimator` class is *totally* b0rked. Check dis special madness out, @tvdboom:

```python
import sklearn
from sklearn.base import BaseEstimator

sklearn.set_config(enable_metadata_routing=True)

class A(BaseEstimator):
    def fit(self, X, y, sample_weight=None):
        return self

A.set_fit_request = A.set_fit_request
```

...which raises the following unreadable exception:

```python
Traceback (most recent call last):
  File "/home/leycec/tmp/mopy.py", line 18, in <module>
    a = A().set_fit_request(sample_weight=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RequestMethod.__get__.<locals>.func() takes 0 positional arguments but 1 was given
```

Suspiciously, note that:

* @beartype is *not* referenced above.
* The assignment `A.set_fit_request = A.set_fit_request` is a **tautology.** That is, that statement should have *no* harmful side effects. But it does. If you comment that assignment out, the above example runs without raising an exception. :roll_eyes: 

Since this is definitively an `sklearn` issue, let's upstream this to the `sklearn` issue tracker.

**Comment by leycec** [comment]
@tvdboom: Until upstream resolves this, consider manually decorating `BaseEstimator` *methods* rather than *subclasses*: e.g.,

```python
import sklearn
from sklearn.base import BaseEstimator
from beartype import beartype

sklearn.set_config(enable_metadata_routing=True)

class A(BaseEstimator):
    @beartype  # <-- shift the decoration from the class to method
    def fit(self, X, y, sample_weight=None):
        return self

a = A().set_fit_request(sample_weight=True)  # <-- woah. this actually works.
```

Thanks again for being so awesome. May the QA be with you always. Please reopen this if @beartype is actually at fault here or should be doing something. Until then, I play video games! :pleading_face:

**Comment by tvdboom** [comment]
Thanks for the quick reply and opening the issue with sklearn. Let's see how they respond.
