### ISSUE TITLE
[Bug] @beartype + `@methodtools.lru_cache` = :boom: 

### ISSUE THREAD

**Issue by AdrienPensart** [beartype/beartype#380]
Hello

I have an error : 

```
 File "server.py", line 21, in <module>
    @beartype
     ^^^^^^^^
  File "lib/python3.11/site-packages/beartype/_decor/decorcache.py", line 77, in beartype
    return beartype_object(obj, conf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/beartype/_decor/decorcore.py", line 87, in beartype_object
    _beartype_object_fatal(obj, conf=conf, **kwargs)
  File "lib/python3.11/site-packages/beartype/_decor/decorcore.py", line 132, in _beartype_object_fatal
    beartype_type(obj, **kwargs)  # type: ignore[return-value]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/beartype/_decor/_decortype.py", line 162, in beartype_type
    for attr_name, attr_value in cls.__dict__.items():  # pyright: ignore[reportGeneralTypeIssues]
RuntimeError: dictionary changed size during iteration
```

It happens on @beartype when using methodtools library which uses WireRope itself.

```
from beartype import beartype
from methodtools import lru_cache

class Test:
    @beartype
    @lru_cache()
    def one_method(self):
        pass
```

(I need this library because it supports lru_cache for classmethod)

Cheers!

**Comment by leycec** [comment]
**Canada _represent_.** Lookin' good in that cherry-red Muskoka chair, @AdrienPensart. Or is there a Francophone variant of "Muskoka chair" I'd better use there? What *is* "Muskoka chair" in Quebecois, anyway? Did Quebec actually invent the Muskoka chair without anybody in Ontario even knowing!? It's hard to know what to say these days. Still, it's lovely to find a fellow enthusiast of sitting on chairs on docks on lakes. :joy: 

*...back to this excellent issue.* Thanks so much for that minimal working example (MWE). That helps a metric ton. It's genuinely shocking to see third-party types changing the size of their `__dict__` dunder attributes during iteration. Never thought that could happen, honestly. Let's pretend that's sane.

`methodtools` is a super-important use case. Kinda surprising that the standard `@functools.lru_cache` decorator fails to memoize methods in the way that users expect, huh? Regardless of whether `methodtools` is less sane than desirable, @beartype *will* support this madness. Let's do this!

**Comment by leycec** [comment]
**Let's talk.** You know things are about to ugly when somebody launches with: "Let's talk." We've all been there. So, the issue here is that both `methodtools` *and* `rope` are:

* **Basically unmaintained.** The last commit for `methodtools` was over **4 months ago.** The last commit for `rope` was over **a year ago.** That's... not great. It's unclear whether either have even been tested under Python 3.12, for example.
* **`methodtools` is trivial.** Srsly. [`methodtools.py` is literally only 20 lines of meaningful code](https://github.com/youknowone/methodtools/blob/main/methodtools.py). 20 lines, bro.
* [Answers to this popular StackOverflow question provide various trivial alternatives](https://stackoverflow.com/questions/33672412/python-functools-lru-cache-with-instance-methods-release-object), including:
  * A trivial [`weakref`-based `@weak_lru_cache` decorator](https://stackoverflow.com/a/68052994/2809027):
  
    ```python
    import functools
    import weakref

    def weak_lru_cache(maxsize=128, typed=False):
        'LRU Cache decorator that keeps a weak reference to "self"'
        def wrapper(func):

            @functools.lru_cache(maxsize, typed)
            def _func(_self, *args, **kwargs):
                return func(_self(), *args, **kwargs)

            @functools.wraps(func)
            def inner(self, *args, **kwargs):
                return _func(weakref.ref(self), *args, **kwargs)

            return inner

        return wrapper
    ```
  * A trivial [`__init__()` kludge that's super clever *and* funny](https://stackoverflow.com/a/68052994/2809027):
  
    ```python
    from functools import lru_cache

    class Foo(object):
        def __init__(self):
            self.cached_method = lru_cache(maxsize=16)(self.cached_method)  # <-- WTF *lololo*

        def cached_method(self, x):
            return x + 5
    ```

There are heaps of other practical alternatives, too. If some combination of `methodtools`, `rope`, and/or `ring` were well-maintained, @beartype would be delighted to officially support them. But... *they're just not.* It's kinda hard to justify the time investment when the original author isn't even investing time in these projects anymore.

@beartype weeps for `methodtools`. :sob:

**Comment by AdrienPensart** [comment]
Thank you!

i agree with your conclusion, I won't do more magic with those unmaintained projects!
And indeed, I found a very simple solution

```
@beartype
@dataclass(frozen=True)
class Server:
    @classmethod
    @cache
    def all(cls) -> list[Self] | None:
        ...
```

immutable dataclasses for the win!

"Muskoka chair" is a simple "chaise de jardin" (at least in french) :p

**Comment by leycec** [comment]
> immutable dataclasses for the win!

**Decorator stacks!** This is now a thing, huh? `@beartype.beartype` + `@dataclasses.dataclass` + `@functools.cache` = `something magical we never thought would work`

> "Muskoka chair" is a simple "chaise de jardin" (at least in french) :p

**...amazing.** French gets it right yet again. "Muskoka chair" is such a *weird* term. Growing up in California left me unprepared for the linguistic rigours of life in Canada. I didn't even know what a "Muskoka" was. My wife politely explained that it's a nice place where rich people live. :joy_cat: 

"Chaise de jardin," though. That just makes sense. "Chair of the garden," right? "Garden chair"? That's sane. Even people from California can understand that.

I'll stop talking now. Actually, I have *one* last thing to say... *promise.* I'm pretty sure [Parc national des Grands-Jardins in Quebec](https://www.google.com/search?q=Parc+National+des+Grands-Jardins) is the most beautiful place in the world. Those images just take my breath away. Quebec is such a stunning province. Much love from Ontario! – *the wilderness QA bear*
