### ISSUE TITLE
Overloading bear confuses Mypy (and/or perhaps issue author)

### ISSUE THREAD

**Issue by posita** [beartype/beartype#39]
Consider:

```python
# test_case.py
from typing import Union, overload
from beartype import beartype

class MypySoConfuse:
    @overload
    def __getitem__(self, key: int) -> int:
        ...

    @overload
    def __getitem__(self, key: slice) -> tuple:
        ...

    @beartype  # <- comment this out and the warning goes away
    def __getitem__(self, key: Union[int, slice]) -> Union[int, tuple]:
        if isinstance(key, int):
            return 0
        else:
            return ()
```

This yields:

```
$ mypy --version
mypy 0.902
$ mypy test_case.py
test_case.py:14: error: Overloaded function implementation does not accept all possible arguments of signature 1
test_case.py:14: error: Overloaded function implementation does not accept all possible arguments of signature 2
Found 2 errors in 1 file (checked 1 source file)
```

If you comment out the `@beartype` decorator above, Mypy stops complaining. beartype is utter magic to me, and I—sadly—have not spent much (okay, _any_) time investigating a root cause, so I don't know if this is a flaw in Mypy, or beartype, or just a fundamental incompatibility (no judgment, some people are just not meant to be together, and that's okay).

**Comment by posita** [comment]
Ah, this might be a [known issue](https://github.com/beartype/beartype/blob/c3b9c9d0f0e77c1d7e3fd4172fa44cbdf431c020/beartype/_util/data/hint/pep/sign/datapepsigns.py#L147). I'm not sure I understand those comments, but I suspect that puts `@overload` in the "fundamental incompatibility" department? 😬

**Comment by leycec** [comment]
**Thanks so much** for the detailed writeup, Matt. We aim to please here at Beartype, Noninc. We'll get everything patched right up. Your minimal length example (MLE) is a veritable godsend during [this dreaded Canadian Heat Bubble that's already killed hundreds](https://www.cnn.com/2021/06/29/americas/canada-heat-wave-deaths/index.html) and fried my already fragile synapses. <sup>y u do this 2 us, sun</sup>

You've *probably* hit a duplicate of #36. You're in luck! We just fixed that. If that's the case, I'll immediately fire off a new stable release (so, `beartype 0.7.1`) to ensure no other innocent bystanders are similarly hit. :car:

**Comment by leycec** [comment]
I have good news and I have bad news:

```
$ mypy --version
mypy 0.812
$ mypy test_case.py
Success: no issues found in 1 source file
```

The good news is that I can't replicate this! The bad news is that I can't replicate this! Either we actually did fix this in #36 *or* my MyPy is too old and erroneously giving me a false negative.

I choose to believe for simplicity that we actually did fix this in #36, which means I'm firing off a new stable release (so, `beartype 0.7.1`) this evening. Look to the coming dawn for it brings hope and renewal. :sunrise_over_mountains:

**Comment by leycec** [comment]
`beartype 0.7.1` has now been released, complete with @jonathanmorley's miraculous fix for this at #37 and my not-so-miraculous fix for #38 (i.e., `NotImplemented`). Would you mind testing everything *yet again* and, if resolved, closing this issue on your end?

Thanks again for the delightful comments. Since I get all intellectually pumped up by this sort of thing, just let me know if you'd like `@beartype` to do any other stupefyingly nice things. Until then, may the Canadian brown bear be with you during this painfully *hottttt* summer. :face_with_thermometer:

**Comment by posita** [comment]
Now it's _my_ turn to deliver the news, good and bad. The good news is that the aforementioned recent fixes (thaumaturgic or otherwise) do indeed appear to have addressed the presented test case.

![Yay!](https://media.tenor.com/images/da59c445cf569623adb3fea2e670ea0d/tenor.gif)

The bad news is that in my efforts to distill my _real_ problem into something digestible, I apparently omitted a key distinction that, when reintroduced, results in an (albeit different) error.

![Boo!](https://media.tenor.com/images/b4a3b32081dc82d7cd1612dad5a1deb8/tenor.gif)

Consider:

```python
# test_case_redux.py
from typing import Union, overload
from beartype import beartype

class ThisTimeWithFeeling(tuple):  # <- uh-oh [dramatic pause], *inheritance* [dramatic discordant score]
    @overload
    def __getitem__(self, key: int) -> int:
        ...

    @overload
    def __getitem__(self, key: slice) -> tuple:
        ...

    @beartype  # <- okay, comment *this* out and the warning goes away
    def __getitem__(self, key: Union[int, slice]) -> Union[int, tuple]:
        if isinstance(key, int):
            return 0
        else:
            return (0,)

assert type(ThisTimeWithFeeling(range(10))[0]) == int
assert type(ThisTimeWithFeeling(range(10))[slice(2, 4)]) == tuple
print("success")
```

My results:

```
$ mypy --version
mypy 0.902
$ mypy test_case_redux.py
test_case_redux.py:15: error: Signature of "__getitem__" incompatible with supertype "tuple"
test_case_redux.py:15: error: Signature of "__getitem__" incompatible with supertype "Sequence"
Found 2 errors in 1 file (checked 1 source file)
$ python test_case_redux.py  # runtime works just fine, thank you
success
```

Now I'm not the most careful critter when it comes to academically rigorous typing, and I did create the above example through mostly observational deduction, but it's not _too_ far off from typeshed's notions, specifically [the following from `stdlib/builtins.pyi`](https://github.com/python/typeshed/blob/04fb7ceb3ce919ed541a5b7b675359f09a104e16/stdlib/builtins.pyi#L715-L718):

```python
class tuple(Sequence[_T_co], Generic[_T_co]):
    …
    @overload
    def __getitem__(self, x: int) -> _T_co: ...
    @overload
    def __getitem__(self, x: slice) -> Tuple[_T_co, ...]: ...
```

That being said, it's quite possible that I'm Doing It Wrong™, in which case perhaps a stern scolding or gentle education (or something in between) would be the best tact for resolution.

**Comment by posita** [comment]
> … [J]ust let me know if you'd like `@beartype` to do any other stupefyingly nice things. …

As tempting as that may be, I find myself drawn to [RFC 1925](http://www.faqs.org/rfcs/rfc1925.html), § (2)(12):

> In protocol design, perfection has been reached not when there is nothing left to add, but when there is nothing left to take away.

**Comment by leycec** [comment]
**Bwaha!** I cackle madly like a scantily clad Heffalump huffing honey, pictured here.

![my eyes, they bleed](https://static.wikia.nocookie.net/disney/images/0/01/Winniethepooh-disneyscreencaps.com-4409.jpg/revision/latest?cb=20170829055310)

I suspect we've now flung ourselves headlong from what was once an actual beartype issue into what is now a probable mypy issue. Yes, I am now bravely shifting the blame! Behold, evidence supporting my suspicious claims:

```
# test_case_part_deux.py
from typing import Any, Callable, TypeVar, Union, overload

T = TypeVar('T', bound=Callable[..., Any])
def identity(func: T) -> T:
    return func

class ThisTimeWithFeeling(tuple):  # <- uh-oh [dramatic pause], *inheritance* [dramatic discordant score]
    @overload
    def __getitem__(self, key: int) -> int:
        ...
    @overload
    def __getitem__(self, key: slice) -> tuple:
        ...
    # @beartype  # <- okay, comment *this* out and the warning goes away
    @identity  # <- okay, comment *this* out and the warning goes away
    def __getitem__(self, key: Union[int, slice]) -> Union[int, tuple]:
        if isinstance(key, int):
            return 0
        else:
            return (0,)

assert type(ThisTimeWithFeeling(range(10))[0]) == int
assert type(ThisTimeWithFeeling(range(10))[slice(2, 4)]) == tuple
print("success")
```

So, we've lazily replaced `@beartype` in [the sad Eeyore example you graciously gave above](https://github.com/beartype/beartype/issues/39#issuecomment-871865394) with the most trivial possible decorator. Yup, it's none other than the `@identity` decorator silently reducing to a noop by returning the passed callable unmodified as is. Excitement! Thrills! And... **spills:**

```
$ mypy test_case_part_deux.py
test_case_redux.py:18: error: Signature of "__getitem__" incompatible with supertype "tuple"
test_case_redux.py:18: error: Signature of "__getitem__" incompatible with supertype "Sequence"
Found 2 errors in 1 file (checked 1 source file)
```

Verily, mypy spaketh. It spaketh the exact same thing as when decorated by the `@beartype` decorator, actually. We infer that the actual decorator being applied doesn't particularly matter. It's something *else* that matters, which means either:

* *mypy is doing it wrong.* This is the likeliest and certainly most convenient explanation. I've found in life that other people are usually to blame for our own personal failings.
* *You're doing it wrong.* I'm honestly out of my depth here, because my facility with type-hinting standards isn't quite what one would hope from a runtime type-checking developer. I don't *think* you're doing wrong, but `@overload` intersects with dark magic and flamboyant dragons – so I can't say for *certain* that you're doing it right.

Would you mind reposting the `@identity` decorator example I just gave to [mypy's issue tracker](https://github.com/python/mypy/issues)? They should be able to clarify the situation. Until then, I'll graciously <sup>:vomiting_face:</sup> leave this open. It's possible, however unlikely, that we've still mistyped the `@beartype` decorator in some way.

<sup>*please let this be mypy's fault please please please*</sup>

**Comment by posita** [comment]
To my utter embarrassment (but not shock), this is indeed not only a Mypy issue, but a _**known**_ one. Specifically: python/mypy#8393. No need to continue chewing valuable cognitive cycles keeping this issue open where it be known where said dragons and dark magic lie.

In summary, I'm closing this as fixed and suggesting that https://github.com/beartype/beartype/issues/39#issuecomment-871865394 _et seq._ should be treated as a _non sequitur_.

Thanks for all the attention!
