### ISSUE TITLE
Reenabling pyright-action

### ISSUE THREAD

**Issue by jakebailey** [beartype/beartype#400]
Hey there; I saw https://github.com/beartype/beartype/commit/5791c2ad6487b4e5cd2f1d59d5421c64d96df916 and commented on it, but commit comments are likely to go under the radar.

The workflows seem to have been timing out because https://github.com/beartype/beartype/blob/main/.github/workflows/python_test.yml#L174 is configured to max the workflow out at a measly 10 minutes, and between the failing runs, pyright went from v1.1.367 (https://github.com/beartype/beartype/actions/runs/9526427274/job/26261820133#step:7:21) to 1.1.369 (https://github.com/beartype/beartype/actions/runs/9675181669/job/26692206557#step:7:21).

I think it's unlikely that the action itself is doing it; you may want to try out testing 1.1.367 to 1.1.369 and see if there's just a perf regression in pyright itself.

**Comment by leycec** [comment]
**My Gods.** You are the QA King of All Time! I'm literally dumbfounded here with cheetos sprinkled across my beard that you responded so *insanely* quickly. And...

> configured to max the workflow out at a measly 10 minutes

Measly, indeed. This is why we don't copy-and-paste from random trustworthy Internet sources. I sigh.

There sure were [*a lot* of failing runs](https://github.com/beartype/beartype/actions), weren't there? Like, *a lot* a lot. Since you are the QA King of All Time, I agree that your Action is blameless and that `pyright` has become slower than a lobster riding a sea cucumber. It might be useful to note somewhere in the `README` for your stunning Action that `pyright` has become slower than a lobster riding a sea cucumber.

Maybe? I dunno. Just a thought. Blame `pyright`. That's what I do.

## `pyright`: What Happened, Buddy?

Interestingly, `pyright` *used* to be super-fast. It used to be `mypy` that was the super-slow one. My, my. How the tables have reversed. I chuckle. Oh, `pyright`. What happened to you along the way? :smile_cat:

**Comment by jakebailey** [comment]
The time went from some 30 seconds to timing out, so I'd hazard a guess that it's just a plain bug.

**Comment by leycec** [comment]
**Yuppers.** Oddly, `pyright` behaves itself locally. It's still slower than `mypy` – *but not 10 minutes slower.* Oh, well. Let's just toggle a few things in our workflow and see if everything settles down...

If not, I might need to blacklist newer `pyright` versions. This saddens me. Why, `pyright`? Why!?  :face_exhaling:

**Comment by leycec** [comment]
**Oh.** Oh, boy. I need to blacklist newer `pyright` versions. `pyright 1.1.365` is fine, but `pyright 1.1.369` is **fundamentally broken.** This isn't just a performance regression; this is an infinite loop. No joke. All shade. `pyright 1.1.369` is literally *not* terminating when you point it at the @beartype codebase. Presumably, many other codebases have been hit as well.

I'm kinda flabbergasted, honestly. An infinite loop in a static type-checker *basically* makes that static type-checker a **Denial of Service (DOS) attack vector** and therefore a **Common Vulnerability and Exploit (CVE)** waiting to happen. 

I can't believe Microsoft broke `pyright` so badly that's it *basically* a self-inflicting DoS now. So not pleased, Microsoft. :sob:

**Comment by leycec** [comment]
**Possibly resolved by 930e70a93278238afbab,** which purports to resolve this issue with finality by:
    
* Restoring your stellar Action in our CI workflow. :partying_face: 
* Pinning `pyright` to `pyright 1.1.365`, the most recent version known to *not* suffer a self-inflicted DoS. :stuck_out_tongue_closed_eyes: 

Thanks again for all the immense assistance. You are the QA light that guides us all.

**Comment by jakebailey** [comment]
Are you planning on reporting this upstream? Bugs happen!

**Comment by leycec** [comment]
*...heh.* I should follow your expert advice, huh? That would be the responsible thing to do. Microsoft deserves to know that their house is burning. Instead, I'll probably just bicycle all day in the rare Canadian sunshine with my wife. Summer priorities! :mountain_bicyclist: :dash:  :sun_with_face:

**Comment by erictraut** [comment]
Apologies for the regression in pyright. Version 1.1.370 (just published) should fix the issue you experienced. When I run pyright 1.1.370 manually on the `beartype` source base, it completes in about 1.5 seconds.

We leverage the [mypy_primer](https://github.com/hauntsaninja/mypy_primer) tool to run pyright on a variety of open-source code bases as part of our testing suite and CI pipeline. This past week, we greatly expanded (by an order of magnitude) the number of repos that are covered by `mypy_primer`. The expanded set now includes `beartype`, so regressions like this should be caught and prevented in the future.

If you run into issue with pyright, please don't hesitate to file a bug in the pyright issue tracker.

**Comment by leycec** [comment]
**...guh.** I really dropped the GitHub ball here. I should've reported this. I didn't, because summertime. I kinda feel bad now, justifiably. I only have lazy excuses and should be the one apologizing. Thus... I'm so sorry! Please accept this sorry meme.

![](https://media1.tenor.com/m/zmLmHP8_e0YAAAAC/i%27m-sorry-ajith.gif)
<sup>*no idea who this guy is but he expresses my feelings*</sup>

Despite my lassitude, I'm really grateful to both you and @hauntsaninja for resolving this so promptly. As the only meagre thanks I can give, **commit a58af4a68fbd68d *finally* resolves this @beartype issue** by:

* Bumped @beartype to require `pyright >= 1.1.370` in our `pyproject.toml`.
* Stopped pinning our GitHub Actions-based `python_test.yaml` workflow to `pyright 1.1.365`.

@beartype salutes @erictraut and @hauntsaninja, whose legend grows with each passing commit.
