### ISSUE TITLE
[Bug] numba interop

### ISSUE THREAD

**Issue by jonnyhyman** [beartype/beartype#412]
I'm using beartype on my entire package which has caught many errors for me so far woot woot!

When using `numba` for no-python JIT acceleration of functions, `beartype` emits warnings for each one, presumably because of the way `numba` mutates the function into a `CPUDispatcher` object whilst JIT compiling it.

Minimum reproducible code:
```python
from beartype import beartype
from numba import njit


@beartype
@njit(cache=True)
def go_bears() -> bool:
    return True


go_bears()
```

emits error:
```bash
Traceback (most recent call last):
  File "numba_beartype_issue.py", line 5, in <module>
    @beartype
     ^^^^^^^^
  File "python3.12/site-packages/beartype/_decor/decorcache.py", line 77, in beartype
    return beartype_object(obj, conf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.12/site-packages/beartype/_decor/decorcore.py", line 87, in beartype_object
    _beartype_object_fatal(obj, conf=conf, **kwargs)
  File "python3.12/site-packages/beartype/_decor/decorcore.py", line 136, in _beartype_object_fatal
    beartype_nontype(obj, **kwargs)  # type: ignore[return-value]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.12/site-packages/beartype/_decor/_decornontype.py", line 135, in beartype_nontype
    return beartype_pseudofunc(obj, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.12/site-packages/beartype/_decor/_decornontype.py", line 715, in beartype_pseudofunc
    pseudofunc.__class__.__call__ = _beartype_descriptor_boundmethod(  # type: ignore[assignment,method-assign]
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.12/site-packages/beartype/_decor/_decornontype.py", line 551, in _beartype_descriptor_boundmethod
    assert is_func_boundmethod(descriptor), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: <method-wrapper '__call__' of CPUDispatcher object at 0x11415a530> not builtin bound method descriptor.
```

Any suggestions of mitigations for these errors, (which are warnings when applied to the whole module)? 

Ideally I'd like to `@beartype` all `@numba.njit` functions since they are a honeypot for bugs and type issues, but given that I have hundreds of numba functions it makes my unit test warnings overly dense.

Happy to put this on `numba`'s radar, perhaps they can mock the bound-method descriptors?

**Comment by leycec** [comment]
> I'm using beartype on my entire package which has caught many errors for me so far woot woot!

:partying_face: :birthday: :balloon: :birthday:  :partying_face:

> Any suggestions of mitigations for these errors, (which are warnings when applied to the whole module)?

I have good news; I have bad news. The good news is that I *appear* to have already resolved this without even knowing I was resolving this. The bad news is that you have to manually install **[@beartype 0.19.0 release candidate 0](https://github.com/beartype/beartype/discussions/401)** to enjoy the good news:

```bash
pip install --upgrade --pre beartype  # <-- LET THE THUNDER AND THE HEADS ROLL
```

The good-good news is that this is easy. The bad-bad news is that I kinda wasted your scarce and valuable time by not officially releasing this as **@beartype 0.19.0** already. The good-good-good news is that I now [publicly announce pre-release "beta" candidates over *here* at this adjacent GitHub discussion](https://github.com/beartype/beartype/discussions/401), which you can also subscribe to to receive automated e-mail updates on new @beartype beta releases. The bad-bad-bad news is that I am disgustingly verbose and will immediately pollute your inbox with irrelevant and nonsensical digressions into Ultraman and the LA Lakers.

I've been holding off on officially releasing @beartype 0.19.0, because I now live in mortal fear of breaking PyTorch *yet again.* Sadly, the fear of breaking PyTorch *yet again* is now being eclipsed by the fear of breaking `numba`. When you're breaking one project out of fear of breaking another project, you know it's time for an official release.

Thanks for the gentle reminder, @jonnyhyman. Even the angels are crying in Los Angeles tonight. :smiling_face_with_tear:
