### ISSUE TITLE
Cannot use numpy.typing.NDArray type hints

### ISSUE THREAD

**Issue by Antyos** [beartype/beartype#42]
Numpy v1.21.0 introduced [runtime subscriptable aliases for ndarrays](https://numpy.org/doc/stable/release/1.21.0-notes.html#a-runtime-subcriptable-alias-has-been-added-for-ndarray). The feature is really cool and I really like the direction that it seems to be headed in. 

However, these new annotations do not seem compatible with the `@beartype` decorator.

## System info

OS: Windows 10, 20H2
Python: 3.8.10
Beartype: 0.71.0
Numpy: 1.21.0

## Sample Code

Running this sample code:

```python
from beartype import beartype
import numpy as np
import numpy.typing as npt

@beartype
def foo(arr: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]:
    return arr

foo(np.zeros(3))
```

Yields this error:

```python
Traceback (most recent call last):
  File "C:\Users\Antyos\Code\Project\.venv\lib\site-packages\beartype\_util\cls\utilclstest.py", line 174, in die_unless_type_isinstanceable
    isinstance(None, cls)  # type: ignore[arg-type]
  File "C:\Users\Antyos\Code\Project\.venv\lib\site-packages\numpy\typing\_generic_alias.py", line 137, in __instancecheck__
    raise TypeError("isinstance() argument 2 cannot be a "
TypeError: isinstance() argument 2 cannot be a parameterized generic

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Users\Antyos\Code\Project\.venv\lib\site-packages\beartype\_decor\main.py", line 268, in beartype
    func_wrapper_code = generate_code(func_data)
  File "C:\Users\Antyos\Code\Project\.venv\lib\site-packages\beartype\_decor\_code\codemain.py", line 162, in generate_code
    code_params = _code_check_params(data)
  File "C:\Users\Antyos\Code\Project\.venv\lib\site-packages\beartype\_decor\_code\codemain.py", line 324, in _code_check_params
    hint = coerce_hint_pep(
  File "C:\Users\Antyos\Code\Project\.venv\lib\site-packages\beartype\_decor\_cache\cachehint.py", line 254, in coerce_hint_pep
    die_unless_hint(hint=hint, hint_label=hint_label)
  File "C:\Users\Antyos\Code\Project\.venv\lib\site-packages\beartype\_util\hint\utilhinttest.py", line 104, in die_unless_hint
    die_unless_hint_nonpep(hint=hint, hint_label=hint_label)
  File "C:\Users\Antyos\Code\Project\.venv\lib\site-packages\beartype\_util\hint\nonpep\utilhintnonpeptest.py", line 111, in die_unless_hint_nonpep
    die_unless_hint_nonpep_type(
  File "C:\Users\Antyos\Code\Project\.venv\lib\site-packages\beartype\_util\hint\nonpep\utilhintnonpeptest.py", line 200, in die_unless_hint_nonpep_type
    die_unless_type_isinstanceable(
  File "C:\Users\Antyos\Code\Project\.venv\lib\site-packages\beartype\_util\cls\utilclstest.py", line 208, in die_unless_type_isinstanceable
    raise exception_cls(exception_message) from exception
beartype.roar.BeartypeDecorHintNonPepException: @beartyped foo() parameter "arr" type hint numpy.ndarray[typing.Any, numpy.dtype[numpy.float64]] uncheckable at runtime (i.e., not passable as 
second parameter to isinstance() due to raising "isinstance() argument 2 cannot be a parameterized generic" from metaclass __instancecheck__() method).

```

Knowing that Beartype leverages the Python built-in `Annotated` type, it roughly makes sense why this error would be occurring. While creating a Beartype numpy array using `Annotated` and `lambda` still has its uses, static type checkers such as Pylance/Pyright are now equipped to recognize this new Numpy typing syntax (that's how I initially found out about this change; my code had a ton of new errors I didn't understand), but I don't know if they can recognize the Beartype version in the same way.

**Comment by leycec** [comment]
**Fantastic find.** Thanks so much for the heads up on this, Antyos. Tensor typing is in our critical section, which makes this a high-priority feature request for us.

Fortunately, NumPy developers sensibly implemented their high-level `numpy.typing.NDArray` type hint in terms of the standard `types.GenericAlias` type hint factory first introduced by Python 3.9.0. That's great, because it means `@beartype` can trivially detect `numpy.typing.NDArray` type hints with well-established standards we already support:

```
$ ipython3.9
>>> import numpy as np
>>> import numpy.typing as npt
>>> hint = npt.NDArray[np.float64]
>>> print(f'NDArray[n.float64] type: {type(hint)}')
NDArray[n.float64] class: <class 'types.GenericAlias'>
```

Unfortunately, NumPy developers kinda non-sensibly reimplemented the same `numpy.typing.NDArray` type hint in terms of their own private non-standard `numpy.typing._generic_alias._GenericAlias` type hint factory under Python < 3.9.0:

```
$ ipython3.8
>>> import numpy as np
>>> import numpy.typing as npt
>>> hint = npt.NDArray[np.float64]
>>> print(f'NDArray[n.float64] type: {type(hint)}')
NDArray[n.float64] class: <class 'numpy.typing._generic_alias._GenericAlias'>
```

If they'd just made `numpy.typing._generic_alias._GenericAlias` public rather than private, it would've been trivial for `@beartype` to detect that too. Instead, they privatized it. `@beartype` *never* violates privacy encapsulation in third-party packages, because `@beartype` doesn't want to become a flying pile of burning wreckage out on the tarmac of PyPI. So, that's a no-fly zone.

But... *that's mostly okay.* Under:

* Python ≥ 3.9.0, I'd be delighted to add conditional support for `numpy.typing.NDArray` to the next stable `beartype` release!
* Python < 3.9.0, we'll probably continue raising an unpleasant exception with all of the apologetic tears I can shed. We can't even reliably detect `numpy.typing.NDArray` type hints under Python < 3.9.0, because their type is private, obfuscated, and really *not* intended to be externally accessed.

Curious Bear hopes that sounds like a reasonable compromise.

![curious bear is curious](https://cottagelife.com/wp-content/uploads/2017/05/vgpyn8diytxduj0kpgvn.jpg)

**Comment by Antyos** [comment]
This sounds great! Glad to see this will be supported!

It's unfortunate that this won't work with Python < 3.9, but I understand why and agree with your decision. Is there a `__futures__` import that would make it work in 3.8?

Unfortunately, the project I'm working on is stuck on 3.8 due to certain dependencies but being compatible with later versions. However, I'm looking forward to implementing beartype in future projects or when my current project can be updated.

**Comment by leycec** [comment]
> It's unfortunate that this won't work with Python < 3.9...

...I share this disappointment. Gatekeeping `numpy.typing` behind bleeding-edge Python versions isn't a good look.

Come to think, there *might* actually be a circuitous way for us to slyly detect `numpy.typing.NDArray` type hints under Python < 3.9:

```
$ ipython3.8
>>> import numpy as np
>>> import numpy.typing as npt
>>> hint = npt.NDArray[np.float64]
>>> getattr(hint, '__origin__', None) is np.ndarray
True
```

*My eyes... they bleed.*

So, `getattr(hint, '__origin__', None) is np.ndarray` may be a hacky, cumbersome, and inefficient kludge – but it has the benefit of actually reliably detecting `numpy.typing.NDArray` type hints under Python < 3.9 without violating privacy encapsulation. **That means we're going to do it.** :exploding_head: 

> Is there a `__futures__` import that would make it work in 3.8?

Sadly, no! But at least I get to blame someone else again. In this case, PEP 585 authors are to blame; they failed to backport support for the `__class_getitem__()` dunder method underlying magical syntax like `npt.NDArray[np.float64]` to the `__futures__` mechanism under Python < 3.9, [despite fraudulently claiming in PEP 585 they had done just that](https://www.python.org/dev/peps/pep-0585/#id5). Mostly everything in the ["Backwards Compatibility"](https://www.python.org/dev/peps/pep-0585/#id5) ["Implementation"](https://www.python.org/dev/peps/pep-0585/#id6) sections of PEP 585 is a [deceptive masquerade that doesn't work at runtime](https://stackoverflow.com/questions/62871524/is-pep-585-unusable-at-runtime-under-python-3-7-and-3-8).

But this must be your lucky GitHub day. `@beartype` can just stealthily hack around the lack of `__futures__` support with the above ~~stupidity~~ cleverness under Python < 3.9, which means you won't even have to import anything additional (from `__futures__` or otherwise) to get this to work on your side. It'll just work.

> Unfortunately, the project I'm working on is stuck on 3.8 due to certain dependencies but being compatible with later versions. 

I definitely get that and feel your radiating dev pain. Would `@beartype` transparently supporting `numpy.typing.NDArray` type hints across all Python versions via the above stealth hack change your mind about adopting `@beartype`?

We aim to please data scientists here. If we ever stop doing that, we have failed in our primary mission... and the bear doesn't tolerate failure. Let me know what you need and we'll make it so.

**Comment by Antyos** [comment]
You weren't kidding about this being my lucky GitHub day, wow! All of this sounds amazing and will absolutely be adding beartype to this project and probably all my future projects too. I'm looking forward to the update!

P.S. Why are you so amazing??? 🤩

**Comment by leycec** [comment]
*awwww* :hugs: 

Why are you so incredibly nice, that's what I want to know! Relatedly, I actually thought of an even ~~awfuller~~ cleverer one-liner for portably detecting `numpy.typing.NDArray` type hints across Python versions: `repr(hint).startswith('numpy.ndarray[')`. Despite being hideously obfuscatory and basically ineffable, it actually works:

```
$ ipython3.8
>>> import numpy as np
>>> import numpy.typing as npt
>>> hint = npt.NDArray[np.float64]
>>> repr(hint).startswith('numpy.ndarray[')
True

$ ipython3.9
>>> import numpy as np
>>> import numpy.typing as npt
>>> hint = npt.NDArray[np.float64]
>>> repr(hint).startswith('numpy.ndarray[')
True
```

I horrify even myself. :scream_cat:

**Comment by Antyos** [comment]
That has to be one of the most elegant hideous line of code I have ever laid eyes on. 😂

**Comment by leycec** [comment]
So – it begins. fcb24d3 now detects `numpy.typing.NDArray` type hints, but how do we handle them?

**...we don't.** Yes, it's both brilliant and stupid! We just internally map `numpy.typing.NDArray` type hints that we don't want to explicitly handle into equivalent `typing.Annotated` type hints powered by `beartype.vale.IsAttr` and `beartype.vale.IsEqual` that we already recursively handle across the entire codebase with extensive unit testing, which means we're mostly already done here:

```
# Beartype 0.8.0 will internally map this "hard"
# annotated callable we don't want to handle...
@beartype
def rock_the_data_science(the_array_dont_like_it:
    npt.NDArray[np.float64]) -> None: ...

# ...to look this this "easy" annotated callable we
# already handle! (Yes, easy. No, really. What's
# not easy about a triply-nested type hint requiring
# imports from at least three wildly different APIs?)
@beartype
def rock_the_data_science(the_array_dont_like_it:
    Annotated[np.ndarray, IsAttr['dtype', IsAttr['type', IsEqual[np.float64]]]]
) -> None: ...
```

The last trick up my hipster flannel will be differentiating between:

* `numpy.dtype.type` objects like `np.float64`, which actually isn't a `dtype` even though NumPy externally pretends it is. Thanks, NumPy.
* `numpy.dtype` objects like `np.dtype('>i4')`, which actually is a `dtype` even though nobody has ever seen one of those in real life.

Let's see how much caffeine I can inject straight into my veins this Friday evening. :coffee:

**Comment by leycec** [comment]
**Great success.** I accidentally closed this with a commit message yesterday, but that's possibly okay because I'm fairly certain that `@beartype` now fully supports all possible `numpy.typing.NDArray` type hints! We rejoice!

...at least, we *would* rejoice if I hadn't used weasel words like "accidentally," "possibly okay", and "fairly certain" above. I should really exhaustively test this a bit more and then write readable documentation. Why is that always a challenge? <sup>...the struggle is real</sup>

I'm aiming to release both this and #34 – yup, it's full `typing_extensions` support – as **beartype 0.8.0** this Friday. But that might get pushed to early next week if I decide to play trashy Japanese video games instead. Let's see what happens! The excitement is palpable.

**Comment by braniii** [comment]
It is so nice to see the impressive pace at which beartype is developing! Now that NDArray is supported by the latest release, one could add the support of [ArrayLike](https://numpy.org/devdocs/reference/typing.html#arraylike) to the roadmap. Just in case you are running out of todos ;)

Here an example code executed with py3.8 and beartype 0.8.0:
```Python
import numpy as np
from beartype import beartype
from numpy.typing import ArrayLike

@beartype
def foo(arr: ArrayLike[np.float64]) -> None:
    return


foo(np.zeros(3).astype(np.float64))
```
Raises following error:
```Bash
Traceback (most recent call last):
  File "asarray.py", line 6, in <module>
    def foo(arr: ArrayLike[np.float64]) -> None:
  File "/home/***/anaconda3/envs/py3.8/lib/python3.8/typing.py", line 261, in inner
    return func(*args, **kwds)
  File "/home/***/anaconda3/envs/py3.8/lib/python3.8/typing.py", line 686, in __getitem__
    _check_generic(self, params)
  File "/home/***/anaconda3/envs/py3.8/lib/python3.8/typing.py", line 211, in _check_generic
    raise TypeError(f"{cls} is not a generic class")
TypeError: typing.Union[typing.Sequence[typing.Sequence[typing.Sequence[typing.Sequence[typing.Sequence[typing.Any]]]]], numpy.typing._array_like._SupportsArray[ForwardRef('dtype[Any]')], typing.Sequence[numpy.typing._array_like._SupportsArray[ForwardRef('dtype[Any]')]], typing.Sequence[typing.Sequence[numpy.typing._array_like._SupportsArray[ForwardRef('dtype[Any]')]]], typing.Sequence[typing.Sequence[typing.Sequence[numpy.typing._array_like._SupportsArray[ForwardRef('dtype[Any]')]]]], typing.Sequence[typing.Sequence[typing.Sequence[typing.Sequence[numpy.typing._array_like._SupportsArray[ForwardRef('dtype[Any]')]]]]], bool, int, float, complex, str, bytes, typing.Sequence[typing.Union[bool, int, float, complex, str, bytes]], typing.Sequence[typing.Sequence[typing.Union[bool, int, float, complex, str, bytes]]], typing.Sequence[typing.Sequence[typing.Sequence[typing.Union[bool, int, float, complex, str, bytes]]]], typing.Sequence[typing.Sequence[typing.Sequence[typing.Sequence[typing.Union[bool, int, float, complex, str, bytes]]]]]] is not a generic class
```

**Comment by leycec** [comment]
> It is so nice to see the impressive pace at which beartype is developing!

aww, *u* so nice! :blush:  

> Now that `NDArray` is supported by the latest release, one could add the support of `ArrayLike` to the roadmap.

Yes. Let's add ever more back-breaking features onto my drooping shoulders. Actually, I think that's just my bursitis acting up. Curse this geriatric body. :older_man: 

In all seriousness, this is a great idea. So, it shall be. I was kinda hoping the remainder of the `numpy.typing` subpackage would just work out-of-the-box. Clearly, I am still a utopian dreamer.

The traceback is suggestive of an upstream issue. Specifically, `numpy.typing.ArrayLike` appears to be inducing infinite recursion from within the `typing` module at runtime under at least Python < 3.9.0. This is *reaaal* sus af:

```
TypeError: typing.Union[typing.Sequence[typing.Sequence[typing.Sequence[
typing.Sequence[typing.Sequence[typing.Any]]]]], 
numpy.typing._array_like._SupportsArray[ForwardRef('dtype[Any]')], 
typing.Sequence[numpy.typing._array_like._SupportsArray[ForwardRef('dtype[Any]')]], 
typing.Sequence[typing.Sequence[numpy.typing._array_like._SupportsArray[
ForwardRef('dtype[Any]')]]], 
typing.Sequence[typing.Sequence[typing.Sequence[
numpy.typing._array_like._SupportsArray[ForwardRef('dtype[Any]')]]]], 
typing.Sequence[typing.Sequence[typing.Sequence[
typing.Sequence[numpy.typing._array_like._SupportsArray[
ForwardRef('dtype[Any]')]]]]], bool, int, float, complex, str, bytes, typing.Sequence[
typing.Union[bool, int, float, complex, str, bytes]], 
typing.Sequence[typing.Sequence[typing.Union[
bool, int, float, complex, str, bytes]]], typing.Sequence[typing.Sequence[typing.Sequence[
typing.Union[bool, int, float, complex, str, bytes]]]], 
typing.Sequence[typing.Sequence[typing.Sequence[
typing.Sequence[typing.Union[bool, int, float, complex, str, bytes]]]]]]
is not a generic class
```

**Yikes.** Let's grep around the NumPy issue tracker and see if we can't find anyone shouting vociferously about similar issues. That exception scares me like only grizzly bears snuffling through our compost pile in October can. :open_mouth:

**Comment by skumargupta-jumptrading** [comment]
👋 

Has this support been added to the awesome DOOR api? 

```py
>>> from beartype import beartype
>>> @beartype
... def foo(t: npt.NDArray[np.float64]):
...     print(t)
...
>>> n = np.array([1, 2, 3], dtype=np.float64)
>>> foo(n)
[1. 2. 3.]
```

works great! but...

```py
>>> from beartype.door import TypeHint
>>> TypeHint(npt.NDArray[np.float64])
Traceback (most recent call last):
  Cell In[40], line 1
    TypeHint(npt.NDArray[np.float64])
...
BeartypeDoorNonpepException: Type hint numpy.ndarray[typing.Any, numpy.dtype[numpy.float64]] invalid
(i.e., either PEP-noncompliant or PEP-compliant but currently unsupported by "beartype.door.TypeHint").
```


Thanks for the great library!

**Comment by leycec** [comment]
**Agh!** Your astute observation is correct; the `beartype.door` API currently lacks support for NumPy type hints. I didn't actually realize that anyone except @wesselb and his [wonderful multiple-dispatch Plum crowd](https://github.com/beartype/plum/settings/branches) was even aware of our secretive DOOR API. The more I know, the more powerful @beartype becomes.

Fortunately, we [already have an issue tracking this feature request](https://github.com/beartype/beartype/issues/212)! That's the good news. Unfortunately, I'm inclined to play Japanese role-playing games rather than do actual work... That's the bad news. Tune in to issue #212 to see which wins. :bear:
