### ISSUE TITLE
renaming beartype_test/ to tests/

### ISSUE THREAD

**Issue by WeepingClown13** [beartype/beartype#421]
Hi again,

I am back again as promised.

Now the case this time is a petition to rename beartype_test to tests unless there is a very specific rationale behind the naming. The reason is simple. As a downstream packager, I have a much easier time running the testsuite if it is named tests. For example, currently I run beartype tests from the project root even after building it in a different location (ie, tests are not run with the locally built beartype), and having the directory name as tests would help fix this. This is simply wishlist, but would help a lot if done.

Will I be back again with more chores? In all probability. You'll just have to _bear_ with me!

**Comment by leycec** [comment]
*...heh.* You prefer `tests`, huh? The rationale is disambiguity, mostly. `beartype_test` is a valid Python package <sup>...*more or less!*</sup> that could be installed as such in `/usr/lib/python/site-packages/` directories for anyone so inclined. Clearly, that breaks down if `beartype_test` were ambiguously renamed to merely `tests`. It's also safety. Test suites occasionally get accidentally installed under various use cases. When they're ambiguously named `tests`, disaster ensues. For these sorts of reasons, I'd *really* like to preserve this disambiguity in package nomenclature if I can. This must be an autism thing.

> For example, currently I run beartype tests from the project root even after building it in a different location (ie, tests are not run with the locally built beartype)...

**Right.** This is how `tox` isolation currently works, actually. On each run, `tox` installs @beartype to a temporary path and then runs tests against that path. This ensures that `tox` is testing against a fully installed @beartype package as users would experience it rather than against some weird dev-specific "editable" `pip install -e .` sort of thing.

There are... no problems that I know of with that workflow? But maybe Debian has its own Python testing toolchain with its own expectations and assumptions, which is sorta conflicting with what @beartype wants here? Sadness ensues.

Would it be feasible for you to just symlink or rename the `beartype_test/` subdirectory to `tests/` on your end? I must be missing something, because that doesn't seem *too* arduous. But... *maybe it is*? Maybe everything related to packaging is pure unadulterated hell? Maybe I'm contributing to this hell by polluting your filesystem with crazy `beartype_test/` subdirectories that only generate more misery? Sadness intensifies. :sweat_smile:

**Comment by WeepingClown13** [comment]
@leycec It is absolutely fine if you want to keep it the current way, as I have already mentioned it as wishlist. As you said, there could indeed be enough downstream shenanigans to achieve what I want. Only, the core of my request being the idea not to diverge from what upstream has at all if possible. But it is nothing critical. You can infer part of it as me being lazy. If anything, I am already very glad you took the time to write a detailed explanation. You are a true man of culture.....!!!
