### ISSUE TITLE
[Feature Request] Blacklist Pydantic, which has unleashed a new `typing` hell upon us all :fire: 

### ISSUE THREAD

**Issue by rgallardone** [beartype/beartype#444]
Hey, there!

I've come across a `beartype` exception while using `langchain`, and they have [redirected](https://github.com/langchain-ai/langchain/issues/26898) me here because it seems like the issue is not on their side.

### Example Code

```python
from langchain_core.retrievers import BaseRetriever
from langchain_core.callbacks import CallbackManagerForRetrieverRun
from langchain_core.documents import Document

class CustomRetriever(BaseRetriever):


    def _get_relevant_documents(
        self, query: str, *, run_manager: CallbackManagerForRetrieverRun
    ) -> list[Document]:
        """Get documents relevant to a query.

        Parameters
        ----------
        query : str
            Query to find relevant documents for.
        run_manager : CallbackManagerForRetrieverRun
            Callbacks handler to use.

        Returns
        -------
        list[Document]
            List of relevant documents.
        """
        
        return []
```

### Error Message and Stack Trace (if applicable)

```
>>> from mypackage.test_tool import CustomRetriever
>>> CustomRetriever()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/toti/workspace/.venv/lib/python3.10/site-packages/langchain_core/load/serializable.py", line 110, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/toti/workspace/.venv/lib/python3.10/site-packages/pydantic/main.py", line 211, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "<@beartype(pydantic._internal._model_construction.ModelMetaclass.__new__.wrapped_model_post_init) at 0x118bfacb0>", line 17, in wrapped_model_post_init
  File "/Users/toti/workspace/.venv/lib/python3.10/site-packages/beartype/_check/forward/reference/fwdrefmeta.py", line 149, in __instancecheck__
    return cls.__is_instance_beartype__(obj)
  File "/Users/toti/workspace/.venv/lib/python3.10/site-packages/beartype/_check/forward/reference/fwdrefabc.py", line 111, in __is_instance_beartype__
    return isinstance(obj, cls.__type_beartype__)  # type: ignore[arg-type]
  File "/Users/toti/workspace/.venv/lib/python3.10/site-packages/beartype/_check/forward/reference/fwdrefmeta.py", line 279, in __type_beartype__
    referee = import_module_attr(
  File "/Users/toti/workspace/.venv/lib/python3.10/site-packages/beartype/_util/module/utilmodimport.py", line 295, in import_module_attr
    raise exception_cls(exception_message)
beartype.roar.BeartypeCallHintForwardRefException: Forward reference "BaseModel" unimportable from module "pydantic._internal._model_construction".
```

### Description

I'm using `beartype` to type-check my custom package, called `mypackage`. I'm trying to create a custom `BaseRetriever`, but when I try to instantiate my `CustomRetriever`, `beartype` throws the following exception:

`beartype.roar.BeartypeCallHintForwardRefException: Forward reference "BaseModel" unimportable from module "pydantic._internal._model_construction".`

I believe the exception is also tied to `pydantic`.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
> Python Version:  3.10.14 (main, Sep 18 2024, 09:45:07) [Clang 15.0.0 (clang-1500.3.9.4)]

Package Information
-------------------
> langchain_core: 0.3.5
> langchain: 0.3.0
> pydantic: 2.9.0
> beartype: 0.18.5

**Comment by leycec** [comment]
**Oh, boy.** Pydantic madness, huh? Looks like LangChain internally leverages Pydantic, which internally uses PEP 563-style stringified forward references. Technically, it's likely this is a Pydantic issue. And let's just rummage around in the Pydantic code for one hot minute...

## Yeah. It's a Pydantic Issue.

So, here is what the private `pydantic._internal._model_construction` submodule is doing:

```python
from __future__ import annotations as _annotations
...

if typing.TYPE_CHECKING:
    from ..fields import Field as PydanticModelField
    from ..fields import FieldInfo, ModelPrivateAttr
    from ..fields import PrivateAttr as PydanticModelPrivateAttr
    from ..main import BaseModel
```

We see the multiple problems, I trust. Pydantic is doing everything wrong that it can possibly do, which is quite impressive from a "Top 50 Worst `typing` Mistakes: You Won't Believe What Pydantic Is Doing" perspective but less impressive from a "Can We Just Make Software That Actually Works For Once?" perspective.

These multiple problems are:

1. Pydantic is enabling PEP 563 via the `from __future__ import annotations as _annotations` pragma. Pydantic absolutely should *not* be doing that. Nobody should be doing that. PEP 563 is fundamentally broken at runtime. @beartype does its best to cope with the breaky, but... *still*. Really! Pydantic of all projects should no better. PEP 563 breaking Pydantic was the entire reason that the CPython 3.10 release was infamously delayed by several months. Pydantic developers should no better. PEP 563 nearly destroyed Pydantic. Now, Pydantic internally uses PEP 563 – thus destroying *other* third-party packages attempting to use Pydantic? Sheer madness. The hypocrisy on display is fairly galling here.
2. The `pydantic._internal._model_construction.BaseModel` attribute doesn't actually exist at runtime. Why? Because the `if typing.TYPE_CHECKING:` conditional shown above is only `True` when a pure static type-checker like `mypy` or `pyright` is running. Since @beartype isn't a pure static type-checker, that block never runs and the `BaseModel` class is left undefined. Again, Pydantic should absolutely no better. Since numerous classes and callables defined by the `pydantic._internal._model_construction` submodule reference the undefined `BaseModel` class as a type hint, @beartype has no means of resolving all those undefined `BaseModel` class references.

Would you mind opening up a Pydantic issue about this? Basically, their entire codebase is hostile to runtime type-checkers like @beartype and `typeguard`. Pretty sad, honestly. The emoji cat cries. :crying_cat_face: 

## Oh, and By the Way...

[@beartype 0.19.0 just dropped last night](https://github.com/beartype/beartype/discussions/441), by the way! Consider upgrading. I'd love to hear your thoughts. :hot_face:

**Comment by leycec** [comment]
**Resolved by b647d6b03e463b66cdc.** Our upcoming @beartype 0.19.1 release to be released "shortly" (which is conveniently undefined) now "officially supports" (which means "officially blacklists and mostly ignores") both Pydantic and LangChain. Let's get this ML party started. :partying_face: 

Your excellent example now runs without raising exceptions, @rgallardone. Thanks so much for reporting this superb issue. I had no idea that so many packages hate type hints. If @beartype continues to complain about anything, please submit another issue and I'll get you sorted right away. LangChain + @beartype for the win!

**Comment by rgallardone** [comment]
And also, thanks a lot for the detailed explanation!

**Comment by leycec** [comment]
You're *most* welcome. Oh – and if you find a spare moment lying around, would you mind testing this most recent @beartype commit against your use case? Just:

```python
pip install git+https://github.com/beartype/beartype.git@b647d6b03e463b66cdc70385249ee102d6e5484f
```

LangChain and Pydantic are *kinda* big APIs these days. <sup><- *understatement of the century*</sup> I've tested the minimal working example (MWE) you've so helpfully provided, but other lingering breakage is possible. :grimacing: 

Let's pretend everything works for now.

**Comment by coactive-jeffrey** [comment]
> @leycec: You're _most_ welcome. Oh – and if you find a spare moment lying around, would you mind testing this most recent @beartype commit against your use case? Just:
> 
> ```python
> pip install git+https://github.com/beartype/beartype.git@b647d6b03e463b66cdc70385249ee102d6e5484f
> ```
> 
> LangChain and Pydantic are _kinda_ big APIs these days. <- _understatement of the century_ I've tested the minimal working example (MWE) you've so helpfully provided, but other lingering breakage is possible. 😬
> 
> Let's pretend everything works for now.

Ran this and it works (no more `Forward reference "BaseModel" unimportable` error from `beartype` after running the above `pip` command).

**Comment by leycec** [comment]
**Wondrousness.** We're on the cusp of publishing all this goodness with our upcoming @beartype 0.20.0 stable release, too. Follow all the hot action at #471 if you want the heads-up when the hammer falls.

Thanks again for choosing @beartype for all your runtime QA needs. :smile:

**Comment by simonprovost** [comment]
Amazing discovery! Really amused me! What a nightmare to `TYPE_CHECKING` everywhere ^^

It would be nice to have a Pydantic Vs. Beartype somehow in the documentation / FAQ or somewhere in a long-lasting Issue because a lot of folks coming from the ML side of things tends to blindly trust Pydantic is PEP-Compliant etc, but is it really, uh :) Cheers!

**Comment by leycec** [comment]
You're totally right! We absolutely should document everything we have yet to document, which... is increasingly everything.

[@beartype's current ReadTheDocs (RTD)-hosted documentation site](https://beartype.readthedocs.io) is a Sphinx-driven nightmare I no longer have the intestinal fortitude to maintain. But fear not, Bear Friends! Over at feature request #408, we're tracking long-term plans to build an entirely new Mkdocs-driven GitHub Pages-hosted documentation site that is *not* a nightmare.

The roadmap for this year thus resembles:

* **Release @beartype 0.22.0** this September! 🥳 
* Publicly declare a **soft feature freeze** for the next several months following that! Obviously, critical bugs and other issues will continue to be crushed. But the core idea here is to give me a bit of much-needed breathing space to devote to rewriting all of our documentation with Mkdocs. I weep. 😭 
* **Release that entirely new Mkdocs-driven GitHub Pages-hosted documentation site** by the end of the year! 😏 

Thanks for continuing to care so much, @simonprovost. As always, you're amazing.
