### ISSUE TITLE
[CI] Transition `tox`-based testing from `pip` 😭 to `uv` ⚡

### ISSUE THREAD

**Issue by minmax** [beartype/beartype#448]
## [uv](https://github.com/astral-sh/uv) is super fast.

It's pretty easy to install into the system and once you try it, something switches in you, so it's hard to go back.
```bash
# On macOS and Linux.
$ curl -LsSf https://astral.sh/uv/install.sh | sh

# Linux (*deb)
snap install astral-uv

# On Windows.
$ powershell -c "irm https://astral.sh/uv/install.ps1 | iex"

# With pip.
$ pip install --user uv
```

`tox-uv` test-only dependency will be required for `uv` support in `tox`.

Additionally it may be useful to create a `make install` command that installs `uv` into the home directory and creates a `./.venv` with dependencies installed. But the user will have to edit their `~/.shrc` themselves (to modify PATH).

### And the reason:
Installing all supported pythons, creating environments, installing all dependencies and running tests took me 5 minutes 30 seconds on AMD RYZEN 5 2600 - 3.4/3.9Ghz (turbo).

@leycec pull request approval is possible for this issue?

**Comment by Moosems** [comment]
It may be fast, but it is neither widely adopted nor the accepted standard as pip is. I imagine leycec would appreciate this as an alternative but simply removing pip as an option will very likely be shut down.

**Comment by m3at** [comment]
Uv is cool<sup>and it's written in rust, which gives it an immediate x1000 street-cred boost!</sup>, I use it for most of my new projects and love it. But... is it really useful for beartype? Hatch can [use uv for faster dependencies resolution and env management](https://hatch.pypa.io/latest/how-to/environment/select-installer/#enabling-uv), but is speed currently a problem? If not, adding an extra tool to solve a non-problem might not be needed

**Comment by leycec** [comment]
**Woops.** Extreme apologies for failing to promptly attend to this or your corresponding PR, @minmax. I promised myself I would never "be that GitHub guy." Yet, I'm being that GitHub guy. :cry: 

On the one tentacle, I undeniably like the sound of fixing this...

> Installing all supported pythons, creating environments, installing all dependencies and running tests took me 5 minutes 30 seconds on AMD RYZEN 5 2600 - 3.4/3.9Ghz (turbo).

**That's maybe horrible.** How much of that is just the "running tests" part? If most of that is just the "running tests" part, that's fine for certain definitions of fine. If most of that is *not* just the "running tests" part, that's a new breed of awful.

Wait. `tox` doesn't install Python interpreters. Does it? So "Installing all supported pythons" shouldn't be happening at all. Right? Likewise, "creating environments, installing all dependencies" only happens on the first `tox` invocation. Subsequent `tox` invocations reuse previously spun up environments – until the next CPython bump, anyway.

So... that doesn't leave much for `uv` to optimize away, really. Of course, speed *is* speed. Improving efficiency is always a good thing. <sup>*...or is it?*</sup>

On the other tentacle, I undeniably do *not* like the sound of this...

> I imagine leycec would appreciate this as an alternative but simply removing pip as an option will very likely be shut down.

...and...

> ...but is speed currently a problem? If not, adding an extra tool to solve a non-problem might not be needed.

**Yes! Yes!** So much "Yes!" @Moosems and @m3at know @leycec better than @leycec knows @leycec.

Wait. Is that a Super Meatboy avatar coupled with a l33tsp3@k spelling for "meat", @m3at!?

Wait. We have now veered this crazy train so far off the rails that the train has sprouted wings. Pretty cool train. I suppose this is as good a time as any to admit that I'd love to add **optional** but *not* mandatory support for `uv` to our `tox`-based continuous integration workflow.

Can that be done? Ideally, `tox` could be configured via the top-level `tox.ini` file to:

* If `uv` is installed, `tox` will install dependencies via `uv`.
* Else, `tox` will install dependencies via `pip`.

And... it looks like that can be done. Maybe.

## Onward to QA Golgotha

I couldn't help but grep around for a solution implementing that conditional workflow.

Sadly, `tox-uv` itself currently only unconditionally supports `uv`. Moreover, [the `tox-uv` maintainer has explicitly excluded this functionality from `tox-uv`](https://github.com/tox-dev/tox-uv/issues/16). Ergo, `tox-uv` will *never* conditionally support `pip`. This means we have to paint outside the `tox-uv` lines.

The closest to a working solution I could fine is [this `tox.ini` snippet](https://github.com/tox-dev/tox-uv/issues/16#issuecomment-2031621592) from @griels:

```ini
pip_impl = {env:TOX_PIP_IMPL:pip}
install_command = {env_python} -m {[tox]pip_impl} install {opts} "{packages}" {[tox]isolation_options} -c {[tox]constraints_file} -vvv
```

Certainly, that's better than nothing – but still not quite what @beartype was hoping for. Although that *does* allow one to trivially switch between `pip` and `uv` at `tox` time, that also forces the choice to be hardcoded in the `${TOX_PIP_IMPL}` environment variable. That's *way* too heavyweight here.

We want `install_command` to intelligently select whichever of `pip` or `uv` is currently in the current `${PATH}`, defaulting to `uv` if both are. Can `install_command` be a series of `;`-delimited commands? If so, someone who is not me could probably cobble together an `install_command` script doing just that.

@beartype leaves this an exercise to the reader. Since "the reader" doesn't exist and would never do this even if "the reader" existed, let's quietly close this and hope for better CI from QA Santa this holiday season. :santa: :gift: :christmas_tree:

**Comment by m3at** [comment]
To answer the important question:
> Is that a Super Meatboy avatar coupled with a l33tsp3@k spelling for "meat", @m3at!?

Yes. 😇 

Thanks for the work on beartype, and the delightful comments ❤️
