### ISSUE TITLE
Can `BeartypeConf(hint_overrides=...)` accept a callable instead please?

### ISSUE THREAD

**Issue by patrick-kidger** [beartype/beartype#453]
I have a case where I would like all 'leaf' annotations `x` to be replaced by `x | foo` for a certain `foo`. That is, I would like to transform hints under the following function:
```python
def hint_override(hint):
    if get_origin(hint) is None:
        return Union[hint, foo]

# `int` becomes `int | foo`
# `dict[str, str]` becomes `dict[str | foo, str | foo]`
# etc.
```
for which the current mapping-based approach is not sufficient. :(

**Comment by leycec** [comment]
**Fascinating...** and horrifying! I'd better not ask too many questions here. You want something ominous and dangerous to happen. That's all I know – and I'm all for it. :laughing: 

Thankfully, @beartype *might* already support this special darkness out-of-the-box. Why? Because `beartype.BeartypeHintOverrides` is a `dict` subclass. In theory, you *should* be able to trivially define your own `EvilHintOverrides` subclass overriding the `get()` and/or `__getitem__()` dunder methods to do what you want. Maybe? No idea, actually. The only spanner in the works might be that `beartype.BeartypeHintOverrides` is a *frozen* `dict` subclass. *Oh, yeah.* In reflection, that's a spanner. Hashability and what not. I sigh.

Still, let's pretend this totally untested monstrosity works as advertised:

```python
from beartype import beartype, BeartypeConf, BeartypeHintOverrides
from typing import Literal, Union, get_origin

foo = Literal['Suck an egg, @beartype. Suck that egg!']

class EvilHintOverrides(BeartypeHintOverrides):
    '''
    Evil incarnate now walks amongst us.
    '''

    def __hash__(self) -> int:
        return id(self)  # <-- it's best not to ask

    def get(self, key: object, default: object = None) -> object:
        if get_origin(key) is None:
            # print(f'Evilifying {repr(key)} -> {repr(Union[key, foo])}!')
            return Union[key, foo]

        return super().get(key, default)

@beartype(conf=BeartypeConf(hint_overrides=EvilHintOverrides()))
def evil_func(evil_arg: int) -> int:
    print(f'evil_arg: {repr(evil_arg)}')
    return evil_arg

evil_func(42)
evil_func('Suck an egg, @beartype. Suck that egg!')
evil_func('This cannot be!?!?')
```

*lol.* I lied and ended up testing it. Looks... fine, shockingly? The only issue is that the trailing call to `evil_func()` should raise a readable `BeartypeCallHintParamViolation`. Instead, it raises a *super*-unreadable `typing` exception that kinda reads like a `typing` bug pertaining to the `typing.Literal[...]` type hint factory. No idea, honestly. Or maybe @beartype is subtly bugged somewhere? *More than likely, @beartype is to blame.*

Would you mind playing around with that a bit on your end? If that suffices for you, superb! Else, there might be some sort of an obscure `typing` or @beartype issue. Let's reopen this if @beartype continues falling down for you.

Alternately... maybe we should publicly document this? It's kinda low-level and kludgy. The `__hash__()` override is hacky AF and deeply suspicious. Perhaps we'd better pretend that @beartype can't do this at all. :rofl:

**Comment by patrick-kidger** [comment]
Haha, thankyou! I originally gave the `__getitem__` approach a try myself and couldn't quite get it to work. When I circle back around to this I'll give you snippet here a go and let you know how things go :)
