### ISSUE TITLE
[Feature Request] Blacklist `xarray`, which has unleashed a new typing hell upon us all 🔥 

### ISSUE THREAD

**Issue by fbartolic** [beartype/beartype#456]
When using `beartype` with `xarray.Dataset` as a type hint, it fails with a `BeartypeCallHintForwardRefException`. However, it works fine with `xarray.DataArray`.

 Minimal reproducible example:
 
```Python
 import xarray as xr
 from beartype import beartype

 @beartype
 def process_data(data: xr.Dataset):
     print(f"Processing data of type: {type(data)}")

 ds = xr.Dataset({"temperature": (["x", "y"], [[20, 25], [30, 35]])})
 process_data(ds)  # This fails
  ```

 Versions:
 beartype: `0.18.5`
 xarray: `2024.9.0`
 Python: `3.11.10 `

**Comment by leycec** [comment]
**lol.** So even xarray hates @beartype. I may not have had that on my 2024 Bingo Card, but I remain unsurprised.

When you find a spare minute, would you mind copy-pasting the full exception traceback that you're seeing? Probably, this is an upstream xarray issue – *but maybe it isn't.* Maybe this is actually @beartype's fault. Maybe there's something immediate and helpful we can do for everyone.

Also, predicting the weather using ML sounds so fun. The eastern seaboard of the continental U.S. just got grandslammed by a horrifying and shocking weather anomaly. Please tell me that AI-based weather prediction will be able to predict and ameliorate this sort of thing with better reliability. The future of humanity is in your awesome hands, @fbartolic! :pleading_face:

**Comment by fbartolic** [comment]
Here's the traceback:

```
{
	"name": "BeartypeCallHintForwardRefException",
	"message": "Forward reference \"DataArray\" unimportable from module \"__main__\".",
	"stack": "---------------------------------------------------------------------------
BeartypeCallHintForwardRefException       Traceback (most recent call last)
Cell In[1], line 12
      8     print(f\"Processing data of type: {type(data)}\")
     11 ds = xr.Dataset({\"temperature\": ([\"x\", \"y\"], [[20, 25], [30, 35]])})
---> 12 process_data(ds)  # This fails

File <@beartype(__main__.process_data) at 0x7f24a373b4c0>:41, in process_data(__beartype_object_94491774531008, __beartype_object_94491746877504, __beartype_object_94491746859376, __beartype_get_violation, __beartype_conf, __beartype_object_94491776848304, __beartype_check_meta, __beartype_func, *args, **kwargs)

File /opt/miniconda3/envs/salient/lib/python3.11/site-packages/beartype/_check/forward/reference/fwdrefmeta.py:148, in BeartypeForwardRefMeta.__instancecheck__(cls, obj)
    124 '''
    125 :data:`True` only if the passed object is an instance of the external
    126 class referenced by the passed **forward reference subclass** (i.e.,
   (...)
    143     class referenced by this forward reference subclass.
    144 '''
    146 # Return true only if this forward reference subclass insists that this
    147 # object satisfies the external class referenced by this subclass.
--> 148 return cls.__is_instance_beartype__(obj)

File /opt/miniconda3/envs/salient/lib/python3.11/site-packages/beartype/_check/forward/reference/fwdrefabc.py:111, in BeartypeForwardRefABC.__is_instance_beartype__(cls, obj)
     89 '''
     90 :data:`True` only if the passed object is an instance of the external
     91 class referred to by this forward reference.
   (...)
    102     class referred to by this forward reference subclass.
    103 '''
    105 # # Resolve the external class referred to by this forward reference and
    106 # # permanently store that class in the \"__type_beartype__\" variable.
    107 # cls.__beartype_resolve_type__()
    108 
    109 # Return true only if this object is an instance of the external class
    110 # referenced by this forward reference.
--> 111 return isinstance(obj, cls.__type_beartype__)

File /opt/miniconda3/envs/salient/lib/python3.11/site-packages/beartype/_check/forward/reference/fwdrefmeta.py:304, in BeartypeForwardRefMeta.__type_beartype__(cls)
    301 EXCEPTION_PREFIX = 'Forward reference '
    303 # Forward referee dynamically imported from this module.
--> 304 referee = import_module_attr(
    305     attr_name=cls.__name_beartype__,
    306     module_name=cls.__scope_name_beartype__,
    307     exception_cls=EXCEPTION_CLS,
    308     exception_prefix=EXCEPTION_PREFIX,
    309 )
    311 # If this referee is this forward reference subclass, then this
    312 # subclass circularly proxies itself. Since allowing this edge case
    313 # would openly invite infinite recursion, we detect this edge case
    314 # and instead raise a human-readable exception.
    315 if referee is cls:

File /opt/miniconda3/envs/salient/lib/python3.11/site-packages/beartype/_util/module/utilmodimport.py:295, in import_module_attr(attr_name, module_name, exception_cls, exception_prefix)
    291             exception_message += (
    292                 f' from unimportable module \"{module_name}\".')
    294     # Raise this exception.
--> 295     raise exception_cls(exception_message)
    296 # Else, this module declares this attribute.
    297 
    298 # Else, return this attribute.
    299 return module_attr

BeartypeCallHintForwardRefException: Forward reference \"DataArray\" unimportable from module \"__main__\"."
}
```

Upgrading to `0.19.0` doesn't change anything :/.

>Also, predicting the weather using ML sounds so fun. The eastern seaboard of the continental U.S. just got grandslammed by a horrifying and shocking weather anomaly. Please tell me that AI-based weather prediction will be able to predict and ameliorate this sort of thing with reliability. The future of humanity is in your awesome hands! 🥺

It's tons of fun! 

Although we're not focused on short-term forecasts for hurricanes tracks and similar, I think they will continue to improve gradually because of recent developments in AI. It's not just the forecasts though, there's a lot of room for improving the decision-making process given a particular forecast. Say, what you do if the probability of a hurricane making landfall increases from 0.1% to 5%.

**Comment by leycec** [comment]
**lol.** Yeah. `xarray` is busted. More specifically, `xarray` is **fundamentally incompatible with runtime type-checking**.

This isn't @beartype's fault. I swear! Let's dig into this unto we both feel like passing out onto our keyboards. :tired_face: 

## How Bad Could It Possibly Be?

It's bad, bro.

The `xarray.Dataset` class is defined by the `xarray.core.dataset` submodule. So far, so good. The `xarray.core.dataset.Dataset` class subclasses the PEP 585 generic `Mapping[Hashable, "DataArray"]` subscripted by the PEP 484 relative forward reference `"DataArray"`. So far, so good. The `DataArray` class is undefined at runtime in this submodule. Wait. What? That's horrible!

It's all true. Here's what `xarray.core.dataset` is doing:

```python
from typing import IO, TYPE_CHECKING, Any, Generic, Literal, cast, overload
...

if TYPE_CHECKING:
    ...
    from xarray.core.dataarray import DataArray

...

class Dataset(
    DataWithCoords,
    DatasetAggregations,
    DatasetArithmetic,
    Mapping[Hashable, "DataArray"],
):
```

See that `if TYPE_CHECKING:` block? Crucially, `TYPE_CHECKING` is `True` *only* at **static analysis time** (i.e., when a pure static type-checker like `mypy` or `pyright` is running outside of the CPython runtime). This means that the `DataArray` class is undefined at runtime. Since the `DataArray` class is undefined, @beartype correctly fails to type-check the `Dataset` class that references the undefined `DataArray` class.

## I Don't Like What I'm Hearing

Right? `xarray` violates core `typing` standards and thus *cannot* be type-checked at runtime. Here's what we should now do, probably:

* **@beartype should internally blacklist `xarray`** (i.e., silently avoid type-checking *anything* pertaining to `xarray`).
* Somebody should submit an upstream issue at the `xarray` issue tracker politely requesting that they stop doing what they're doing. The `typing.TYPE_CHECKING` global is hostile to runtime type-checking and should basically *never* be used by anybody ever – especially for forward references. Instead, `xarray` should just use standard PEP 484 absolute forward references ala:

```python
class Dataset(
    DataWithCoords,
    DatasetAggregations,
    DatasetArithmetic,
    Mapping[Hashable, "xarray.core.dataarray.DataArray"],  # <-- this is all @beartype asks
):
```

Will `xarray` do that? *Probably not.* This issue is actually extremely similar to a [recent Pydantic issue](https://github.com/beartype/beartype/issues/444). The underlying issue is the same in both cases. So is the solution: @beartype, **blacklist these crazy peeps!** :zany_face: 

## Hurricanes! Hurricanes Everywhere!

Also, you are *so* right about everything:

> there's a lot of room for improving the decision-making process given a particular forecast.

*...heh.* This is a nice way of saying "crazy politics," isn't it? Indeed, one of the political parties in the United States (who shall remain nameless) has campaigned on a platform of gutting all funding for federal meteorological forecasting. Relatedly, this is why one of many reasons why I live in Canada.

It's interesting. Not even good politics would have saved North Carolina this time. Forecasting predicted calamitous landfall in northern Florida (which was then mandatorily evacuated) but *not* the interior of North Carolina (which was then mostly ignored until it was all over). I am ignorant, but this does seem to have been a widespread modelling failure.

Thus, AI. Save us from inadequate predictions, my AI Weather Overlords! Canada is begging you here.

**Comment by fbartolic** [comment]
Thanks so much for digging into this! 

So you don't think it's worth raising an issue with `xarray`?

**Comment by leycec** [comment]
**Gah!** Apologies for the confusion. I should haven spoken more plainly. Alas, I talk too much.

It's *definitely* worth raising an issue with `xarray`. If @beartype has issues with this, every other runtime type-checker has issues with this. And thanks so much for reporting this issue here (and in such detail), @fbartolic. Our upcoming @beartype 0.19.1 patch release will get this squared away for you in a jiffy. :+1:

**Comment by leycec** [comment]
**Resolved by b49ea71.** Would you mind testing this @beartype commit against your codebase? Although your exact example now runs, there might be other unforeseen explosions somewhere. Just:

```bash
pip install git+https://github.com/beartype/beartype.git@b49ea71ad5451cf92ec8d7331830fcf2c07c5126
```

So, I have good news and I have bad news about all this. Let's start with...

* The good news is that your example now runs. :partying_face:
* The bad news is that **@beartype now unconditionally ignores everything from `xarray`.** This means that @beartype no longer type-checks `xarray.Dataset` or `xarray.DataArray` objects or... well, *anything* that is `xarray`, really. :sob: 

Running is better than breaking. But type-checking is better than no type-checking! Thus, this "resolution" is sucky.

A much healthier resolution would be for `xarray` themselves to resolve this on their end. If you *do* find the time to submit an upstream `xarray` issue about this, that would be wondrous. Please ping me with @leycec; I'll help explain to the `xarray` devs in long-winded detail exactly what runtime type-checkers like @beartype and `typeguard` need to make `xarray` type-checkable at runtime.

Thanks again, @fbartolic. So sorry that @beartype couldn't do more for you here. :face_exhaling:

**Comment by headtr1ck** [comment]
> xarray violates core typing standards and thus cannot be type-checked at runtime.

Could you point me to this standard? Where is it written that this should be avoided?

As far as I can tell, this `if TYPE_CHECKING` block is used to prevent circular imports and is purely used to resolve the generic type (not required by the runtime?)

**Comment by fbartolic** [comment]
> Resolved by https://github.com/beartype/beartype/commit/b49ea71ad5451cf92ec8d7331830fcf2c07c5126. Would you mind testing this https://github.com/beartype commit against your codebase? Although your exact example now runs, there might be other unforeseen explosions somewhere. Just:

Thank you! Seems to be working fine.
