### ISSUE TITLE
random check on sequetial 

### ISSUE THREAD

**Issue by im-Kitsch** [beartype/beartype#466]
Hi, first of all, thank for the good work.

 I find it's super slow for sequential data, for example, `foo(a: list[int])`, if a is list with long length like 1000000. The type check speed is super slow. As I know, beartype is super fast since the type check is randomly executed.  

I wonder if type check could be randomly executed on the long list. 

If there is already discussions about this, then please just close this issue.

Best.

**Comment by im-Kitsch** [comment]
An example 
```
import time
@beartype
def test(a: list[int]):
    return a

a = [np.random.random(10) for i in range(int(1e5))]

t0 = time.time()
[isinstance(_a_i, int) for _a_i in a]
print('manually test', time.time() - t0)

t0 = time.time()
try:
    test(a)
finally:
    print('auto check',  time.time() - t0)


```
Manully check is just 0.002 s while auto check costs more than 5s, it's really weired.

**Comment by leycec** [comment]
**lol.** NumPy, huh? You may not believe this, but NumPy is slow. @beartype is *always* fast, because that's pretty much all @beartype does: raw speed. NumPy, on the other hand? It's painfully slow. That's why increasingly all of us have switched to GPU compute (e.g., JAX, PyTorch).

Specifically, the [public `numpy.array2string()` function](https://numpy.org/doc/stable/reference/generated/numpy.array2string.html#numpy.array2string) underlying the `numpy.ndarray.__repr__()` dunder method invoked when @beartype internally calls the `repr()` builtin to render the contents of your passed NumPy array as a human-readable string... is **stupidly slow.** It's so slow, I feel stupider just contemplating its ponderous slowness. Why is it so slow? Because:

* `numpy.array2string()` is implemented in **pure-Python** – literally the slowest language humanity has yet devised. Moreover...
* `numpy.array2string()` is implemented **recursively** – literally the worst possible thing you can ever do in pure-Python if you care about either speed *or* not exhausting the finite stack. Don't even get @leycec started on recursion in Python. :laughing: :sob: 

You can validate NumPy's stupidity by [manually inspecting the private `numpy._core.arrayprint._array2string()` function](https://github.com/numpy/numpy/blob/c045306a188f19d7f919512638bd5f02724c9c7e/numpy/_core/arrayprint.py#L566), which is at the heart of this whole fiasco. Sheer madness that they implemented this in pure-Python. I shudder, bro. I shudder. 

## The Proof Is in the Profiling Pudding

**Behold!** NumPy sucks harder than any tensor framework has ever sucked:

```python
from beartype import beartype
import numpy as np
import time

def test_unchecked(lst: list[int]):
    return lst

test_beartyped = beartype(test_unchecked)
a = [np.random.random(10) for i in range(int(1e5))]

t0 = time.time()
try:
    test_unchecked(a)
finally:
    print('unchecked call',  time.time() - t0)

t0 = time.time()
try:
    repr(a)
finally:
    print('numpy array repr',  time.time() - t0)

t0 = time.time()
try:
    test_beartyped(a)
finally:
    print('beartyped check',  time.time() - t0)
```

...which prints (much to our collective horror):

```
unchecked call 5.9604644775390625e-06
numpy check 22.002719163894653
auto check 45.36865973472595
Traceback (most recent call last):
  File "/home/leycec/tmp/bear/profile_badstuff.py", line 28, in <module>
    test_beartyped(a)
    ~~~~~~~~~~~~~~^^^
  File "<@beartype(__main__.test_unchecked) at 0x7fc9dee27100>", line 39, in test_unchecked
beartype.roar.BeartypeCallHintParamViolation: Function __main__.test_unchecked() parameter lst=[array([0.10707116, 0.97750919, 0.03726412, 0.70011024, 0.70292419,
       0.07850488, 0.4...])] violates type hint list[int], as list index 25448 item <class "numpy.ndarray"> "array([0.5275426 , 0.25691856, 0.77531528, 0.87830658, 0.17324984,
       0.10349288, 0.4...])" not instance of int.
```

See what's happening there? NumPy is stupid. NumPy takes **22 seconds** to produce the `repr()` string for a single list containing only **100,000** one-dimensional NumPy arrays each containing only **10** 64-bit floating point numbers.

@beartype is exactly twice as slow, because @beartype internally calls `repr()` twice:

1. Once to produce the `repr()` for the outermost list of all NumPy arrays.
2. Again to produce the `repr()` for a randomly selected NumPy array from that list.

@beartype is optimally efficient here. Since NumPy is outside @beartype's control, @beartype's paws are tied here. NumPy being stupid is NumPy's fault – *not* @beartype's. What we're saying is...

## You Have Two Options Here (And You're Not Gonna Like Either)

1. **Option 1:** Submit an upstream NumPy issue encouraging them to optimize their blatantly slow `numpy.array2string()` function. Of course, they'll probably just laugh and then never do anything. There's a reason everybody has switched from NumPy to fully parallelized tensor packages: **NumPy devs mostly do not care about speed.** You care about speed, though. Should you still be using NumPy? Probably... *not.*
2. **Option 2:** Switch from NumPy to a competing tensor package that actually cares about speed. JAX and PyTorch are both fantastic options in this space. This is what I'd do, frankly. NumPy is no longer worth anyone's time in 2024 – unless you're just slinging some casual impromptu data science in a Jupyter notebook where speed doesn't particularly matter. In that case, sure; NumPy's fine. In production environments, though, NumPy's really *not* fine.

Do what @leycec would do. Yup. It's **option 2!** :partying_face: :sob: 

## P-p-please Make This Work Somehow! I'm Begging You!

Thanks so much for opening up this fascinating issue, @im-Kitsch. Sadly, our paws are tied. The ball is entirely in NumPy's court.

Actually, in theory, @beartype *could* internally call the `repr()` function for NumPy arrays from within a `with np.printoptions(threshold=10):` context manager. Doing so appears to mildly speed up NumPy's internal array formatting – but only by a few seconds. Given that NumPy's internal array formatting is on the order of **tens of seconds,** shaving off a few seconds harmly seems worthwhile. Still, here's what the profiling resembles when we do that:

```python
from beartype import beartype
import numpy as np
import time

def test_unchecked(lst: list[int]):
    return lst

test_beartyped = beartype(test_unchecked)
a = [np.random.random(10) for i in range(int(1e5))]

t0 = time.time()
try:
    test_unchecked(a)
finally:
    print('unchecked call',  time.time() - t0)

t0 = time.time()
try:
    with np.printoptions(threshold=10):
        repr(a)
finally:
    print('numpy array repr',  time.time() - t0)

t0 = time.time()
try:
    test_beartyped(a)
finally:
    print('beartyped check',  time.time() - t0)
```

...which prints:

```
unchecked call 5.9604644775390625e-06
numpy check 19.46793818473816
auto check 45.36865973472595
Traceback (most recent call last):
  File "/home/leycec/tmp/bear/profile_badstuff.py", line 28, in <module>
    test_beartyped(a)
    ~~~~~~~~~~~~~~^^^
  File "<@beartype(__main__.test_unchecked) at 0x7fc9dee27100>", line 39, in test_unchecked
beartype.roar.BeartypeCallHintParamViolation: Function __main__.test_unchecked() parameter lst=[array([0.10707116, 0.97750919, 0.03726412, 0.70011024, 0.70292419,
       0.07850488, 0.4...])] violates type hint list[int], as list index 25448 item <class "numpy.ndarray"> "array([0.5275426 , 0.25691856, 0.77531528, 0.87830658, 0.17324984,
       0.10349288, 0.4...])" not instance of int.
```

A mere three second gain hardly seems worth it. It's not even a reliable three seconds, either. Sometimes it's slightly faster; sometime it's just as slow. What are you even doing, NumPy!?

@beartype thus wisely chooses to close this issue and pretend this never happened. I'm *sooooo* sorry. Let us all weep for NumPy.

**Comment by im-Kitsch** [comment]
Hi, @leycec 

thanks a lot for the detailed interpretation. I really learned many things. I never thought it's numpy's problem. I find that every typechecking related to numpy is annoying. Either function entry or annoation with `list[np.ndarray]` makes speed very slow. I would change my code and avoid numpy.

Howevery, I tried also torch and jax, but both torch and jax are also slow, in my machine , in the following code it costs 4.6s and 11.6s respectively.  I wonde why `repr()` function is needed for type check.  Is it only needed for raise Exception with unmatched typecheck or is it also used in typecheck?

Thanks in advance.

```python
from beartype import beartype
import numpy as np
import time
import torch
import timeit
import jax

def torch_unchecked(lst: list[int]):
    return lst

torch_beartyped = beartype(torch_unchecked)
torch_list = [torch.arange(10) for i in range(int(1e5))]

t0 = time.time()
try:
    torch_beartyped(torch_list)
except Exception as e:
    pass
finally:
    print('list torch betype check',  time.time() - t0)
    

key = jax.random.PRNGKey(0)
jax_keys = jax.random.split(key, int(1e5))
jax_array = [jax.random.normal(_key, (10, )) for _key in jax_keys]

def jax_unchecked(lst: list[int]):
    return lst

jax_beartyped = beartype(jax_unchecked)
t0 = time.time()
try:
    jax_beartyped(jax_array)
except Exception as e:
    pass
finally:
    print('list jax beartype check', time.time() - t0)
```

**Comment by leycec** [comment]
**lol.** Everybody sucks, huh? Thanks so much for profiling everything. Ideally, parallelized tensor APIs like JAX and PyTorch should also be parallelizing their array `__repr__()` implementations. But... it looks like nobody is doing that. Everybody probably thought, "Slow array `__repr__()` implementations are fine. Why optimize what nobody needs?"

Everybody failed to realize that runtime type-checkers actually do need *reasonably* fast `__repr__()` implementations. @beartype doesn't even need super-fast `__repr__()` implementations. It just needs `__repr__()` implementations that return strings within the known lifetime of the Universe. And... this is why my belly hurts. :laughing: 

Thankfully, you're in luck. Why? Because...

> I wonder why `repr()` function is needed for type check.

It isn't! Yay! Party on, @beartype. :partying_face: 

Why? Because...

> Is it only needed for raise `Exception` with unmatched typecheck...

**Yup.** That's it exactly, @im-Kitsch. @beartype only calls `repr()` to produce human-readable exception messages on type-checking violations. Ideally, nothing should ever violate a type-check. Right? So, it's *sorta* okay that tensor `__repr__()` implementations are so unbelievably slow.

...*sorta.* :sweat: 

> ...or is it used in every typecheck?

**Nope!** Type-checks that pass <sup>*...which should be all of them, right?*</sup> never call `repr()`. @beartype fully protects you from everybody's incompetence.

Phew. What a rough issue, huh? Let's make dinner and pretend this never happened.

**Comment by im-Kitsch** [comment]
thanks for the reply, haha, Let's make dinner and pretend this never happened.
