### ISSUE TITLE
Adding support for numpys abstract classes with NDArray, e.g. NDArray[np.floating]

### ISSUE THREAD

**Issue by braniii** [beartype/beartype#48]
Again me, sorry for opening so many issues. In the [README#numpy-type-hints](https://github.com/beartype/beartype#numpy-type-hints) the usage of NDArray is explained. Beartype uses `IsAttr` combined with `IsEqual` for transforming the `NDArray` to an amazing beartype validator. This works only for explicit dtypes. Using `np.floating`it will be casted to `np.float64`. The problem is on numpys side, that `np.dtype(np.floating)` is deprecated.
```Python
import numpy as np
from beartype import beartype
from beartype.vale import Is, IsAttr, IsEqual
from typing import Annotated
from numpy.typing import NDArray

# Defining an array allowing all floats does not work, in both cases it is casted to np.float64
# and a deprecation warning is printed:
# <stdin>:2: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
NumpyFloatArray = NDArray[np.floating]  # is casted by beartype to np.float64 with printed warning
NumpyFloatArray = Annotated[  # this is casted by beartype as well
    np.ndarray, IsAttr['dtype', IsEqual[np.dtype(np.floating)]]]
# a working alternative is (taken again from the README)
NumpyFloatArray = Annotated[
    np.ndarray, Is[lambda arr: np.issubdtype(arr.dtype, np.floating)]]

```

There is a working solution (also from the README) by using `Is[lambda arr: np.issubdtype(arr.dtype, np.floating)]`. So there is no hurry at all.

In my mind there is a simple solution, but probably only because I do not know the source code. If it is a dump idea, feel free to ignore it :see_no_evil:.
Maybe one could add additionally an `IsSubclass` which checks, obviously :sweat_smile: , for subclasses.
```Python
NumpyFloatArray = Annotated[
    np.ndarray, IsAttr['dtype', IsSubclass[np.floating]]]
```

Then one needs to catch if `NDArray` is used with one of the abstract subclasses
`np.floating, np.integer, np.signedinteger, np.unsignedinteger, np.inexact, np.complexfloating` and then the `IsEqual` calls needs to be replaced by `IsSubclass`.

**Comment by leycec** [comment]
> Again me, sorry for opening so many issues.

I love these issues. Please never stop spamming me. ← <sub>*the only time i said that willingly*</sub>

> The problem is on numpys side, that `np.dtype(np.floating)` is deprecated.

**Yup.** NumPy used to be a *whole* lot looser than it currently is. Thankfully, those days are ending. Unfortunately, those days are ending.

My wife and I co-authored [this whole biosimulator thingamajigger complete with gene regulatory networks and more bells, test tubes, and ear-splitting whistles than you can shake a wooden pirate leg at](https://gitlab.com/betse/betse) a few years back. It increasingly no longer works because everything we coded assumed NumPy would "do the right thing" regardless of what you threw at it. Now, NumPy refuses. We miss the bad old behaviour – even if it was bad and old.

In this case, silently casting `np.dtype(np.floating) == np.dtype(float64)` was clearly a bad thing for NumPy to do. Did anyone actually know NumPy was doing that? It makes sense in hindsight, but... *yikes.*

> So there is no hurry at all.

**Thank the Gods.** If anyone needs me, I'll be out back drip-feeding a steady diet of Japanese role-playing games directly into my head.

> In my mind there is a simple solution, but probably only because I do not know the source code.

**Brilliant!** Simple solutions [KISS](https://en.wikipedia.org/wiki/KISS_principle), which might also be the worst Dad Rock Band ever.

I was mildly concerned the various floating-point scalar data types (e.g., `np.float32`, `np.float64`) might not actually be subclasses of `np.floating`. After all, why would NumPy even define the `np.issubdtype()` tester if you could just call the `issubclass()` builtin directly? Right?

My concerns were unfounded:

```
>>> import numpy as np
>>> issubclass(np.float64, np.floating)
True
```

It's a miracle on Earth. On the bright side, this means that adding a new `beartype.vale.IsSubclass` validator is TheRightThingToDoHereAbsolutely™. By your command, it shall be done. On the dark side, I now have *no* idea why `np.issubdtype()` even exists; it doesn't need to, yet there it is. Like an octopus clinging to your cat's face, it simply should not be.

> Then one needs to catch if `NDArray` is used with one of the abstract subclasses
`np.floating`, `np.integer`, `np.signedinteger`, `np.unsignedinteger`, `np.inexact`, `np.complexfloating` and then the `IsEqual` calls needs to be replaced by `IsSubclass`.

This is clever, too. I have one concern that concerns me:

1. **What does mypy say?** Interestingly, `numpy.typing` is actually a mypy plugin, which means that mypy has something to say. Whatever mypy does, beartype also should do. Mypy is the de-facto typing standard. Mypy's Word Is Law.

I suspect mypy will outright reject NumPy type hints subscripted by abstract base classes (e.g., `NDArray[np.floating]`). It would be fascinating if mypy implicitly both accepts those hints *and* enforces subclass rather than equality constraints against them, but... that seems overly optimistic. Mypy is the [Soup Nazi](https://www.youtube.com/watch?v=euLQOQNVzgY) of the Python world.

When you find a spare moment, would you mind investigating that for us all? In the meanwhile, I'll see if I can't spin up a new `beartype.vale.IsSubclass` validator. *Dis gunna be fun.*

**Comment by leycec** [comment]
*I couldn't help myself.* I'm supposed to either be doing "meaningful productive work" or just binging anime for two weeks straight. Instead, here we are – spelunking deep within the unlit caverns of another semantic typing rabbit hole, where none but GitHub hobos dare to tread:

```
$ cat <<'EOF' > muh_data_science.py
from numpy import asarray, floating, float64, int64, integer
from numpy.typing import NDArray

def muh_data_func(muh_array: NDArray[floating]):
    return muh_array.round()

muh_float_array: NDArray[float64] = asarray((
    3.0, 3.1, 3.14, 3.141, 3.1415, 3.14159, 3.141592))
muh_int_array: NDArray[int64] = asarray((
    3, 0, 3, 1, 3, 14, 3, 141, 3, 1415, 3, 14159, 3, 141592))

print(muh_data_func(muh_float_array))
print(muh_data_func(muh_int_array))

$ mypy muh_data_science.py
maso.py:16: error: Argument 1 to "muh_data_func" has incompatible type "ndarray[Any, dtype[signedinteger[_64Bit]]]"; expected "ndarray[Any, dtype[floating[Any]]]"
Found 1 error in 1 file (checked 1 source file)
```

At this point, you might be thinking: "*Uh oh.* That's bad, right?"

Actually... **that's great!** Mypy + NumPy correctly decides that an array of type `NDArray[float64]` but *not* `NDArray[int64]` satisfies the type hint `NDArray[floating]`. That means we're all in luck. NumPy's bundled mypy plugin does, indeed, appear to be transparently type-checking arbitrary dtypes against `np.floating` by calling either `issubclass()` or `np.issubdtype()`. Somebody did something good for once, everybody!

That means the next stable release of beartype will follow suite and do the exact same good thing. Let us now prepare for the long journey ahead by binging anime for two weeks straight.

**Comment by braniii** [comment]
Sorry for not investigating, I was on a short holiday trip. But that is great news :tada:

**Comment by leycec** [comment]
**Success!** This quest has been transgressed with success. Thanks to cb9af0c, beartype now transparently supports `numpy.typing.NDArray` type hints subscripted by any of three possible types of objects:

* An **array dtype** (i.e., instance of the `numpy.dtype` class).
* A **scalar dtype** (i.e., concrete subclass of the `numpy.generic` ABC).
* A **scalar dtype ABC** (i.e., abstract subclass of the `numpy.generic` ABC).

See our [voluminous documentation on the subject for excruciating details that will make you wish you'd done something else with your Saturday](https://github.com/beartype/beartype#typed-numpy-arrays). It also reliably induces cluster migraines and chronic fatigue in susceptible children. <sup>*...what you gonna do*</sup>

Thanks again for the fantastic feature request, Dan! Hit us up again if you stumble into anything else that looks *sus af*. Until then, enjoy all the blindingly fast runtime type-safety we have to offer. :dash:
