### ISSUE TITLE
beartype performance is substantially slower than no beartype

### ISSUE THREAD

**Issue by mpenning** [beartype/beartype#58]
Hello,

I was quite interested when I found [this stackoverflow answer about beartype](https://stackoverflow.com/a/37961120/667301)... As a POC, I cooked up a performance test using [beartype](https://github.com/beartype/beartype), [Enthought traits](https://github.com/enthought/traits), [traitlets](https://github.com/ipython/traitlets), and plain-ole-python-ducktyping...

But... I found that beartype was pretty slow in my test.... As an attempt to be as fair as possible, I used `assert` to enforce types in my duck-typed function (ref - `main_duck()`)...

I also confess that Enthought traits are compiled, so the Enthought traits data below is mostly just an FYI...

Running my comparison 100,000 times...
```shell
$ python test_type.py
timeit duck getattr time: 0.0395 seconds
timeit duck assert  time: 0.0417 seconds
timeit traits       time: 0.0633 seconds
timeit traitlets    time: 0.5236 seconds
timeit bear         time: 0.0782 seconds
$
```

**Question**
Am I doing something wrong with bear-typing (ref my POC code below)?  Is there a way to improve the "beartyped" performance?

My rig...
- Linux under VMWare (running on a Lenovo T430); kernel version `4.19.0-12-amd64`
- Python 3.7.0
- [beartype](https://github.com/beartype/beartype/) version 0.8.1
- [Enthought traits](https://github.com/enthought/traits) version 6.3.0
- [traitlets](https://github.com/ipython/traitlets), version 5.1.0

```python
from beartype import beartype

from traits.api import HasTraits as eHasTraits
from traits.api import Unicode as eUnicode
from traits.api import Int as eInt

from traitlets import HasTraits as tHasTraitlets
from traitlets import Unicode as tUnicode
from traitlets import Integer as tInteger

from timeit import timeit

def main_duck_getattr(arg01="__undefined__", arg02=0):
    """Proof of concept code implenting duck-typed args and getattr"""
    getattr(arg01, "capitalize")  # Type-checking with attributes
    getattr(arg02, "to_bytes")    # Type-checking with attributes

    str_len = len(arg01) + arg02
    getattr(str_len, "to_bytes")
    return ("duck_bar", str_len,)

def main_duck_assert(arg01="__undefined__", arg02=0):
    """Proof of concept code implenting duck-typed args and assert"""
    assert isinstance(arg01, str)
    assert isinstance(arg02, int)

    str_len = len(arg01) + arg02
    assert isinstance(str_len, int)
    return ("duck_bar", str_len,)


class MainTraits(eHasTraits):
    """Proof of concept code implenting Enthought traits args"""
    arg01 = eUnicode()
    arg02 = eInt()
    def __init__(self, *args, **kwargs):
        super(MainTraits, self).__init__(*args, **kwargs)

    def run(self, arg01="__undefined__", arg02=0):
        self.arg01 = arg01
        self.arg02 = arg02
        self.str_len = len(self.arg01) + self.arg02
        return ("traits_bar", self.str_len)

class MainTraitlets(tHasTraitlets):
    """Proof of concept code implenting traitlets args"""
    arg01 = tUnicode()
    arg02 = tInteger()
    def __init__(self, *args, **kwargs):
        super(MainTraitlets, self).__init__(*args, **kwargs)

    def run(self, arg01="__undefined__", arg02=0):
        self.arg01 = arg01
        self.arg02 = arg02
        self.str_len = len(self.arg01) + self.arg02
        return ("traitlets_bar", self.str_len)

@beartype
def main_bear(arg01: str="__undefined__", arg02: int=0) -> tuple:
    """Proof of concept code implenting bear-typed args"""
    str_len = len(arg01) + arg02
    return ("bear_bar", str_len,)

if __name__=="__main__":
    num_loops = 100000

    duck_result_getattr = timeit('main_duck_getattr("foo", 1)', setup="from __main__ import main_duck_getattr", number=num_loops)
    print("timeit duck getattr time:", round(duck_result_getattr, 4), "seconds")

    duck_result_assert = timeit('main_duck_assert("foo", 1)', setup="from __main__ import main_duck_assert", number=num_loops)
    print("timeit duck assert  time:", round(duck_result_assert, 4), "seconds")

    traits_result = timeit('mm.run("foo", 1)', setup="from __main__ import MainTraits;mm = MainTraits()", number=num_loops)
    print("timeit traits       time:", round(traits_result, 4), "seconds")

    traitlets_result = timeit('tt.run("foo", 1)', setup="from __main__ import MainTraitlets;tt = MainTraitlets()", number=num_loops)
    print("timeit traitlets    time:", round(traitlets_result, 4), "seconds")

    bear_result = timeit('main_bear("foo", 1)', setup="from __main__ import main_bear", number=num_loops)
    print("timeit bear         time:", round(bear_result, 4), "seconds")
```

**Comment by leycec** [comment]
> I found that beartype was much slower than no bear-typing in my test....

**Hah-hah!** I *love* fielding questions like this, because overly scrupulous fixation on efficiency is my middle name. Err, middle *names*... as it were.

Thankfully, according to the wizened sages of old and [our own `timeit` timings](https://github.com/beartype/beartype#id48), `@beartype` is still as blazing fast at call time as it always was. In general, `@beartype` adds anywhere from 1µsec (i.e., 10<sup>-6</sup> seconds) in the worst case to 0.01µsec (i.e., 10<sup>-8</sup> seconds) in the best case of call-time overhead to each decorated callable. This superficially *seems* reasonable – but is it? Let's delve deeper.

## Formulaic Formulas (Brought to You By @beartype)

First, let's formalize how exactly we arrive at the prior call-time overheads.

Given any pair of reasonably fair timings (which yours *absolutely* are) between an undecorated callable and the equivalent `@beartype`-decorated callable, the call-time overhead `Δ(n, γ, λ)` added by `@beartype` to each call for `n` the number of times (i.e., loop iterations) each callable is repetitiously called, `γ` the total time in seconds of all calls to that undecorated callable, and `λ` the total time in seconds of all calls to that `@beartype`-decorated callable called is:

```
Δ(n, γ, λ) = λ/n - γ/n
```

Plugging in `n = 100000`, `γ = 0.0435s`, and `λ = 0.0823s` from your excellent timings, we see that `@beartype` on average adds call-time overhead of 0.388µsec to each decorated call: e.g.,

```
Δ(100000, 0.0435s, 0.0823s) = 0.0823s/100000 - 0.0435s/100000
Δ(100000, 0.0435s, 0.0823s) = 3.8800000000000003e-07
```

Again, this superficially *seems* reasonable – but is it? Let's delve deeper.

## Python Function Call Overhead: The New Glass Ceiling

What we're seeing here specifically and with Python decoration generally is just a residual artifact of the cost of **stack frames** (i.e., function and method calls) in Python. The mere act of *calling* any pure-Python callable induces a measurable overhead – even if the body of that callable is just the `...` or `pass` noop doing absolutely nothing. This is the minimal cost of calls in Python.

Since Python decorators almost always add at least one additional stack frame (typically as a closure call) to the call stack of each decorated call, this measurable overhead is the minimal cost of doing business with Python decorators. Even the fastest possible Python decorator necessarily pays that cost.

The quandry then becomes: "Is 1—0.01µsec of call-time overhead reasonable or sufficiently embarrassing as to bring shame upon our entire extended genealogical tree, even that second cousin twice-removed who never sends a kitsch greeting card at Christmas time?"

We can answer that by first inspecting the theoretical maximum efficiency for a pure-Python decorator that performs minimal work by wrapping the decorated callable with a closure that just defers to the decorated callable. This excludes the identity decorator (i.e., decorator that merely returns the decorated callable unmodified), which doesn't actually perform *any* work whatsoever. The fastest *meaningful* pure-Python decorator is thus:

``` python
def fastest_decorator(func):
    def fastest_wrapper(*args, **kwargs): return func(*args, **kwargs)
    return fastest_wrapper
```

By replacing `@beartype` with `@fastest_decorator` in your awesome snippet, we can expose the minimal cost of Python decoration:

```
$ python3.7 <<EOF
from timeit import timeit
def fastest_decorator(func):
    def fastest_wrapper(*args, **kwargs): return func(*args, **kwargs)
    return fastest_wrapper

@fastest_decorator
def main_decorated(arg01: str="__undefined__", arg02: int=0) -> tuple:
    """Proof of concept code implenting bear-typed args"""
    assert isinstance(arg01, str)
    assert isinstance(arg02, int)

    str_len = len(arg01) + arg02
    assert isinstance(str_len, int)
    return ("bear_bar", str_len,)

def main_undecorated(arg01="__undefined__", arg02=0):
    """Proof of concept code implenting duck-typed args"""
    assert isinstance(arg01, str)
    assert isinstance(arg02, int)

    str_len = len(arg01) + arg02
    assert isinstance(str_len, int)
    return ("duck_bar", str_len,)

if __name__=="__main__":
    num_loops = 100000

    decorated_result = timeit('main_decorated("foo", 1)', setup="from __main__ import main_decorated", number=num_loops)
    print("timeit decorated time:  ", round(decorated_result, 4), "seconds")    
                                   
    undecorated_result = timeit('main_undecorated("foo", 1)', setup="from __main__ import main_undecorated", number=num_loops)
    print("timeit undecorated time:", round(undecorated_result, 4), "seconds")    
EOF
timeit decorated time:   0.1185 seconds
timeit undecorated time: 0.0889 seconds
```

Again, plugging in `n = 100000`, `γ = 0.0889s`, and `λ = 0.1185s` from your excellent timings, we see that `@fastest_decorator` on average adds call-time overhead of 0.3µsec to each decorated call: e.g.,

```
Δ(100000, 0.0889s, 0.1185s) = 0.1185s/100000 - 0.0889s/100000
Δ(100000, 0.0889s, 0.1185s) = 2.959999999999998e-07
```

## Holy Balls of Flaming Dumpster Fires

**Holy balls,** people. I'm actually astounded myself.

Above, we saw that `@beartype` on average only adds call-time overhead of 0.388µsec to each decorated call. But `0.388µsec - 0.3µsec = 0.088µsec`, so `@beartype` only adds 0.1µsec (generously rounding up) of *additional* call-time overhead above and beyond that necessarily added by the fasted possible Python decorator.

Not only is `@beartype` within the same order of magnitude as the fastest possible Python decorator, it's effectively indistinguishable from the fastest possible Python decorator on a per-call basis.

Of course, even a negligible time delta accumulated over 10,000 function calls becomes *slightly* less negligible. Still, it's pretty clear that `@beartype` remains the fastest possible runtime type-checker.

## But, but... That's Not Good Enough!

*Yeah.* None of us are particularly pleased with the performance of the official CPython interpreter. CPython is the geriatric old man down the street that everyone puts up with because they've seen [Pixar's *Up!*](https://www.youtube.com/watch?v=F2bk_9T482g) and he means well and he didn't *really* mean to beat your equally geriatric 20-year-old tomcat with a cane last week. Really, that cat had it comin'!

If `@beartype` *still* isn't ludicrously speedy enough for you under CPython, we officially support PyPy3 – where you're likely to extract even more ludicrous speed.

Does that fully satisfy your thirsty cravings for break-neck performance? If so, feel free to toggle that *Close* button. If not, I'd be happy to hash it out over a casual presentation of further timings, fake math, and excessive Greek character abuse.

**Comment by mpenning** [comment]
Thank you for a great analysis of the situation... as a retrospective, I am taking away the following from this exercise...

1. If I don't want a compiled module and I don't care about [PEP 484 Type Hints](https://www.python.org/dev/peps/pep-0484/), duck typing is as fast as we can get (see `main_duck_assert()` and `main_duck_getattr()` above).  Interestingly, duck typing also beat the *compiled* Enthought traits module... I confess this compares apples to oranges.
2. If I'm willing to compile *and* I don't care about PEP 484, [Enthought traits](https://github.com/enthought/traits) is the "safest" static typing approach (because variables are never allowed to deviate, compared with duck-typing - which is a one-time type check).  As mentioned above, Enthought traits is significantly slower than duck-type approaches.
3. traitlets (pure python) has awful performance.  Enthought traits is much faster (as long as a compiler is available).
4. If I want PEP 484 Type Hints, the beartype decorator is a great option, but admittedly slower than non-PEP 484 approaches.

**Comment by leycec** [comment]
These continue to be great questions! Thanks for all the fun engagement here. Let's see if I can't tackle a few of these...

> If I don't want a compiled module and I don't care about PEP 484 Type Hints, duck typing is as fast as we can get (see main_duck_assert() and main_duck_getattr() above).

**Right.** All else being equal, manually inlining code (e.g., with hand-rolled `assert()` statements in this case) into a callable should *always* be slightly faster than decorating that callable with wrapper code.

The same is actually true of all languages – not only high-level dynamically typed languages like Python and Ruby. This is why [manual loop unrolling](https://en.wikipedia.org/wiki/Loop_unrolling#Static/manual_loop_unrolling) is still a thing in C and C++. <sup>i am shaking my head</sup>

> Interestingly, duck typing also beat the compiled Enthought traits module...

**Right.** This is because Enthought traits isn't *actually* being compiled to low-level machine code; like all pure-Python code, it *is* being compiled to intermediary Python bytecode. But Python bytecode is still excruciatingly slow.

Given your understandable interest in extreme speed, compilation, and optimizations, I wonder if you're familiar with [**pydantic**](https://pydantic-docs.helpmanual.io)? Unlike traits, pydantic *is* actually being compiled to low-level machine code via [Cython](https://en.wikipedia.org/wiki/Cython). This means that **pydantic should be faster than duck typing.**

The only disadvantage of pydantic's approach is that it will be slower than beartype's approach when JIT-ed by a JIT like PyPy3, because JITs like PyPy3 can't JIT low-level Cython, C, or machine code; they can only JIT pure-Python.

In any case... I now, right? It's hard to beat the duck, but pydantic should get you there for 90% of common use cases. :duck: 

> Enthought traits is the "safest" static typing approach...

Careful there! "Static" is an unfortunately overloaded term that means many strange different things in many strange different languages.

When Python devs say "static typing," they mean [static type checkers that perform their work at static analysis time rather than runtime](https://github.com/beartype/beartype#static-type-checkers). So, things like mypy, Facebook's Pyre, Microsoft's pyright, and Google's pytype is what I'm saying.

What you probably mean here is more commonly known as **type-safe dataclasses.** This is also what pydantic and [attrs](https://www.attrs.org/en/stable) (and eventually beartype itself) do: they inject automated type-checking into each read and write of class and instance variables.

> traitlets (pure python) has awful performance. Enthought traits is much faster (as long as a compiler is available).

**Fascinating!** Again, pydantic should handily beat out both if you have Cython installed. Enthought traits and traitlets are actually *both* pure-Python, as far as I know. If Enthought traits significantly outperforms traitlets, this is likely due to [extreme microoptimizations](https://github.com/unazed/python-micro--optimizations) in the former versus the latter.

Microoptimization is right up in our wheelhouse here, because beartype itself internally leverages extreme microoptimization to the hilt to extract every last ounce of the wall-clock time slice from CPython.

> If I want PEP 484 Type Hints, the beartype decorator is a great option, but beartype is admittedly slower than non-PEP 484 approaches.

Actually... beartype should be dramatically faster than *all* other pure-Python runtime type checkers! This includes Enthought traits, traitlets, and attrs. If this is *not* the case, please post timings in a separate issue and I'd be happily to repeatedly bang my head against CPython until we beat 'em up. :fist_right: :drop_of_blood: :fist_left:

Beartype began life as a non-PEP 484 type checker. For this reason, [`@beartype` reduces simple use cases that *only* type check against simple classes to an optimally efficient code path](https://github.com/beartype/beartype#id69). For these use cases, `@beartype` entirely avoids all heavyweight compliance with PEP standards – including PEP 484.

If you're at all curious about what the code `@beartype` generates vaguely looks like, [hit this link when you find a spare moment](https://github.com/beartype/beartype#id69). We actually generate even *faster* code than when that link was first published, but it's still a useful deep dive into the Beartype School of Hard Knocks.

Thanks again for the fun discourse, Mike! From the [Great White North](https://theculturetrip.com/north-america/canada/articles/why-is-canada-nicknamed-the-great-white-north/) to you, have a great Canadian Thanksgiving. :turkey: :fork_and_knife:

**Comment by mpenning** [comment]
> Given your understandable interest in extreme speed, compilation, and optimizations, I wonder if you're familiar with pydantic? Unlike traits, pydantic is actually being compiled to low-level machine code via Cython. This means that pydantic should be faster than duck typing.

Thank you for pointing out pydantic, but pydantic tested worst of all when I configured type validation... see the `test_me.py` output below...

> Enthought traits and traitlets are actually both pure-Python, as far as I know.

Actually Enthought traits compiles the [base traits classes](https://docs.enthought.com/traits/traits_api_reference/ctraits.html#module-traits.ctraits)... also ref the source -> [`traits/ctraits.c`](https://github.com/enthought/traits/blob/main/traits/ctraits.c)...  quoting from the docs...

> **_traits.ctraits Module_**
> Fast base classes for HasTraits and CTrait.
>
> The ctraits module defines the CHasTraits and cTrait extension types that define the core performance-oriented portions of the Traits package. 

Test results...

```shell
$ python test_me.py
timeit duck getattr time: 0.0432 seconds
timeit duck assert  time: 0.0466 seconds
timeit traits       time: 0.0743 seconds
timeit bear         time: 0.098 seconds
timeit traitlets    time: 0.5947 seconds
timeit pydantic     time: 1.6075 seconds
```

Test code:
```python
# Filename: test_me.py
from beartype import beartype

import pydantic

from traits.api import HasTraits as eHasTraits
from traits.api import Unicode as eUnicode
from traits.api import Int as eInt

from traitlets import HasTraits as tHasTraitlets
from traitlets import Unicode as tUnicode
from traitlets import Integer as tInteger

from timeit import timeit

def main_duck_getattr(arg01="__undefined__", arg02=0):
    """Proof of concept code implenting duck-typed args and getattr"""
    getattr(arg01, "capitalize")  # Type-checking with attributes
    getattr(arg02, "to_bytes")    # Type-checking with attributes

    str_len = len(arg01) + arg02
    getattr(str_len, "to_bytes")
    return ("duck_bar", str_len,)

def main_duck_assert(arg01="__undefined__", arg02=0):
    """Proof of concept code implenting duck-typed args and assert"""
    assert isinstance(arg01, str)
    assert isinstance(arg02, int)

    str_len = len(arg01) + arg02
    assert isinstance(str_len, int)
    return ("duck_bar", str_len,)


class MainTraits(eHasTraits):
    """Proof of concept code implenting Enthought traits args"""
    arg01 = eUnicode()
    arg02 = eInt()

    def __init__(self, *args, **kwargs):
        super(MainTraits, self).__init__(*args, **kwargs)

    def run(self, arg01="__undefined__", arg02=0):
        self.arg01 = arg01
        self.arg02 = arg02
        self.str_len = len(self.arg01) + self.arg02
        return ("traits_bar", self.str_len)

class MainTraitlets(tHasTraitlets):
    """Proof of concept code implenting traitlets args"""
    arg01 = tUnicode()
    arg02 = tInteger()

    def __init__(self, *args, **kwargs):
        super(MainTraitlets, self).__init__(*args, **kwargs)

    def run(self, arg01="__undefined__", arg02=0):
        self.arg01 = arg01
        self.arg02 = arg02
        self.str_len = len(self.arg01) + self.arg02
        return ("traitlets_bar", self.str_len)

@beartype
def main_bear(arg01: str="__undefined__", arg02: int=0) -> tuple:
    """Proof of concept code implenting bear-typed args"""
    str_len = len(arg01) + arg02
    return ("bear_bar", str_len,)

class MainPydantic(pydantic.BaseModel):
    """
    Proof of concept code implenting pydantic args

    - Warning: pydantic does NOT vaidate types by default
      https://github.com/samuelcolvin/pydantic/issues/578
    """
    arg01: pydantic.StrictStr = ""
    arg02: pydantic.StrictInt = 0
    str_len: pydantic.StrictInt = 0

    class Config(object):
        """Configure pydantic parameters"""
        validate_all = True
        validate_assignment = True

    def __init__(self, *args, **kwargs):
        super(MainPydantic, self).__init__(*args, **kwargs)

    def run(self, arg01="__undefined__", arg02=0):
        self.arg01 = arg01
        self.arg02 = arg02
        self.str_len = len(self.arg01) + self.arg02
        return ("pydantic_bar", self.str_len)

if __name__=="__main__":
    num_loops = 100000

    duck_result_getattr = timeit('main_duck_getattr("foo", 1)', setup="from __main__ import main_duck_getattr", number=num_loops)
    print("timeit duck getattr time:", round(duck_result_getattr, 4), "seconds")

    duck_result_assert = timeit('main_duck_assert("foo", 1)', setup="from __main__ import main_duck_assert", number=num_loops)
    print("timeit duck assert  time:", round(duck_result_assert, 4), "seconds")

    traits_result = timeit('mm.run("foo", 1)', setup="from __main__ import MainTraits;mm = MainTraits()", number=num_loops)
    print("timeit traits       time:", round(traits_result, 4), "seconds")

    bear_result = timeit('main_bear("foo", 1)', setup="from __main__ import main_bear", number=num_loops)
    print("timeit bear         time:", round(bear_result, 4), "seconds")

    traitlets_result = timeit('tt.run("foo", 1)', setup="from __main__ import MainTraitlets;tt = MainTraitlets()", number=num_loops)
    print("timeit traitlets    time:", round(traitlets_result, 4), "seconds")

    pydantic_result = timeit('pp.run("foo", 1)', setup="from __main__ import MainPydantic;pp = MainPydantic()", number=num_loops)
    print("timeit pydantic     time:", round(pydantic_result, 4), "seconds")
```

**Comment by leycec** [comment]
*...ohnoes*

I didn't mean to publicly put you on the spot, Mike. Now I feel bad, having failed to grok the subtle signs that you were on the company dime. **Awkward.**

This is why I live in the woods, folks. We deal with simple Old World problems here – like how to politely separate an unruly pack of raccoons squabbling over post-Thanksgiving kitchen detritus without losing a hand. <sup>*it happened*</sup>

**Please.** Don't go to any absurd trouble on `beartype`'s account. On the one hand, we'd be *more* than happy to publicly attribute, advertise, and/or promote Cisco Systems. On the other hand, it might be best for all the inevitable legal, HR, and marketing suits involved if I just manually rewrite our profiling suite from the ground up without reference to your formidable work.

I now formally swear on both of my arthritic pinky fingers that I neither read nor understood (*...if I actually read, which I didn't!*) a single line of the code you graciously posted above. I swear, Cisco. I didn't see nuffin'.
