### ISSUE TITLE
How to use beartype with boto3?

### ISSUE THREAD

**Issue by paulhutchings** [beartype/beartype#68]
Recently discovered beartype and have been loving it, especially love the humor and lighthearted nature of the project!

I'm working with boto3 (the AWS Python SDK) and disocvered that it [uses a factory to dynamically create the various class _types_ at runtime](https://github.com/boto/boto3/blob/develop/boto3/resources/factory.py#L139), meaning that by default, you cannot annotate them. I discovered the [boto3-stubs](https://pypi.org/project/boto3-stubs/) package exists as a way to provide both types to annotate with, as well as allowing various IDE auto-complete features to work.

However...(you might already see where this is going), because the types provided by `boto3-stubs` and the actual type that `boto3` creates are not identical (even though they represent the same object/schema), the type validation fails when decorating a function that accepts/returns boto3 types as arguments with `beartype`. Below is a simple example:

```
from beartype import beartype
import boto3
from mypy_boto3_s3.service_resource import S3ServiceResource, Bucket

@beartype
def example(s3: S3ServiceResource) -> Bucket:
    return s3.Bucket('example')

if __name__ == "__main__":
    s3 = boto3.resource('s3')
    bucket = example(s3)
```
```
Traceback (most recent call last):
  File "example.py", line 11, in <module>
    bucket = example(s3)
  File "<string>", line 23, in example
  File "/home/paul/.cache/pypoetry/virtualenvs/beartype-boto3-V5MWr3_P-py3.8/lib/python3.8/site-packages/beartype/_decor/_error/errormain.py", line 301, in raise_pep_call_exception
    raise exception_cls(  # type: ignore[misc]
beartype.roar.BeartypeCallHintPepParamException: @beartyped example() parameter s3="s3.ServiceResource()" violates type hint <class 'mypy_boto3_s3.service_resource.S3ServiceResource'>, as "s3.ServiceResource()" not instance of <class "mypy_boto3_s3.service_resource.S3ServiceResource">.
```

I've also made [a small example project](https://github.com/paulhutchings/beartype-boto3-example) for this so that people can play around with it/reproduce it.

Now poking around, I discovered [validators](https://github.com/beartype/beartype#beartype-validators) and I assume this is the appropriate way to handle situations like this. However, after playing around a bit, while I can create a custom type (see example below) that works with beartype, I lose the other features that the `boto3-stubs` library provides such as the autocomplete/suggest features. Granted, those are not the most important things in the world, but they certainly help, especially when working in a larger project.

```
from typing import Annotated
from beartype.vale import Is

S3Bucket = Annotated[object, lambda obj: obj.__class__.__name__ == "s3.Bucket"] 
```

What I'm really after I suppose is a way to "map" types, or basically tell beartype, "hey, these types are the same" or something along those lines. Is it possible to have my salmon and eat it too?

**Comment by leycec** [comment]
> ...it uses a factory to dynamically create the various class types at runtime, meaning that by default, you cannot annotate them.

*ohnoes*

> I discovered the `boto3-stubs` package exists as a way to provide both types to annotate with, as well as allowing various IDE auto-complete features to work.

**Oh. Oh, yes.**

> ...because the types provided by `boto3-stubs` and the actual type that `boto3` creates are not identical (even though they represent the same object/schema),

*ohnoes* x 2: The Revenge of *ohnoes*

> However, after playing around a bit, while I can create a custom type (see example below) that works with `beartype`...

**Oh. Oh, even more yes.**

> I lose the other features that the `boto3-stubs` library provides such as the autocomplete/suggest features.

"Why, Bezos. Why are we cursed with your dark legacy?", I screech to the uncaring skies. No reply is heard.

> Granted, those are not the most important things in the world, but they certainly help, especially when working in a larger project.

Absolutely. When you start pushing past a million lines, `git rebase -i` starts spewing incomprehensible merge conflicts everywhere, and your coworkers begin defacing your cubicle with phallic anti-`pyright` slurs, you know you need answers fast.

That's why we're here... is what I'd be saying if I had any experience whatsoever with Boto3. Instead, I have none. Therefore, please take everything that follows with a generous pinch of salt to avoid additional salty tears of dismay and anguish from coworkers.

According to StackOverflow, PEP 484-style forward references *might* be of some assistance here ([citation](https://stackoverflow.com/a/53573372/2809027), [citation](https://stackoverflow.com/a/68036578/2809027)). Anonymous Internet strangers (who stridently assure us we can trust them with our Q4 profit margins) claim that types dynamically fabricated by abstruse Boto3 factories actually *do* exist at some indefinite point in time: e.g.,

``` python
# Supposedly, this works. I unconditionally trust Internet
# strangers with my cats. Would You?
dynamo: 'boto3.resources.factory.dynamodb.Table' = (
    boto3
    .resource('dynamodb')
    .Table(os.environ['DYNAMODB_TABLE']))

# Supposedly, this works too. I believe what I am told.
def get_object(s3_client: 'botocore.client.S3') -> str:
        pass
```

The latter example suggests `beartype` (and other runtime type-checking solutions like `pydantic`) *might* transparently support standard type hints resembling:

``` python
from beartype import beartype
import boto3

# Forward references for value. Because we care.
S3Client = 'botocore.client.S3'
S3ServiceResource = 'kinda.have.no.idea.what.the.type.of.S3ServiceResource.actually.is'
Bucket = 's3.Bucket'
Table = 'boto3.resources.factory.dynamodb.Table'

@beartype
def example(s3: S3ServiceResource) -> Bucket:
    return s3.Bucket('example')

if __name__ == "__main__":
    s3 = boto3.resource('s3')
    bucket = example(s3)
```

## That's Not Gonna Work

...*yeah.* I know. If that actually worked as advertised, [`my_boto3_builder`](https://github.com/vemel/mypy_boto3_builder) and other competing Boto3 static type-checking stub APIs wouldn't be a thing. But they are. Ergo, that's not gonna work.

I'm a bit surprised there's no sane public well-defined way to either:

* Get the actual `boto3` types that would be returned by various Boto3 functions and methods.
* Map from `boto3-stub` fake types to actual `boto3` types.

Or is there? Neither project really name-drops runtime type-checkers like `pydantic` aside from [a few sporadic unresolved issues on the Boto3 issue tracker](https://github.com/boto/botocore/issues/2297).

## Map Types for the Good of the Amazon

> What I'm really after I suppose is a way to "map" types, or basically tell `beartype`, "hey, these types are the same" or something along those lines. Is it possible to have my salmon and eat it too?

**This is a fascinating idea.** In theory, it *might* be feasible for us to doctor up a new public `beartype` API for registering dynamic type mappings: e.g.,

```
from beartype import register_type_mapping  # <-- ...or something, something
from mypy_boto3_s3.service_resource import Bucket

# But what is "ActualBucket"? Is there an actual type somewhere
# that you can statically or dynamically import and pass to this API?
ActualBucket = oh. gods. help. us.

# Tell @beartype to internally treat all type hints
# annotated as object "Bucket" as if they were
# annotated as object "ActualBucket" instead.
register_beartype_mapping(Bucket, ActualBucket)
```

In practice, that's probably the wrong thing to do. [Upstream is aware this is a pressing concern and will *probably* begin offically type-hinting Boto3 sometime this century](https://github.com/boto/boto3/issues/1725). Obviously, no one wants to wait for the clone of Bezos to resolve this... but maybe we should? Of course, I *would* say this. I just spent three weeks wrestling with Sphinx `autodoc` integration in `beartype`. It wasn't a good time.

My bear sense is tingling. This can only mean that absolutely nothing will work and we are doomed to abandon sanity-preserving intellisense for Boto3 types on excessively big codebases that make even VSCode Pylance weep.

*ohnoes* x 3: The Final Legend of *ohnoes*

**Comment by leycec** [comment]
*Eureka!** *Ignore everything above,* because it was bad. I have something better – nay, something devious – nay, something cruel and malicious that eats at the very beating heart of static type-checking like Lyme disease in PEP-compliant form.

So. There's something awful and amazing called [`typing.TYPE_CHECKING`](https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING). Ever heard of it? No? Great. Let's continue.

`typing.TYPE_CHECKING` is *wonderful*, because it officially allows us to lie straight to the face of static type checkers and be rewarded for it. The idea here is that we create two variants of each Boto3 type hint via [PEP 484 type aliases](https://www.python.org/dev/peps/pep-0484/#type-aliases), conditionally created depending on whether we're currently performing static or runtime type-checking:

``` python
import boto3
from beartype import beartype
from typing import TYPE_CHECKING

# If performing static type-checking (e.g., mypy, pyright),
# conditionally import Boto3 type hint stubs that are
# safely usable *ONLY* at static type-checking time.
if TYPE_CHECKING:
    from mypy_boto3_s3.service_resource import S3ServiceResource, Bucket
# Else, @beartime-based runtime type-checking is
# being performed. In this case, alias the same
# Boto3 type hint stub names imported above to their
# semantically equivalent beartype validators that are
# safely usable *ONLY* at runtime type-checking time.
else:
    from typing import Annotated
    from beartype.vale import Is

    # Suck it, intellisense IDE. Suck it.
    S3ServiceResource = Annotated[
        object, Is[lambda obj: obj.__class__.__name__ == "s3.ServiceResourceOrSmthng"]]
    Bucket = Annotated[object, Is[lambda obj: obj.__class__.__name__ == "s3.Bucket"]]

# Do this for the good of commerce, @beartype.
@beartype
def example(s3: S3ServiceResource) -> Bucket:
    return s3.Bucket('example')

if __name__ == "__main__":
    s3 = boto3.resource('s3')
    bucket = example(s3)
```

If that doesn't work, I *will* graffittii my next GitHub comment with 10,000 soul-destroying repetitions of the sparkly heart emoji. We pray it never comes to that. :sparkling_heart:

**Comment by paulhutchings** [comment]
@leycec Dude...you are amazing. Not only did you manage to figure something out for an issue I thought was going to be unsolvable (at least as far as the whole "have your types and intellisense too" goes), you did this within...(checks timestamp)... like a couple of hours from me posting.

Looking back, `typing.TYPE_CHECKING`  seems like it was the real key, as it enables the dual-nature of the types to provide both the runtime type-checking _and_ the intellisense goodies.

In all seriousness, how may I express my thanks to you and the project for helping solve the missing piece of this puzzle? I can make a PR to add this to the documentation so that others who may come across in the future won't have to scratch their heads.

**Comment by leycec** [comment]
**Awwwwwww.** You so nice, Paul. As a supremely skilled sloth that rocks shades, I'm kinda concerned about hurting you if I emoji you too fast over here. Oh, God – here goes! :hugs: 

> I can make a PR to add this to the documentation so that others who may come across in the future won't have to scratch their heads.

[**Bwa-hah.** I accidentally got there first ahead of you. Let me know how that reads for you.](https://github.com/beartype/beartype#boto3-types)

Must be rough being a sloth. I sympathize. My beautiful wifey <sup>←you just know she's gonna see this</sup> calls me a sloth all the time. Metaphorically speaking, she's not wrong. This issue is everything I did tonight. :sweat_smile: 

> In all seriousness, how may I express my thanks to you and the project for helping solve the missing piece of this puzzle?

Why, I'm so glad you asked. The answer is money. Just kidding! Yikes. Tough crowd tonight. Seriously, though. If you find any available volunteer time for open source, <sup>yup so never</sup> I'm certain we'd all *love* a package from Paul that is either:

* `bearboto3` (*...do it, do it*), publishing Boto3 types safely usable by both `@beartype` and static type checkers via the `TYPE_CHECKING` Uncertainty Principle. GitHub stars will flow like wine.
* `midinow` (*...do it, do it*), packaging [`midi-nn`](https://github.com/paulhutchings/midi-nn) into a full-blown thing. Machine-generated music is this fascinating thing that seeks to obsolete the last remaining human MIDI composer alive. When I was young and had this even *more* fascinating thing nebulously called "free time," I made a 90's-era online metal MIDI repository called **"Mysidia."** Yup. *Metal. MIDI.* Synth don't get more hardcore. `</ahem>` It'd be fascinating to hear machine intelligence tackle classically unrepresented genres. So, anything *other* than classical is what we're saying. Does such a thing exist? For the love of the poorly sampled fretless bass, make such a thing exist.

Thanks again for all this voluminous interest! Don't hesitate to drop me a line anywhere you need a helping hand with @beartype and/or Python type-checking in general.

**Comment by paulhutchings** [comment]
> [**Bwa-hah.** I accidentally got there first ahead of you. Let me know how that reads for you.](https://github.com/beartype/beartype#boto3-types)
> 

I love it! Could not have done a _beartype_ style write-up better myself.

>     * `bearboto3` (_...do it, do it_), publishing Boto3 types safely usable by both `@beartype` and static type checkers via the `TYPE_CHECKING` Uncertainty Principle. GitHub stars will flow like wine.
> 

Indeed, I was already thinking of doing this :)

I'm afraid _midi-nn_ will have to wait (hopefully not for long). I'm afraid my musical knowledge outstrips my ML knowledge at the moment, but rest assured it is not an intersection of interests that I will abandon.
