### ISSUE TITLE
[Speed] Redundant generic and protocol checks

### ISSUE THREAD

**Issue by leycec** [beartype/beartype#76]
**uhohs.** @beartype currently exhibits ~~crippling~~ less-than-ideal performance for generics (i.e., user-defined `typing.Generic` subclasses) and protocols (i.e., user-defined `typing.Protocol` subclasses). As [@posita publicly exposed in this hard-hitting journalist expose](https://github.com/beartype/beartype/discussions/67#discussioncomment-1842501), this is because @beartype currently generates redundant `isinstance()` checks for these subclasses: e.g.,

``` python
if not (
    isinstance(1, numerary.types.SupportsComplexOps)  # <-- this is fine
    and
    isinstance(1, numerary.types._SupportsComplexOps)  # <-- this is badness
):
```

While technically *fine* (for various hand-wavy definitions of *fine*), this redundancy reduces runtime efficiency for generics and protocols involved in complex inheritance hierarchies that make my head spin with dysphoric nausea like last year's eggnog bender. Just like Santa hopped up on too much Christmas hopium, `beartype 0.10.0` promises to fix all the badness.

Let's keep our promises, @beartype. The reindeer with the blinking nose is depending on us! :santa:

**Comment by posita** [comment]
Oh dear. 🦌 It looks like I have [stepped right in it](https://github.com/beartype/beartype/blob/2b5165ce13ad7a74e60eba59223bb8fc1c1aa474/beartype/_decor/_code/_pep/_pephint.py#L1741-L1811), haven't I? 😬

**Comment by leycec** [comment]
...heh. You weren't supposed to see that comment.

Heck, *I* wasn't supposed to see that comment. I'd forgotten all about that horrifying edge case. Now I feel a sadness burying through my lumpy soul like a thousand year-old sandworm on Arachis and it's not even Christmas yet.

![sadness gone furry](https://s36537.pcdn.co/wp-content/uploads/2018/05/A-gray-cat-crying-looking-upset.jpg.webp)

**Comment by leycec** [comment]
...heh. So, my younger self was ~~blinded with incoherent rage~~ mildly frustrated while implementing deep type-checking support for PEP 484-, 544-, and 585-compliant generics and protocols.

The `SupportsNumeratorDenominator.__orig_bases__` landmine you stumbled into above is probably a product of this non-orthogonality:

    For inexplicable reasons, **single-inherited protocols**
    (i.e., classes directly subclassing *only* the :pep:`544`-compliant
    :attr:`typing.Protocol` abstract base class (ABC)) are *not* subject to
    type erasure and thus constitute a notable exception to this heuristic:

        .. code-block:: python

        >>> from typing import Protocol
        >>> class UserDefinedProtocol(Protocol): pass
        >>> UserDefinedProtocol.__mro__
        (__main__.UserDefinedProtocol, typing.Protocol, typing.Generic, object)
        >>> UserDefinedProtocol.__orig_bases__
        AttributeError: type object 'UserDefinedProtocol' has no attribute
        '__orig_bases__'

    Welcome to :mod:`typing` hell, where even :mod:`typing` types lie broken
    and misshapen on the killing floor of overzealous theory-crafting purists.

Rub my eye with a spork, for it can no longer cry on its own. :eye:

**Comment by posita** [comment]
🤣😭

There is room aplenty in human hearts for all: frustration, sadness, _and_ hope.

> Though wise men at their end know dark is right,
> Because their words had forked no lightning they
> Do not go gentle into that good night. …
> Rage, rage against the dying of the light.
> 
>                                 _—Dylan Thomas_

**Comment by leycec** [comment]
I see your *Rage Against Wales* and raise you one [*Random Rustic Hill in Wales that Makes Even Grown Canadian Men Weep*](https://poets.org/poem/fern-hill):

```
Now as I was young and easy under the apple boughs
About the lilting house and happy as the grass was green,
     The night above the dingle starry,
          Time let me hail and climb
     Golden in the heydays of his eyes,
And honoured among wagons I was prince of the apple towns
And once below a time I lordly had the trees and leaves
          Trail with daisies and barley
     Down the rivers of the windfall light.

And as I was green and carefree, famous among the barns
About the happy yard and singing as the farm was home,
     In the sun that is young once only,
          Time let me play and be
     Golden in the mercy of his means...
```

I'm bawling by "And as I was green and carefree." It goes south from there.

**Oh!** Almost forgot to mention in between nostalgic tears shed for a wistful British childhood I never knew: I *think* I've finally solved this plague on both our houses. In theory, commit 51c5b9b should eliminate the excess `isinstance()` check crippling numerary's performance. Mypy 0.920 is currently failing, but I kinda could care less about that tonight. Shutup and accept this codebase for the misshappen horror it so clearly is, Mypy!

If you're feelin' frisky and have a Christmas afternoon to quietly bang your forehead against, try giving `HEAD` on our `main` branch yet another go.

:christmas_tree: **+** :desktop_computer: **=** :full_moon_with_face:

**Comment by leycec** [comment]
We (*...okay, it's just me*) are currently testing this up against your exact use case in `numerary`, which is instructive, elucidative, and scary. We saw this and our eye bundles simultaneously twitched:

``` python
# TODO(posita): Once <https://github.com/python/typeshed/pull/6394> is released,
# consider adding something this above instead:
# if sys.version_info >= (3, 8):
#     from typing import _ProtocolMeta
# else:
#     from typing_extensions import _ProtocolMeta
```

So... yeah. The thing is, you probably don't want to do that. Importing private attributes from `typing{_extensions,}` has destroyed many a prior package. Pypi is littered with their corpses. Their tongues are lolling out!

The way you're currently doing it (i.e., `_ProtocolMeta = type(Protocol)`) is both clever and robust against `typing{_extensions,}` breakage, which *will* happen exactly when the dog starts squealing because the vicious neighbourhood kids are playing Pin the Second Tail on Your Dog again. <sup>\*wince\*</sup>

**Comment by leycec** [comment]
:expressionless: :exploding_head: :boom: 

The transition from expressionless head to exploding head can only mean one thing... **everything has been fixed!** We even tested everything, too. I know, right? How often does *that* happen!?!?

Let me know if this satisfies `numerary`'s need for ludicrous speed. If not, we'll dump everything into `/dev/null` and start over from scratch. We may both hope it doesn't come to that.

Oh, and **Merry Friggin' Christmas!** We doin' this. And by "this," I mostly mean sleeping. That's the true gift for us who are code monkeys. :sleeping:

**Comment by posita** [comment]
OMG, this is so much better! I noticed one teensy weensy little issue, though. 👌😬 For some reason, the update is getting confused where there there are variadic keyword arguments. Consider:

``` python
from beartype import beartype

@beartype
def okay(okay_a, okay_b: int = 0, okay_c: str = "") -> None:
    pass

@beartype
def okay_too(okay_too_a, okay_too_b: int = 0, okay_too_c: str = "", *args) -> None:
    pass

@beartype
def also_okay(also_okay_a, also_okay_b: int = 0, *, also_okay_c: str = "") -> None:
    pass

@beartype
def whoops(whoops_a, whoops_b: int = 0, whoops_c: str = "", **kw) -> None:
    pass

@beartype
def whoops_too(whoops_too_a, whoops_too_b: int, whoops_too_c: str, **kw) -> None:
    pass

def test_nothing() -> None:
    assert True, f"Nothing to see here!"
```

The `@beartype` decorator will choke when decorating `whoops` and `whoops_too`.

That being said, with some casual testing (selecting from some of [`dyce`](/posita/dyce)'s unit tests), I got the following before and after your change:

| No Bear | Old Bear | Merry Christmas Bear |
|:---:|:---:|:---:|
| 3.5875 s | 10.3075 s | **_4.92 s_** 💨💥 |

Nice! I now have a hope of landing my no-more-short-circuiting-unions branch!

**Comment by leycec** [comment]
> For some reason, the update is getting confused where there there are variadic keyword arguments.

**Brilliant.** I'm *so* inexpressibly grateful for that graceful catch – and during the most family fun-filled time of the year, too! I was actually on the cusp of begging you to join an impromptu @beartype QA Team. My Spideybear Sense was tingling that I might have broken something with respect to core argument parsing during last month's sweeping optimization pass.

Lo, those fears have come to pass. Welp. It's back to the slave mines. @GitHub: I politely request a :whip: emoji for moments such as this.

And... let's open an issue tracking this new shame.

**Comment by leycec** [comment]
**Top 10 Shocking Revelation of 2021:** 0's aren't 1's. :scream: 

I have good news; I have bad news. The good news is that d710a54 resolves that innocuous little "issue" with variadic keyword arguments you bumped into. I'm willing to pretend you never saw that if you are.

The bad news is that I now feel sleepy. Curse this emaciated meat suit! :man_astronaut:

**Comment by posita** [comment]
> **Top 10 Shocking Revelation of 2021:** 0's aren't 1's. 😱

🤣 I humbly offer one minor edit to make the math work: **Top 10 Shocking Revelation of 2021:** 0's aren't 1's _and 1's aren't 0's_.

> The bad news is that I now feel sleepy. Curse this emaciated meat suit! 👨‍🚀

I awoke just now because my mind was ablaze with three questions my memory could not answer (and not at all because I consumed too much tea before turning in well before you did and now my bladder was full):

1. Wait, did I attach a stack trace to #76? I meant to. I had one. I would be lazy-bordering-on-rude not to. I hope poor @leycec hasn't seen my post yet. Maybe I can offer one via stealth edit and he'll be none the wiser.
2. Did I even bother thanking him? Even if I did, I don't think I properly acknowledged all the care and attention he has paid to this, especially in light of the holidays. I hope he is well. I hope that all this typing is a way to keep his fingers warm in his _cozy_ cabin during these cold, dark winter months and is not instead risking frostbite by the removal of digit-preserving mittens. I hope I have not distracted him from Mrs. @leycec or other loved ones urging him to refill the overtaxed pellet stove. I hope I have adequately expressed the joy I receive from these interactions. Maybe I can eloquently convey all this via stealth edit and he'll be none the wiser.
3. Did I let the cat in? (Not relevant to this context, but included to maintain a complete and accurate record.)

> I'm willing to pretend you never saw that if you are.

Never saw what? I don't know what you're talking about.

> > ...my no-more-short-circuiting-unions branch!
> 
> This is a thing I must know everything about. Look at me salivatin' over here.

``numerary`` offers what it refers to as [short-circuiting unions](https://posita.github.io/numerary/0.2/#short-circuit-type-enumerations) (SCUs) in addition to its protocols. ([Here's an example](https://github.com/posita/numerary/blob/3424d0484dda961024f63e7f65f8d383ba322849/numerary/types.py#L1139).) The original motivation was a performance optimization, but they really didn't provide much benefit, even though I erroneously claimed that they did…_except where `beartype` checks hit this issue_. In that case, all bets were off, since (as you know) checks sometimes degraded to the non-caching protocols (in which case, short-circuiting those checks reined in runtime type-checking performance).

The prospect of a fix here was super exciting because the only reason I used SCUs at all in ``dyce`` was to work-around this performance gap and simplifying code is one of my favorite things. I even went so far as to [make a branch](https://github.com/posita/dyce/commit/483e9fc9de123b326d64e40fc4e8930ba1d2c223) that removed their use. I was nervous that the performance of my `beartype`d tests [ballooned to over 6×](https://github.com/posita/dyce/runs/4543126284?check_suite_focus=true#step:5:254) the time of my [non-`beartype`d tests](https://github.com/posita/dyce/runs/4543126284?check_suite_focus=true#step:5:207), which was the motivation behind #67.

The bonus? After this and [d710a54](https://github.com/beartype/beartype/commit/d710a54d00464ff2fb0b5ac3a3afe5b1459f3547), ``dyce``'s ``beartype``d tests are faster then they've ever been (under 1.5× of their non-``beartype``d counterparts). That is not only _stupid_ fast, but it has made for a very Merry Christmas, indeed. Santa has _nothing_ on bear this season.

![Got presents, bruh?](https://c.tenor.com/Gn7Ll5Xs2FkAAAAM/bear-santa-claus.gif)

I am now even contemplating [removing SCUs altogether from ``numerary``](https://github.com/posita/numerary/commit/b16faabda12e37aa0e4ac07b17b736bf4f02bac8) and leaving their surgically targeted reintroduction to clients on those rare occasions where they are helpful.

I hope that loved ones are taking as good care of you as you are of us this winter.

![Christmas Pooh](https://c.tenor.com/kKNd6c_9ZOkAAAAM/winnie-the-pooh-pooh.gif)

**Comment by leycec** [comment]
**Awwwwwwwww!** What a wonderfully exuberant outpouring of goodwill, festive cheer, and gr8-m8-i-r8-8/8 humour. I *really* kinda needed this, too. My stepmom was just diagnosed with Stage IV Stomach Cancer (so: terminal, debilitating, and excruciating) the day before Christmas Eve. She's a delightful woman and I love her to bits. My wife is... well, devastated.

I'm trying not to think about physical reality for a bit by instead beating up manscaped yakuza in *Yakuza.* But you can only punch so many digital criminal underworld cretins in their plasticky uncanny-valley faces before Ugly Ol' Reality starts peering over your shoulder and whispering an unintelligible (yet predictably disturbing) catechism in a creepy monotone. And I'm like:

> Come on. Fess up. Who invited Reality to the party, guys?

Thank you for the cuddly chuckles. And you're most welcome, of course! @beartype is here to service numerary's every need – especially that need for blistering speed that transgresses every local codebase traffic law. Clearly, we're not *quite* there yet; we'd love `@beartype`-checked calls to quietly inch within 1.25× or even 1.10× of unchecked calls.

We're confident that our next optimization sprint will lift us up to those lofty heights. Sadly, we didn't get there for the `beartype 0.10.0` release cycle. I hope to push that out the ice-encrusted cabin door by New Year's – even though the codebase is mewling with big round eyes for attention, chocolate cookies, and warm hugs. Too bad, bear! *You must leave this den.*

Urgh! So close to perfection. Yet so far from destiny. :ringed_planet:
