### ISSUE TITLE
[Bug report?] beartype 0.10.0 type hint elision example seems broken

### ISSUE THREAD

**Issue by shawwn** [beartype/beartype#77]
From https://github.com/beartype/beartype#type-hint-elision:

```py
# Import the requisite machinery.
from beartype import beartype
from beartype.vale import IsInstance
from typing import Annotated   # <--------------- if Python ≥ 3.9.0
#from typing_extensions import Annotated   # <--- if Python < 3.9.0

# Type hint matching any non-boolean integer. This day all errata die.
IntNonbool = Annotated[int, ~IsInstance[bool]]   # <--- bruh

# Type-check a list of non-boolean integers summing to a non-boolean
# integer. Beartype wills it. So it shall be.
@beartype
def sum_intlist(my_list: list[IntNonbool]) -> IntNonbool:
    '''
    I cast thee out, mangy booleans!

    You plague these shores no more.
    '''

    return sum(my_list)

```

This should error, but doesn't:
```py
>>> sum_intlist([True, 42, 1, 2, 3])
49
```

This correctly errors:
```py
>>> sum_intlist([True, True, 1, 2, 3])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 39, in sum_intlist
  File "/Users/spresser/ml/beartype/beartype/_decor/_error/errormain.py", line 301, in raise_pep_call_exception
    raise exception_cls(  # type: ignore[misc]
beartype.roar.BeartypeCallHintPepParamException: @beartyped sum_intlist() parameter my_list=[True, True, 1, 2, 3] violates type hint list[typing.Annotated[int, ~IsInstance[builtins.bool]]], as list index 1 item True violates validator ~IsInstance[builtins.bool]:
    False == ~(
     True ==     IsInstance[builtins.bool]
             ).
```

Is this covered in the docs anywhere? I guess it's some sort of optimization, since it would be expensive to check the type of every element in a list for every function call. But it's rather counterintuitive that the docs say "You can prevent booleans from being in this list," and then you can sneak at most 1 boolean into the list. :)

**Comment by shawwn** [comment]
Ah, the docs explain that beartype is designed to work with homogenous collections, not heterogenous collections. In that case, consider a feature request: a way to force beartype to check all items of a collection, rather than nondeterministically sampling from one. (E.g. I'd prefer to validate all items in a ~1024-item list rather than rely on nondeterminism in most cases.)

Maybe I just don't know enough about `beartype` and it already supports this though. Probably something like `Annotated[object, Is[lambda x: all([isinstance( ....` (... well, no, that wouldn't work, because beartype doesn't seem to expose an `isinstance` function that can run at runtime.)

**Comment by leycec** [comment]
> Ah, the docs explain that beartype is designed to work with homogenous collections, not heterogenous collections.

**Yay!** Our documentation finally did something. You're absolutely right, though; the example we initially gave is *really* non-ideal, because it lends the wrong impression and invites gross misunderstandings. I've repaired that to instead resemble:

``` python
   ...

   # Type-check zero or more non-boolean integers summing to a non-boolean
   # integer. Beartype wills it. So it shall be.
   @beartype
   def sum_ints(*args: IntNonbool) -> IntNonbool:
       '''
       I cast thee out, mangy booleans!

       You plague these shores no more.
       '''

       return sum(args)
```

`beartype` deterministically type-checks *all* items of a tuple of variadic positional arguments, as callers typically only pass a small number of arguments variadically. So, that should comport more with basic sanity.

> In that case, consider a feature request: a way to force `beartype` to check all items of a collection...

[Your Christmas wish is our command, Sir Presser.](https://github.com/beartype/beartype/issues/60) Everyone including us *really* want that. Unsurprisingly, that along with [complete deep type-checking support](https://github.com/beartype/beartype/issues/53) are at the top of our "Please do this now or our users will smear Twitter with shopped videos of teddy bears burning on their front lawns" list for 2022.

We hope to definitively nail both later next year – but the road ahead is dark and we're only equipped with a flickering oil lamp from the 1800's handed down from Great Grandpa Moses the grit-covered coal miner. Let's see where we go from here... The hype is palpable.

> I'd prefer to validate all items in a ~1024-item list rather than rely on nondeterminism in most cases.

You're in luck, yet again. [You can actually force this right now, today, even as I am typing these bloated words to you from a ~~creepy~~ cozy cabin in the Canadian wilderness with **beartype validators**](https://github.com/beartype/beartype#full-fat-o-n-matching). Combining type elision with `O(n)` type-checking, for example, yields this iteration on the above ints-not-bools example:

``` python
# Import the requisite machinery.
from beartype import beartype
from beartype.vale import Is
from typing import Annotated   # <--------------- if Python ≥ 3.9.0
#from typing_extensions import Annotated   # <--- if Python < 3.9.0

# Type hint matching all non-boolean integers in a list of non-boolean
# integers in O(n) time. Thus was yet another beautiful thing born.
IntNonBoolList = Annotated[list[int], Is[lambda lst: all(
    (isinstance(item, int) and not isinstance(item, bool))
    for item in lst
)]]

# Type-check all integers in a list of integers in O(n) time. How could you?
@beartype
def sum_intlist(my_list: IntNonBoolList) -> int:
    '''
    The slowest possible integer summation over the passed list of integers.

    There goes your whole data science pipeline. Yikes! So much cringe.
    '''

    return sum(my_list)  # oh, gods what have you done
```

Dangerously untested, of course. But that *should* work... in theory.

> Maybe I just don't know enough about `beartype` and it already supports this though.

*...heh.* You're in luck, yet again! As the above example exhibits, [the `beartype.vale.Is[{func}`] validator is a **functional validator** accepting an arbitrary callable `{func}` with signature `Callable[[Any], bool]]`(https://github.com/beartype/beartype#id35).

Fielding great questions like this is actually why I developed the validator API in the first place: to enable my intrepid userbase to run ahead and develop their own PEP-compliant type hints without waiting for me to get their first. I am slow and always finish last in every race. My wife's the hare; I'm the tortoise. Sure, I'll get to that finish line *eventually* – but I advise just racing ahead of me instead. :speedboat: 

Does that answer all of your wonderful inquisitiveness this festive season?

**Comment by shawwn** [comment]
> Does that answer all of your wonderful inquisitiveness this festive season?

It sure does! Thanks so much for the thorough reply. And my compliments on running the project so well -- `beartype` is one of my new favorite libs. Much appreciated!

Feel free to close this issue (or to keep it open, whichever's most convenient for you).

Merry Christmas-eve-eve-eve, and have a happy new year!

**Comment by leycec** [comment]
Oh, you're most welcome. Thanks so much for the generous compliments, which we'll bask in while otherwise freezing our bits off in the subarctic. Please, pellet stove: Heat this icicle-encrusted place up! We invoke thee!"

Hit us with your best issue if you get any further insights into something we should be doing for you. Until then, Merry **[**_insert ethnic holiday here_**]** to you and yours too! :santa: :gift: :christmas_tree: :star2:
