### ISSUE TITLE
Create Sphinx documentation and host on Read The Docs

### ISSUE THREAD

**Issue by felix-hilden** [beartype/beartype#8]
From #7: Let's build and host the documentation on RTD then! I'd be happy to help in this way, since for me it seems like low-hanging fruit 👍

So what would you like in the documentation, since *beartype* has no API?

I would propose the following, which I did for my library ([RTD site](https://tekore.readthedocs.io/en/stable/) for reference):
- RTD becomes the home site for *beartype*, because there is no ugly file contents blocking the readme, like on GitHub
- We move the changelog and the (extremely) terse reference documentation there into one section, and create another section for tutorials, examples, explanations and such. GitHub readme becomes essentially an introduction to the *repository*, not the package. Although at this stage there's an argument to be made for keeping things in the GitHub readme still.

Thoughts?

**Comment by leycec** [comment]
**Yup.** This is the way. <sup>*Thanks, Mandalorian.*</sup>

I at least had the marginal foresight to format our current `README` as reStructuredText (reST). So, this should be a less painful transition than the [blood-dimmed tide of anarchy](https://poets.org/poem/second-coming) I'd initially envisioned. I just need to start toying around with [Sphinx](https://www.sphinx-doc.org/en/master) on my local geriatric devbox mostly.

On a natural scale of **[1—11]** where **1** is *"Do everything else first..."* and **11** is *"Do this now or the Baby Yoda gets it!"*, where would you say this personally lands in importance for you?

It goes without saying that all future @beartype projects like the proposed `deeptyping` and `pepitup` will use an RTD-hosted setup from the get-go.

**Comment by felix-hilden** [comment]
Neat! Well, I could certainly lend a few hours for it tomorrow, which should be enough to at least some version up, so let's say a 7/11 😉 I can't remember if RTD requires write access to the repo. It shouldn't though, so once the PR is merged, the documentation will begin building. The appearance can be checked with local builds anyway, it's more so a matter of configuring RTD. Until tomorrow, then!

**Comment by leycec** [comment]
**Wow.** Our first prospective PR! The excitement just keeps building.

I will, of course, promptly merge pretty much *anything* you propose. Since we currently have nothing, anything is already a distinct improvement worthy of everyone's praise and gratitude. :partying_face:

**Comment by leycec** [comment]
Optional endgame bonus points if we wire up this mysterious magic through GitHub Actions, too. Since we already automate both stable releases and continuous integration with GitHub Actions, adding RTD to that zesty mix would be the *crème de la crème.* :cake: 

Helpfully, I just stumbled across a [third-party GitHub Action that possibly streamlines that](https://github.com/dfm/rtds-action#2-set-up-github-actions-workflow). In theory, adding a new step using `dfm/rtds-action@v1` to our existing `.github/workflows/pythonrelease.yml` file might get us where we want to go. Maybe?

You decide, RTD maestro! We're in your capable hands.

**Comment by leycec** [comment]
**Boom!** :boom: 

I felt miserable both inside and outside for letting you do all the heavy administrative lifting here, so I finally put the DualShock 4 (DS4) down and went to volunteer work. Specifically, I've quick-started a Sphinx configuration in our existing `doc/` directory enabling the standard retinue of builtin Sphinx extensions (e.g., `autodoc`, `viewcode`) as well as:
* MathJax configured for remote implicit usage.
* Napolean configured for NumPy-formatted docstrings.

Of course, `make html` basically builds nothing at the moment. It is sad! This is where I left off for tonight. Tomorrow, I'll roll up my grease-covered sleeves and dig in a bit deeper. Immediate work includes:

1. Define a sane top-level `.readthedocs.yml` configuration.
1. Wire `make html` up to `autodoc` to generate API documentation. Not that we have any, of course... but someday. Someday we will, by Guido.
1. Shift the majority of our existing `README.rst` into various reST files in the `doc/source/` subdirectory.

Task **3.** is *definitely* where we need the most volunteer assistance. I'm happy to tackle the former two tasks, but that third task... that's a doozie. Would you like to handle a bit of that with a PR or two? No pressure, obviously. I'm delighted just to have somebody meaningfully prodding me to get started on this. Since I'm getting light-headed just thinking about task 3, it's now time to play JRPGs. *Yay!* :video_game:

**Comment by felix-hilden** [comment]
Yep exactly! The auto builds are convenient as anything. I'm glad you got it started already. And in that case we could separate the changes into two PRs: one for content, and one for configuration. I'll get to work and we'll see what comes of it in the PRs!

**Comment by felix-hilden** [comment]
Also, what are your views on Beartype presentation? Is it simply a lower-case beartype, perhaps in *black*-esque italics as *beartype*, headings capitalised like Beartype, or would you like a simple logo like this:

![beartype](https://user-images.githubusercontent.com/25202257/104578271-32dc9500-5663-11eb-9ae2-29ac4bcce25e.png)

**Comment by leycec** [comment]
**Oh.** Oh, Felix Hildén. That bear-friendly logo is indescribably awesome and very @leycec-approved. Did you just mock that up? 'cause... I really couldn't do that. I sling code and pretend to sling documentation. That's it. Your multi-paradigmal prowess puts you five levels ahead of my power curve.

Salient questions: is that vector line art your own personal creation? If so, congratulations and would you consent to either transferring copyright to @beartype *or* explicitly publishing that under an MIT-compatible creative license like, say, [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/)? Either is absolutely fine, of course; you're the impressive graphical wizard in the room. If not, is that art published elsewhere under such a license or <sup>\*gulp\*</sup> depressingly copyright-encumbered and that was just a tantalizing taste of things to come?

Bears! Bears everywhere, I say. :bear: :bearded_person: :teddy_bear:

**Comment by leycec** [comment]
Also, my wife loves it. This is the most important criteria.

**Comment by felix-hilden** [comment]
That's awesome to hear 😄 yeah sure it is, under the copyright clause §11 "Hoping no one notices" that it's a black-and-white overlay on the first result of image searching "bear"... I'm not an expert on the matter, but I guess that makes it a new picture, or at least an insignificant infringement. I'll make a clean version of with some variations so you can choose on you like the most!

If it is mine to give, I hereby grant the lisence of any logo material I present here or in any PRs to *beartype*. I'll also not edit this message even for fixing mistakes, so that the validity of this message doesn't get questioned. Nevermind the fact that I could delete it at any time. But let's trust me that tiny bit, I think that'd be fair.

Yeah, I got burned by the dark theme [myself](https://github.com/felix-hilden/tekore/issues/235) recently too. A white outline was a fine solution, so I'll include that in the images as well! Any opinion on size?

I guess that bear thing could be true 😄 I of course can only recite a handful, but seeing that the list also includes "mörkö" and such, now commonly used to refer to just generally big and scary things, I can see that there could be many more that originally have referred to bears. My favourite of the presented ones must be "mesikämmen" though, literally translated as honey hand (or even more literally: nectar palm)!

**Comment by felix-hilden** [comment]
Here are the clean versions!
![see-through](https://user-images.githubusercontent.com/25202257/104699003-cb821c00-571a-11eb-9f03-3df9e2870d68.png)
![black background](https://user-images.githubusercontent.com/25202257/104699027-d177fd00-571a-11eb-8d04-e8fd4f8aaed4.png)
![small scale](https://user-images.githubusercontent.com/25202257/104699225-1439d500-571b-11eb-9be9-822328070117.png)

**Comment by leycec** [comment]
> ...under the copyright clause §11 "Hoping no one notices"

**OMG.** You even used the Unicode character for the typographical section sign §. Who outside of the morally grey law profession even knows about the glyph resembling a boa constrictor that just digested my favourite cat?

...Felix. Felix Hildén, Computer Vision Expert, A-Grade. That's who.

> ...it's a black-and-white overlay on the first result of image searching "bear"... I'm not an expert on the matter, but I guess that makes it a new picture, or at least an insignificant infringement.

Leave it to the computer vision expert to use computer vision to generate logos for a potential new dependency for... *computer vision.*

That mostly sounds like a novel creation of your own invention to me. So, let's go with that. When the Pro-bear Legal Consortium comes after me, I'll profess ignorance and pretend not to know where you're from: "I'm pretty sure he was from Norway."

> My favourite of the presented ones must be "mesikämmen" though, literally translated as honey hand (or even more literally: nectar palm)!

*Nectar palm.* Oh, Scandinavian funny man. This is solid gold. The next time I spot a Canadian brown bear desperately rummaging through our backyard compost, I'll reassure my wife there's really nothing to fear. After all... it's just got a nectar palm, honey.

> Here are the clean versions!

**Yup.** This solidifies your hallowed status as first up in our new *Contributors* section, which I have yet to write but will just as soon as I put down the controller and step away from the Man Cave.

I'll also directly credit you immediately beneath your logo wherever we use it, possibly in midget text. Sample citation follows:

![Bear Boss](https://user-images.githubusercontent.com/25202257/104699027-d177fd00-571a-11eb-8d04-e8fd4f8aaed4.png)
<sup>Felix Hildén (@felix-hilden), also known as "Bear Boss," made this.</sup>

My wife and I mutually adore this black, *really black* bear. His name is Mr. Nectar Palm. If it's not too much more trouble... would attaching Mr. Nectar Palm to the [black, *really black* **beartype** logo you previously drafted](https://github.com/beartype/beartype/issues/8#issuecomment-760103474) be feasible? Please don't kick me.

Lastly, what would you say to [releasing both of the clean versions under some sort of Creative Commons license](https://chooser-beta.creativecommons.org)? You pick the license. Anything goes.

The main benefit of licensing isn't for us, actually – it's for everybody else. This is clearly creative genius. It'd be super if other projects had the opportunity to reuse your sterling handiwork, too.

All of this can wait until Monday or much, much later. Enjoy the weekend. You've earned it, Bear Boss.

**Comment by felix-hilden** [comment]
You're too much man 😄 (dare I say, too much to... *bear*) but it does stroke my ego in a special way, which I'm biologically programmed to crave 😄 I appreciate your never-ending kindness - it's like an invitation for a cup of chocolate on a cold winter day ❄️ And that's a perfect name for the bear! Also "Bear boss" sounds needlessly bad ass but I'll take it 😂

Yeah I'll attach the text next. Actually, that asset repository thing sounds pretty good, since I haven't really released images to any website services ever. MIT is a-ok for me, although the CC licenses seem more appropriate for images. And in that case it would be nice to include *beartype* in the attributions as well! I can figure something with the lisence file and readme once the repo is up!

Nah, no worries! I do this for fun, so weekends aren't really an issue 😄 But of course it's all good if you have sanctified your weekend for other activities!

**Comment by felix-hilden** [comment]
Now would you like... something basic for safety:
![beartype-calibri](https://user-images.githubusercontent.com/25202257/104807147-4f083f80-57e5-11eb-85c3-637178792117.png)
or perhaps a narrow one to assert the importance and absolute seriousness of the library:
![beartype-bahnschrift-lc](https://user-images.githubusercontent.com/25202257/104807137-3a2bac00-57e5-11eb-8b11-0c285d4ccc87.png)
or something with a little more character:
![beartype-candara](https://user-images.githubusercontent.com/25202257/104807156-60514c00-57e5-11eb-9a7a-02cb072675b2.png)

Personally, besides the basic clean look I quite enjoy a bit of character. At the risk of sounding pretentious as all hell, that last one made with "Candara" kinda reminds me of foresty branches or whatever. Nevermind the positioning for now, I couldn't be arsed to widen the background. But I think it should be more or less how the first one is.

I'll figure out an outline for the text as well after we choose the font!

**Comment by leycec** [comment]
**Oh. Oh.** This must surely be the Eighth Wonder of the design world. My soul is now so stuffed with beautiful typography and aesthetic art that my face hurts from smiling.

Things I have done:

* [Credited you in our new *Authors* section](https://github.com/beartype/beartype#authors). Bask as you receive global applause!

Things I have *not* done include anything else, such as:

* Read The Docs repository importation. *I know, I know.* I just have to click a friggin' button. **Urgh!** I meant to. Really. But then this super-nice Londoner named @harens [told us all about his amazing MacOS MacPorts installer for `beartype`](https://github.com/beartype/beartype/issues/12), which was so amazing that I didn't do anything else. In short, I blame @harens.
* `beartype/beartype-assets` repository creation. I want this branding *sooo* bad, which means this will happen first thing ~~tomorrow~~ today, unless something else blows up on our issue tracker. I pray for silence.

**Comment by felix-hilden** [comment]
No worries! 😃 Hope you had a battery-recharging weekend, playing japanese metal-RPGs I presume 😜 My poison is power-metal and soccer with flying cars.

So which of the three tickles your taste the most? Or would you like even wilder suggestions? I'm assuming you'd like to have a say in it of course :D but if you'd like for me to just fin(n)ish it myself, I can shoot a PR to the repo once it's created with my picks. Either one is completely fine!

**Comment by leycec** [comment]
> My poison is power-metal and...

*Power metal!* Yes! Yes! I penitently knelt and worshipped like a teenage hobbit hopped up on magical rings before [Blind Guardian at Wacken 2007 in Deutschland at the glorious height of The Bard's prime and still the most majestic power metal concert I've ever given myself whiplash to](https://www.youtube.com/watch?v=veiIRX_SMms). I am somewhere in that crowd, bloodied but unbroken. If you see someone repeatedly kicked in the back of the head by crowd surfers, it's me.

I was lucky enough to be conducting AI research with the [Technologie-Zentrum Informatik (TZI) at the University of Bremen, Germany](https://www.uni-bremen.de/tzi) at the time. They let me attend Wacken, which makes them upstanding human beings. One of them had even heard of Wacken. To no one's surprise, he was in a hard rock band.

I now feel mildly sad that live concerts no longer exist. As a palliative, I'll just leave this here: **_["VALHALLLLLLLLLA!"](https://www.youtube.com/watch?v=CZ_VFJn2kJM)_**

<sup>*We do not talk about [their most recent LP](https://rateyourmusic.com/release/album/blind-guardian-twilight-orchestra/legacy-of-the-dark-lands).*</sup>

> ...soccer with flying cars.

*Rocket Arena!* Yes! Yes! Competitively bump those balls into the gaping hole!

> So which of the three tickles your taste the most?

I see you are a man of typography and culture.

To heck with safety air bags! We are metaphorically bound together as one in cheesy metallic brotherhood. I just talked about giving myself whiplash and getting repeatedly kicked in the back of the head. I was born and raised in urban poverty adjacent to the infamous concrete canals of Los Angeles, as [featured in every worthwhile action movie ever](https://www.youtube.com/watch?v=41qWnyMuJPY).

It's safe to say safety is a low personal priority. I wholeheartedly embrace *Candara,* the font whose name sounds like the hot Portuguese exchange student no one could ever work up the courage to talk to.

Relatedly, [`beartype-assets` is now a thing and you have full push access to that thing](https://github.com/beartype/beartype-assets). It's currently a vacuous void of nihility, aside from the top-level `banner/` directory containing an MIT license attributed to you.

*You can change that.* Feel free to push whatever vector or bitmap images you like – or even change the license and directory name, if you like. I reluctantly adopted the MIT license rather than, say, the arguably more art-appropriate [Creative Commons Attribution 4.0 International (CC BY 4.0) license](https://creativecommons.org/licenses/by/4.0/deed.ast). This is entirely to avoid potential conflicts with the MIT license of the core `beartype/beartype` project (i.e., this thing).

**The power is in your hands.** Also, [is this not the most triumphant power metal cover of all time and space?](https://www.youtube.com/watch?v=eur7sB9nUY0) <sup>*Yes. Yes, it is.*</sup>

**Comment by felix-hilden** [comment]
That sounds awesome 😄 the songs seem pretty good as well! And yeah that Rhapsody of Fire is epic 🤘 I like a bit of [fun](https://www.youtube.com/watch?v=DamWr3wdy_g) <sup>see the description</sup> in the songs, and sufficiently [*fantastical*](https://www.youtube.com/watch?v=CCnn7WEQIDI) lyrics :D some German [folk](https://www.youtube.com/watch?v=83aRH4XmGXw) is always welcome too! It's quite exhilarating to hear singing from heights that are [seemingly unnecessary](https://www.youtube.com/watch?v=3ubKaNrfwVI) or [just perfect](https://www.youtube.com/watch?v=mTRqXuqpc_8) 🎤

We'll go with the unreachable beauty that is the hot Portugese exchange student Candara then! 💃 I'll see what could be done about mixing the licenses, but that discussion will continue on *assets*. Maybe we'll leave this issue open until the logos are put in place in this repository as well!

**Comment by leycec** [comment]
> some German folk is always welcome too!

*Equilibriuuuuuuuuuuum!* "Turis Fratyr," "Sagas," and "Erdentempel" are all engraved **on my very soul.** It hurt, as you might expect. But it was worth it.

But nobody does melodic viking metal like the Finns. I mean, come on! It's not even a fair beer stein contest. Ensiferum, Havukruunu, Wintersun, and the God-tier *Moonsorrrrrrrrrrrrow* dominate all that once proudly rode on longships across the Gulf of Finland to bravely pillage innocent foreign lands in the hallowed  name of Odin Himself.

Okay, so maybe they shouldn't have done that. But they did – and at least humanity now has [**V: Hävitetty**](https://www.youtube.com/watch?v=pa885g6oeMc) to show for it.

> Auringon kuoleman syntyäkseen
> Uusi maailma tarvitsee
> Vain pisaran vettä kylmyyteen
> Käsillä juoksemaan ihmisten

**Comment by NowanIlfideme** [comment]
Hey, to avoid rewriting the docs too much from that insane (and beautiful) readme, why not [MkDocs](https://www.mkdocs.org/)? You can keep the docs in markdown, use whatever theme you want (I like the `material` theme).

Here's how I did it in my own project in 4 files:
- [Site structure, themes, etc.](https://github.com/NowanIlfideme/pydantic-yaml/blob/main/mkdocs.yml)
- [ReadTheDocs configuration](https://github.com/NowanIlfideme/pydantic-yaml/blob/main/.readthedocs.yaml)
- [The docs pages themselves](https://github.com/NowanIlfideme/pydantic-yaml/tree/main/docs)

And here's [the completed site](https://pydantic-yaml.readthedocs.io/en/latest/?badge=latest)

If you want, I can contribute this relatively easily, however someone (I imagine @leycec) would need to set up the link to RTD and debug any issues that come up.

**Comment by leycec** [comment]
Why. Why, GitHub UX designer, did you place the **Close with comment** button next to the **Comment** button! I rage.

**Comment by felix-hilden** [comment]
Oh, very nice! <sub>and yeah damn that's intense 😄</sub> Looking forward to seeing the new docs!

**Comment by leycec** [comment]
You *so* nice, Felix. :hugs: 

In the spirit of solidarity with all nations bordering the mangy Russian Bear, I thought you might like this sneak preview of my  hideous bastardization of your original magnum opus. (I speak, of course, of [**Mr. Nectar Palm**](https://github.com/beartype/beartype-assets/tree/main/banner).)

Presenting... **[Mr. Hypno-Nectar Palm](https://github.com/beartype/beartype-assets/tree/main/brand)**!

![Mr. Hypno-Nectar Palm](https://github.com/beartype/beartype-assets/raw/main/brand/brand-2600x800.png)

I'll be splashing this across my **Sponsors** page when that *finally* goes live in a few days. Thanks again for all tremendous efforts in the early days of @beartype. Your legend grows by the day.

**Comment by felix-hilden** [comment]
😂 ahh that's great. I see club lights, hear psytrance, and my leg is starting to shake!

On a serious note though, it's been great to see Beartype grow and mature! You've done great work, and it seems that many people think the same 👌

**Comment by davidfstr** [comment]
+1 to create a dedicated documentation site. The README currently weighs in at over 90 printed pages. Very difficult to navigate. 

The tutorial - arguably one of the more important sections to put near the beginning - is currently ~80% through the entire page-ream.

**Comment by leycec** [comment]
**You're not wrong, Dave.** You never are. After all, you're a digital archivist! That means you're amazing and are doing the good work on behalf of future generations. Their plaintive  "~~~thank you~~~" can almost be heard from here.

Luckily, [ReadTheDocs (RTD) hosting](https://beartype.readthedocs.io) is our ongoing priority after resolving minor (but paradoxically critical) issues like #117. This restructuring would've already been *fait accompli*, but configuring Sphinx has proved... non-trivial. The pain is real.

I'm actually reminded of Vim here. Just like Vim:

* Sphinx is *basically* non-functional out-of-the-box.
* Sphinx requires extreme customization to provide even a reasonable facsimile of readable and maintainable documentation.

Because wrestling Sphinx into the mud is consuming more time than even I envisioned in my worst deep dev dreams, I'm temporarily abandoning automatic API generation. Instead, the focus now is to just revise our monolithic `README.rst` into multiple reST documents cross-referencing one another.

It's a feeble dream. But it's my dream. :sleeping:

**Comment by hhoeflin** [comment]
There are also pretty good autodoc plugins now for mkdocs. Maybe that would work better for you.

**Comment by leycec** [comment]
**Gah!** Our existing monolithic `README.rst` has become repugnant. With `beartype 0.11.0` and the issue tracker mostly quiet, I'm declaring a soft feature freeze as I head back into the Sphinx rabbit hole.

This time, we *are* doin' this – mostly because I'm stealing everything that's not nailed down from the Sphinx configuration and directory structure of my favourite mobile-friendly Python project: [**KivyMD**](https://kivymd.readthedocs.io/en/latest). Astonishingly, this is actually working. They already did all the heavy Sphinx lifting and now I parasitically feed like a rabid leech. :grin: 

The three-week plan is for a **full-scale transition to Read The Docs (RTD)** by Halloween. Then we disembowel our `README.rst` and pretend the last two years of doco shame never happened.

<sup>*pump that fist in the air like you just don't care*</sup>

**Comment by hhoeflin** [comment]
Whenever I get one of your issue messages in my inbox, I always smile a little :)

**Comment by posita** [comment]
Regarding @hhoeflin's suggestion above as well as https://github.com/mkdocstrings/griffe/issues/75#issuecomment-1264324768, and at the risk of sending this whole thing off the rails, I'm happy to consult if MkDocs is still being considered as an alternative. (My apologies for completely dropping the ball after [raising this approach before](https://github.com/posita/numerary/issues/8#issuecomment-1089972175).) I _don't_ know if I can commit to a Halloween deadline, though. :grimacing:

**Comment by leycec** [comment]
Aww! Beartype doco bros is the best. :smiling_face_with_three_hearts: 

Let this stand as a monolith in the sand to future generations: **Use MkDocs Ye Who Tread Here.** Sadly, I can't take the advice of my own monolith. @posita and all the open-source heroes at MkDocs have the right of it: everyone (including me), just use MkDocs **+** the [stunning Material theme](https://squidfunk.github.io/mkdocs-material/) **+** the [stunning `mkdocstrings` extension](https://github.com/mkdocstrings/mkdocstrings).

That would be the right thing to do. Which is exactly why I'm not doing that!

Hah! You didn't realize you were dealing with an imbecile, @posita. Gritty low-level combat with illegible configuration files that are actually executed Python code is what I'm *really* here for. Firing up Vim on an undocumented Sphinx `conf.py` configuration is like unsheathing that immaculate katana you've been polishing every night for fifty years at the onset of a samurai bloodbath with heartless ninjas sent by the rabid shogun that will define your career as a masterless ronin. You just know heads are gonna roll – and you know you're the Big Boss when they do and you're still standing.

![it do be like this](https://media.tenor.com/I0uPUEBX40UAAAAC/samurai-champloo-katana.gif)
<sup>*pictured:* the surprisingly supple hands of @leycec.</sup>

**Comment by leycec** [comment]
**Resolved by 86b79db.**

[Beartype documentation now officially lives at ReadTheDocs (RTD)](https://beartype.readthedocs.io). Our `README.rst` file has been truncated to a shadow of its former self. So this is what it feels like when bears cry.

![omg](https://media.tenor.com/JC2gzaAISiEAAAAC/sweaty-sweat.gif)

**Comment by bionicles** [comment]
yo, sorry to necro, just mentioning, the cool logo you guys made is not loading on the docs page, might be missing asset file or wrong path 

![image](https://github.com/beartype/beartype/assets/24532336/48214de7-a3e6-46a0-9fe5-df0831fb4ed6)

**Comment by rbnhd** [comment]
@bionicles 
Yup ! Maybe the real logo was the bears we made along the way

<img width="567" alt="Image" src="https://github.com/user-attachments/assets/2254e971-aeae-4e47-a12e-bb4b60d5bcd2" />
