### ISSUE TITLE
Slow for bad types.

### ISSUE THREAD

**Issue by mvaled** [beartype/beartype#91]
I took the the same example in the readme and introduced a type error, by replacing the list to `[[["0"]*1000]*1000]*100]` (only 100m because I don't have much patience):

```
$ python -m timeit -n 1 -r 1 -s '
from beartype import beartype

@beartype
def behold(the_great_destroyer_of_apps: list[list[list[int]]]) -> int:
    return len(the_great_destroyer_of_apps)

def bad_player():
    try:
        behold([[["a"]*1000]*1000]*100)
    except:
        pass

' 'bad_player()'
1 loop, best of 1: 37 sec per loop
```

I ran this in Python 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0] on linux, and installed `beartype` like this: `pip install git+https://github.com/beartype/beartype.git@main`

**Comment by leycec** [comment]
**Wow.** You just exposed a severe performance regression in `@beartype`, @mvaled – and from Cuba no less! I am equally stunned and grateful. If you're at home chugging on gluten-free Sweet Chili Heat Doritos and both curious and appalled by what you are reading, here's a play-by-play on this minor crisis:

1. `@beartype` is efficiently type-checking your worst-case `[[["a"]*1000]*1000]*100` input to be bad. That's fast, so that's good. But that's only the beginning of this ugly expose into the criminal underworld of bad types, because...
2. `@beartype` then raises a human-readable exception describing the failure of that list to satisfy the type hint. To do so, `@beartype` previously **(A)** stringified that list into a string with the standard `pprint.saferepr()` function and then **(B)** truncated that string to 80 characters with a compiled regular expression. Both **(A)** and **(B)** are surprisingly slow for worst-case input like, say... oh I don't know, *a list of 100 sublists of 1000 sublists of 1000 iterations of the character `a`.* That's bad.

To ensure this *never* happens again, our test suite now explicitly guards against these sorts of underhanded shenanigans with a sprawling unit test.

Thanks *so* much for the exciting (yet unsettling) edge case that caused my heart to skip five beats in a row. We'll get this patched up for everyone in a jiffy.

![me irl rn](https://i.kym-cdn.com/photos/images/newsfeed/001/406/358/91b.jpg)

**Comment by leycec** [comment]
**Phew.** Patched that right up for you. Let us know if you hit any other unspeakable evils while using @beartype. Until then, thanks for the excellent catch and best of luck throughout 2022!
